@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title GoVietStay - Remove Phu Quoc Hero Logo ONLY

set "REPO=%USERPROFILE%\Documents\GitHub\govietstay-main-website"
if not exist "%REPO%\package.json" (
  if exist "%USERPROFILE%\OneDrive\Documents\GitHub\govietstay-main-website\package.json" (
    set "REPO=%USERPROFILE%\OneDrive\Documents\GitHub\govietstay-main-website"
  ) else if exist "%CD%\package.json" (
    set "REPO=%CD%"
  ) else (
    echo [STOP] Khong tim thay project govietstay-main-website.
    echo Thu muc du kien:
    echo   %%USERPROFILE%%\Documents\GitHub\govietstay-main-website
    echo hoac chay BAT ngay trong project.
    pause
    exit /b 1
  )
)

cd /d "%REPO%"
set "TARGET=components\PhuQuocJohnsCatalog.tsx"

echo.
echo ============================================================
echo   GOVIETSTAY - REMOVE HERO IMAGE LOGO ONLY
echo   EN: /tours/phu-quoc
echo   RU: /ru/tours/phu-quoc
echo   Target: components/PhuQuocJohnsCatalog.tsx
echo ============================================================
echo.

for /f "delims=" %%B in ('git branch --show-current') do set "BRANCH=%%B"
if /i not "!BRANCH!"=="main" (
  echo [STOP] Dang o branch !BRANCH!, can branch main.
  pause
  exit /b 1
)

if not exist "%TARGET%" (
  echo [STOP] Khong tim thay %TARGET%
  pause
  exit /b 1
)

git diff --quiet -- "%TARGET%"
if errorlevel 1 (
  echo [STOP] %TARGET% dang co thay doi chua commit.
  echo De tranh ghi de code dang lam, BAT dung tai day.
  git diff -- "%TARGET%"
  pause
  exit /b 1
)

git diff --cached --quiet -- "%TARGET%"
if errorlevel 1 (
  echo [STOP] %TARGET% dang duoc stage tu truoc.
  pause
  exit /b 1
)

echo [1/5] Xoa CHI logo card mau trang de tren anh hero...
set "GVS_ROOT=%REPO%"
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAiAFMAdABvAHAAIgAKAAoAJAByAG8AbwB0ACAAPQAgACQAZQBuAHYAOgBHAFYAUwBfAFIATwBPAFQACgBpAGYAIAAoAFsAcwB0AHIAaQBuAGcAXQA6ADoASQBzAE4AdQBsAGwATwByAFcAaABpAHQAZQBTAHAAYQBjAGUAKAAkAHIAbwBvAHQAKQApACAAewAKACAAIAAgACAAdABoAHIAbwB3ACAAIgBHAFYAUwBfAFIATwBPAFQAIABpAHMAIABlAG0AcAB0AHkALgAiAAoAfQAKAAoAJAB0AGEAcgBnAGUAdAAgAD0AIABKAG8AaQBuAC0AUABhAHQAaAAgACQAcgBvAG8AdAAgACIAYwBvAG0AcABvAG4AZQBuAHQAcwBcAFAAaAB1AFEAdQBvAGMASgBvAGgAbgBzAEMAYQB0AGEAbABvAGcALgB0AHMAeAAiAAoAaQBmACAAKAAtAG4AbwB0ACAAKABUAGUAcwB0AC0AUABhAHQAaAAgACQAdABhAHIAZwBlAHQAKQApACAAewAKACAAIAAgACAAdABoAHIAbwB3ACAAIgBNAGkAcwBzAGkAbgBnACAAYwBvAG0AcABvAG4AZQBuAHQAcwBcAFAAaAB1AFEAdQBvAGMASgBvAGgAbgBzAEMAYQB0AGEAbABvAGcALgB0AHMAeAAiAAoAfQAKAAoAJAB0AGUAeAB0ACAAPQAgAFsASQBPAC4ARgBpAGwAZQBdADoAOgBSAGUAYQBkAEEAbABsAFQAZQB4AHQAKAAkAHQAYQByAGcAZQB0ACkACgAKACQAbgBlAGUAZABsAGUAIAA9ACAAIgAvAGIAcgBhAG4AZAAvAGcAbwB2AGkAZQB0AHMAdABhAHkALQBwAGgAdQAtAHEAdQBvAGMALQBsAG8AZwBvAC4AcABuAGcAIgAKACQAcABvAHMAaQB0AGkAbwBuAHMAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4AQwBvAGwAbABlAGMAdABpAG8AbgBzAC4ARwBlAG4AZQByAGkAYwAuAEwAaQBzAHQAWwBpAG4AdABdAAoAJABzAHQAYQByAHQAIAA9ACAAMAAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGkAIAA9ACAAJAB0AGUAeAB0AC4ASQBuAGQAZQB4AE8AZgAoACQAbgBlAGUAZABsAGUALAAgACQAcwB0AGEAcgB0ACwAIABbAFMAdAByAGkAbgBnAEMAbwBtAHAAYQByAGkAcwBvAG4AXQA6ADoATwByAGQAaQBuAGEAbAApAAoAIAAgACAAIABpAGYAIAAoACQAaQAgAC0AbAB0ACAAMAApACAAewAgAGIAcgBlAGEAawAgAH0ACgAgACAAIAAgACQAcABvAHMAaQB0AGkAbwBuAHMALgBBAGQAZAAoACQAaQApAAoAIAAgACAAIAAkAHMAdABhAHIAdAAgAD0AIAAkAGkAIAArACAAJABuAGUAZQBkAGwAZQAuAEwAZQBuAGcAdABoAAoAfQAKAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACgAIgBMAG8AZwBvACAAcABhAHQAaAAgAG8AYwBjAHUAcgByAGUAbgBjAGUAcwAgAGIAZQBmAG8AcgBlADoAIAAiACAAKwAgACQAcABvAHMAaQB0AGkAbwBuAHMALgBDAG8AdQBuAHQAKQAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABDAHkAYQBuAAoACgBpAGYAIAAoACQAcABvAHMAaQB0AGkAbwBuAHMALgBDAG8AdQBuAHQAIAAtAGUAcQAgADEAKQAgAHsACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsATwBLAF0AIABPAG4AbAB5ACAAbwBuAGUAIABQAGgAdQAgAFEAdQBvAGMAIABsAG8AZwBvACAAcgBlAG0AYQBpAG4AcwAgAGEAbAByAGUAYQBkAHkALgAgAE4AbwB0AGgAaQBuAGcAIAB0AG8AIAByAGUAbQBvAHYAZQAuACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAIAAgACAAIABlAHgAaQB0ACAAMQAwAAoAfQAKAGkAZgAgACgAJABwAG8AcwBpAHQAaQBvAG4AcwAuAEMAbwB1AG4AdAAgAC0AbgBlACAAMgApACAAewAKACAAIAAgACAAdABoAHIAbwB3ACAAIgBFAHgAcABlAGMAdABlAGQAIABlAHgAYQBjAHQAbAB5ACAAMgAgAG8AYwBjAHUAcgByAGUAbgBjAGUAcwAgAG8AZgAgAHQAaABlACAAUABoAHUAIABRAHUAbwBjACAAbABvAGcAbwAgAHAAYQB0AGgALAAgAGYAbwB1AG4AZAAgACQAKAAkAHAAbwBzAGkAdABpAG8AbgBzAC4AQwBvAHUAbgB0ACkALgAgAFMAdABvAHAAcABpAG4AZwAgAHQAbwAgAGEAdgBvAGkAZAAgAHIAZQBtAG8AdgBpAG4AZwAgAHQAaABlACAAdwByAG8AbgBnACAAZQBsAGUAbQBlAG4AdAAuACIACgB9AAoACgAkAHMAZQBjAG8AbgBkACAAPQAgACQAcABvAHMAaQB0AGkAbwBuAHMAWwAxAF0ACgAKACMAIABMAG8AYwBhAHQAZQAgAHQAaABlACAAbgBlAGEAcgBlAHMAdAAgAHcAaABpAHQAZQAtAGMAYQByAGQAIABEAEkAVgAgAGIAZQBmAG8AcgBlACAAdABoAGUAIABTAEUAQwBPAE4ARAAgAGwAbwBnAG8ALgAKACQAcAByAGUAZgBpAHgAUwB0AGEAcgB0ACAAPQAgAFsATQBhAHQAaABdADoAOgBNAGEAeAAoADAALAAgACQAcwBlAGMAbwBuAGQAIAAtACAAMgA1ADAAMAApAAoAJABwAHIAZQBmAGkAeAAgAD0AIAAkAHQAZQB4AHQALgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAcAByAGUAZgBpAHgAUwB0AGEAcgB0ACwAIAAkAHMAZQBjAG8AbgBkACAALQAgACQAcAByAGUAZgBpAHgAUwB0AGEAcgB0ACkACgAKACQAbQBhAHQAYwBoAGUAcwAgAD0AIABbAHIAZQBnAGUAeABdADoAOgBNAGEAdABjAGgAZQBzACgACgAgACAAIAAgACQAcAByAGUAZgBpAHgALAAKACAAIAAgACAAJwA8AGQAaQB2AFwAcwArAGMAbABhAHMAcwBOAGEAbQBlAFwAcwAqAD0AXABzACoAWwAiACcAJwBdAFsAXgAiACcAJwBdACoAYgBnAC0AdwBoAGkAdABlAFsAXgAiACcAJwBdACoAWwAiACcAJwBdAFsAXgA+AF0AKgA+ACcALAAKACAAIAAgACAAWwBUAGUAeAB0AC4AUgBlAGcAdQBsAGEAcgBFAHgAcAByAGUAcwBzAGkAbwBuAHMALgBSAGUAZwBlAHgATwBwAHQAaQBvAG4AcwBdADoAOgBJAGcAbgBvAHIAZQBDAGEAcwBlAAoAKQAKAAoAaQBmACAAKAAkAG0AYQB0AGMAaABlAHMALgBDAG8AdQBuAHQAIAAtAGUAcQAgADAAKQAgAHsACgAgACAAIAAgAHQAaAByAG8AdwAgACIAQwBvAHUAbABkACAAbgBvAHQAIABzAGEAZgBlAGwAeQAgAGkAZABlAG4AdABpAGYAeQAgAHQAaABlACAAdwBoAGkAdABlACAAbABvAGcAbwAtAGMAYQByAGQAIAB3AHIAYQBwAHAAZQByACAAbgBlAGEAcgAgAHQAaABlACAAcwBlAGMAbwBuAGQAIABsAG8AZwBvAC4AIABOAG8AIABmAGkAbABlACAAdwBhAHMAIABjAGgAYQBuAGcAZQBkAC4AIgAKAH0ACgAKACQAbQAgAD0AIAAkAG0AYQB0AGMAaABlAHMAWwAkAG0AYQB0AGMAaABlAHMALgBDAG8AdQBuAHQAIAAtACAAMQBdAAoAJABiAGwAbwBjAGsAUwB0AGEAcgB0ACAAPQAgACQAcAByAGUAZgBpAHgAUwB0AGEAcgB0ACAAKwAgACQAbQAuAEkAbgBkAGUAeAAKACQAbwBwAGUAbgBUAGEAZwBFAG4AZAAgAD0AIAAkAHAAcgBlAGYAaQB4AFMAdABhAHIAdAAgACsAIAAkAG0ALgBJAG4AZABlAHgAIAArACAAJABtAC4ATABlAG4AZwB0AGgACgAKAGkAZgAgACgAJABiAGwAbwBjAGsAUwB0AGEAcgB0ACAALQBnAGUAIAAkAHMAZQBjAG8AbgBkACkAIAB7AAoAIAAgACAAIAB0AGgAcgBvAHcAIAAiAFMAYQBmAGUAdAB5ACAAYwBoAGUAYwBrACAAZgBhAGkAbABlAGQAOgAgAHcAcgBhAHAAcABlAHIAIABkAG8AZQBzACAAbgBvAHQAIABiAGUAZwBpAG4AIABiAGUAZgBvAHIAZQAgAHQAaABlACAAcwBlAGMAbwBuAGQAIABsAG8AZwBvAC4AIgAKAH0ACgAKACMAIABGAGkAbgBkACAAdABoAGUAIABtAGEAdABjAGgAaQBuAGcAIAA8AC8AZABpAHYAPgAsACAAYgBhAGwAYQBuAGMAaQBuAGcAIABuAGUAcwB0AGUAZAAgAGQAaQB2ACAAdABhAGcAcwAuAAoAJAB0AGEAZwBSAGUAZwBlAHgAIAA9ACAAWwByAGUAZwBlAHgAXQA6ADoAbgBlAHcAKAAnADwALwA/AGQAaQB2AFwAYgBbAF4APgBdACoAPgAnACwAIABbAFQAZQB4AHQALgBSAGUAZwB1AGwAYQByAEUAeABwAHIAZQBzAHMAaQBvAG4AcwAuAFIAZQBnAGUAeABPAHAAdABpAG8AbgBzAF0AOgA6AEkAZwBuAG8AcgBlAEMAYQBzAGUAKQAKACQAZABlAHAAdABoACAAPQAgADEACgAkAHMAYwBhAG4AIAA9ACAAJABvAHAAZQBuAFQAYQBnAEUAbgBkAAoAJABiAGwAbwBjAGsARQBuAGQAIAA9ACAALQAxAAoACgB3AGgAaQBsAGUAIAAoACQAZABlAHAAdABoACAALQBnAHQAIAAwACkAIAB7AAoAIAAgACAAIAAkAHQAbQAgAD0AIAAkAHQAYQBnAFIAZQBnAGUAeAAuAE0AYQB0AGMAaAAoACQAdABlAHgAdAAsACAAJABzAGMAYQBuACkACgAgACAAIAAgAGkAZgAgACgALQBuAG8AdAAgACQAdABtAC4AUwB1AGMAYwBlAHMAcwApACAAewAKACAAIAAgACAAIAAgACAAIAB0AGgAcgBvAHcAIAAiAEMAbwB1AGwAZAAgAG4AbwB0ACAAZgBpAG4AZAAgAG0AYQB0AGMAaABpAG4AZwAgAGMAbABvAHMAaQBuAGcAIABkAGkAdgAgAGYAbwByACAAdABoAGUAIABoAGUAcgBvACAAbABvAGcAbwAgAGMAYQByAGQALgAiAAoAIAAgACAAIAB9AAoAIAAgACAAIABpAGYAIAAoACQAdABtAC4AVgBhAGwAdQBlAC4AUwB0AGEAcgB0AHMAVwBpAHQAaAAoACIAPAAvACIALAAgAFsAUwB0AHIAaQBuAGcAQwBvAG0AcABhAHIAaQBzAG8AbgBdADoAOgBPAHIAZABpAG4AYQBsACkAKQAgAHsACgAgACAAIAAgACAAIAAgACAAJABkAGUAcAB0AGgALQAtAAoAIAAgACAAIAB9ACAAZQBsAHMAZQAgAHsACgAgACAAIAAgACAAIAAgACAAJABkAGUAcAB0AGgAKwArAAoAIAAgACAAIAB9AAoAIAAgACAAIAAkAHMAYwBhAG4AIAA9ACAAJAB0AG0ALgBJAG4AZABlAHgAIAArACAAJAB0AG0ALgBMAGUAbgBnAHQAaAAKACAAIAAgACAAaQBmACAAKAAkAGQAZQBwAHQAaAAgAC0AZQBxACAAMAApACAAewAKACAAIAAgACAAIAAgACAAIAAkAGIAbABvAGMAawBFAG4AZAAgAD0AIAAkAHMAYwBhAG4ACgAgACAAIAAgACAAIAAgACAAYgByAGUAYQBrAAoAIAAgACAAIAB9AAoAfQAKAAoAaQBmACAAKAAkAGIAbABvAGMAawBFAG4AZAAgAC0AbAB0ACAAMAApACAAewAKACAAIAAgACAAdABoAHIAbwB3ACAAIgBDAG8AdQBsAGQAIABuAG8AdAAgAGQAZQB0AGUAcgBtAGkAbgBlACAAbABvAGcAbwAtAGMAYQByAGQAIABiAGwAbwBjAGsAIABlAG4AZAAuACIACgB9AAoACgAkAGIAbABvAGMAawBMAGUAbgAgAD0AIAAkAGIAbABvAGMAawBFAG4AZAAgAC0AIAAkAGIAbABvAGMAawBTAHQAYQByAHQACgBpAGYAIAAoACQAYgBsAG8AYwBrAEwAZQBuACAALQBnAHQAIAA2ADAAMAAwACkAIAB7AAoAIAAgACAAIAB0AGgAcgBvAHcAIAAiAFMAYQBmAGUAdAB5ACAAcwB0AG8AcAA6ACAAYwBhAG4AZABpAGQAYQB0AGUAIABsAG8AZwBvAC0AYwBhAHIAZAAgAGIAbABvAGMAawAgAGkAcwAgAHUAbgBlAHgAcABlAGMAdABlAGQAbAB5ACAAbABhAHIAZwBlACAAKAAkAGIAbABvAGMAawBMAGUAbgAgAGMAaABhAHIAcwApAC4AIgAKAH0ACgAKACQAYgBsAG8AYwBrACAAPQAgACQAdABlAHgAdAAuAFMAdQBiAHMAdAByAGkAbgBnACgAJABiAGwAbwBjAGsAUwB0AGEAcgB0ACwAIAAkAGIAbABvAGMAawBMAGUAbgApAAoAaQBmACAAKAAtAG4AbwB0ACAAJABiAGwAbwBjAGsALgBDAG8AbgB0AGEAaQBuAHMAKAAkAG4AZQBlAGQAbABlACkAKQAgAHsACgAgACAAIAAgAHQAaAByAG8AdwAgACIAUwBhAGYAZQB0AHkAIABzAHQAbwBwADoAIABjAGEAbgBkAGkAZABhAHQAZQAgAGIAbABvAGMAawAgAGQAbwBlAHMAIABuAG8AdAAgAGMAbwBuAHQAYQBpAG4AIAB0AGgAZQAgAHMAZQBjAG8AbgBkACAAbABvAGcAbwAuACIACgB9AAoAaQBmACAAKAAkAGIAbABvAGMAawAgAC0AbQBhAHQAYwBoACAAJwBXAGgAYQB0AHMAQQBwAHAAfABiAG8AbwBrAGkAbgBnAHwAQgBvAG8AawAgAE4AbwB3AHwAUwBlAG4AZAAgAEIAbwBvAGsAaQBuAGcAfAB0AG8AdQByAC0AYwBhAHIAZAB8AGgAZQByAG8ALQBpAG0AYQBnAGUAJwApACAAewAKACAAIAAgACAAdABoAHIAbwB3ACAAIgBTAGEAZgBlAHQAeQAgAHMAdABvAHAAOgAgAGMAYQBuAGQAaQBkAGEAdABlACAAYgBsAG8AYwBrACAAYwBvAG4AdABhAGkAbgBzACAAaQBtAHAAbwByAHQAYQBuAHQAIABVAEkAIAB0AGUAeAB0ADsAIAByAGUAZgB1AHMAaQBuAGcAIAB0AG8AIAByAGUAbQBvAHYAZQAgAGkAdAAuACIACgB9AAoACgAkAGIAYQBjAGsAdQBwACAAPQAgAEoAbwBpAG4ALQBQAGEAdABoACAAJABlAG4AdgA6AFQARQBNAFAAIAAiAFAAaAB1AFEAdQBvAGMASgBvAGgAbgBzAEMAYQB0AGEAbABvAGcALgBiAGUAZgBvAHIAZQAtAHIAZQBtAG8AdgBlAC0AaABlAHIAbwAtAGwAbwBnAG8ALgB0AHMAeAAiAAoAWwBJAE8ALgBGAGkAbABlAF0AOgA6AFcAcgBpAHQAZQBBAGwAbABUAGUAeAB0ACgAJABiAGEAYwBrAHUAcAAsACAAJAB0AGUAeAB0ACwAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABUAGUAeAB0AC4AVQBUAEYAOABFAG4AYwBvAGQAaQBuAGcAKAAkAGYAYQBsAHMAZQApACkAKQAKAAoAJABuAGUAdwBUAGUAeAB0ACAAPQAgACQAdABlAHgAdAAuAFIAZQBtAG8AdgBlACgAJABiAGwAbwBjAGsAUwB0AGEAcgB0ACwAIAAkAGIAbABvAGMAawBMAGUAbgApAAoACgAjACAAVAByAGkAbQAgAG8AbgBlACAAZQB4AGMAZQBzAHMAaQB2AGUAIABiAGwAYQBuAGsAIABsAGkAbgBlACAAbABlAGYAdAAgAGIAeQAgAHIAZQBtAG8AdgBhAGwALgAKACQAbgBlAHcAVABlAHgAdAAgAD0AIAAkAG4AZQB3AFQAZQB4AHQAIAAtAHIAZQBwAGwAYQBjAGUAIAAnACgAPwBtACkAXgBbACAAXAB0AF0AKwBcAHIAPwBcAG4AKAA/AD0AWwAgAFwAdABdACoAXAByAD8AXABuACkAJwAsACAAJwAnAAoACgAkAGEAZgB0AGUAcgBDAG8AdQBuAHQAIAA9ACAAMAAKACQAcABvAHMAIAA9ACAAMAAKAHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7AAoAIAAgACAAIAAkAGkAIAA9ACAAJABuAGUAdwBUAGUAeAB0AC4ASQBuAGQAZQB4AE8AZgAoACQAbgBlAGUAZABsAGUALAAgACQAcABvAHMALAAgAFsAUwB0AHIAaQBuAGcAQwBvAG0AcABhAHIAaQBzAG8AbgBdADoAOgBPAHIAZABpAG4AYQBsACkACgAgACAAIAAgAGkAZgAgACgAJABpACAALQBsAHQAIAAwACkAIAB7ACAAYgByAGUAYQBrACAAfQAKACAAIAAgACAAJABhAGYAdABlAHIAQwBvAHUAbgB0ACsAKwAKACAAIAAgACAAJABwAG8AcwAgAD0AIAAkAGkAIAArACAAJABuAGUAZQBkAGwAZQAuAEwAZQBuAGcAdABoAAoAfQAKAAoAaQBmACAAKAAkAGEAZgB0AGUAcgBDAG8AdQBuAHQAIAAtAG4AZQAgADEAKQAgAHsACgAgACAAIAAgAHQAaAByAG8AdwAgACIAUwBhAGYAZQB0AHkAIABjAGgAZQBjAGsAIABmAGEAaQBsAGUAZAAgAGEAZgB0AGUAcgAgAGUAZABpAHQAOgAgAGUAeABwAGUAYwB0AGUAZAAgADEAIABsAG8AZwBvACAAbwBjAGMAdQByAHIAZQBuAGMAZQAsACAAZgBvAHUAbgBkACAAJABhAGYAdABlAHIAQwBvAHUAbgB0AC4AIgAKAH0ACgAKAFsASQBPAC4ARgBpAGwAZQBdADoAOgBXAHIAaQB0AGUAQQBsAGwAVABlAHgAdAAoACQAdABhAHIAZwBlAHQALAAgACQAbgBlAHcAVABlAHgAdAAsACAAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAVABlAHgAdAAuAFUAVABGADgARQBuAGMAbwBkAGkAbgBnACgAJABmAGEAbABzAGUAKQApACkACgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsATwBLAF0AIABSAGUAbQBvAHYAZQBkACAATwBOAEwAWQAgAHQAaABlACAAdwBoAGkAdABlACAAbABvAGcAbwAgAGMAYQByAGQAIABvAHYAZQByACAAdABoAGUAIABoAGUAcgBvACAAcABoAG8AdABvAC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAKAAiAEIAYQBjAGsAdQBwADoAIAAiACAAKwAgACQAYgBhAGMAawB1AHAAKQAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABEAGEAcgBrAEcAcgBhAHkA
set "PATCHCODE=%ERRORLEVEL%"

if "%PATCHCODE%"=="10" (
  echo.
  echo [OK] Trang da chi con 1 logo. Khong can sua them.
  pause
  exit /b 0
)
if not "%PATCHCODE%"=="0" (
  echo.
  echo [STOP] Khong sua file vi khong xac dinh duoc dung logo card.
  pause
  exit /b %PATCHCODE%
)

echo.
echo [2/5] Kiem tra diff...
git diff -- "%TARGET%"

echo.
echo [3/5] Production build...
if exist ".next" rmdir /s /q ".next"
call npm run build
if errorlevel 1 (
  echo.
  echo [FAIL] Build loi. Dang khoi phuc file cu...
  if exist "%TEMP%\PhuQuocJohnsCatalog.before-remove-hero-logo.tsx" (
    copy /y "%TEMP%\PhuQuocJohnsCatalog.before-remove-hero-logo.tsx" "%TARGET%" >nul
    echo [OK] Da khoi phuc component cu.
  )
  echo KHONG commit, KHONG push.
  pause
  exit /b 1
)

echo.
echo [4/5] Stage + commit CHI component Phu Quoc...
git reset >nul 2>&1
git add -- "%TARGET%"

for /f %%C in ('git diff --cached --name-only ^| find /c /v ""') do set "COUNT=%%C"
if not "!COUNT!"=="1" (
  echo [STOP] Expected exactly 1 staged file, found !COUNT!.
  git diff --cached --name-status
  git reset
  pause
  exit /b 1
)

for /f "delims=" %%F in ('git diff --cached --name-only') do set "STAGED=%%F"
if /i not "!STAGED!"=="components/PhuQuocJohnsCatalog.tsx" (
  echo [STOP] Unexpected staged file: !STAGED!
  git reset
  pause
  exit /b 1
)

git commit -m "fix: remove duplicate Phu Quoc logo from hero image"
if errorlevel 1 (
  echo [STOP] Commit failed. Nothing pushed.
  pause
  exit /b 1
)

echo.
echo [5/5] Push main...
git push origin main
if errorlevel 1 (
  echo [STOP] Push failed. Commit van nam o may local.
  pause
  exit /b 1
)

echo.
echo ============================================================
echo   SUCCESS
echo ============================================================
echo - Logo tren TAM HINH hero da bo
echo - Logo chinh tren dau trang giu nguyen
echo - Anh Phu Quoc giu nguyen
echo - WhatsApp va noi dung tour giu nguyen
echo.
echo EN: https://www.govietstay.com/tours/phu-quoc
echo RU: https://www.govietstay.com/ru/tours/phu-quoc
echo.
echo Vercel se tu deploy sau khi GitHub nhan commit.
pause
exit /b 0
