@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title GoVietStay - FINAL Remove Hero Logo + Push

set "GIT_PAGER=cat"
set "PAGER=cat"

set "REPO=%USERPROFILE%\Documents\GitHub\govietstay-main-website"
if not exist "%REPO%\package.json" (
  if exist "%USERPROFILE%\OneDrive\Documents\GitHub\govietstay-main-website\package.json" (
    set "REPO=%USERPROFILE%\OneDrive\Documents\GitHub\govietstay-main-website"
  ) else if exist "%CD%\package.json" (
    set "REPO=%CD%"
  ) else (
    echo [STOP] Khong tim thay govietstay-main-website.
    pause
    exit /b 1
  )
)

cd /d "%REPO%"
set "TARGET=components\PhuQuocJohnsCatalog.tsx"

echo.
echo ============================================================
echo   GOVIETSTAY - FINAL REMOVE HERO LOGO
echo   Khong mo pager / khong dung o man hinh diff
echo ============================================================
echo.

for /f "delims=" %%B in ('git branch --show-current') do set "BRANCH=%%B"
if /i not "!BRANCH!"=="main" (
  echo [STOP] Branch hien tai: !BRANCH! - can main.
  pause
  exit /b 1
)

REM Do not interfere with anything already staged
git diff --cached --quiet
if errorlevel 1 (
  echo [STOP] Dang co file STAGED tu truoc. Em khong dong vao de tranh commit nham.
  git status --short
  pause
  exit /b 1
)

echo [1/6] Kiem tra va sua DUNG logo de tren anh hero...
set "GVS_ROOT=%REPO%"
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAiAFMAdABvAHAAIgAKAAoAJAByAG8AbwB0ACAAPQAgACQAZQBuAHYAOgBHAFYAUwBfAFIATwBPAFQACgAkAHQAYQByAGcAZQB0ACAAPQAgAEoAbwBpAG4ALQBQAGEAdABoACAAJAByAG8AbwB0ACAAIgBjAG8AbQBwAG8AbgBlAG4AdABzAFwAUABoAHUAUQB1AG8AYwBKAG8AaABuAHMAQwBhAHQAYQBsAG8AZwAuAHQAcwB4ACIACgAkAGgAZQBhAGQAQwBvAHAAeQAgAD0AIABKAG8AaQBuAC0AUABhAHQAaAAgACQAZQBuAHYAOgBUAEUATQBQACAAIgBnAHYAcwBfAHAAcQBfAGgAZQBhAGQAXwBjAGEAdABhAGwAbwBnAC4AdABzAHgAIgAKAAoAaQBmACAAKAAtAG4AbwB0ACAAKABUAGUAcwB0AC0AUABhAHQAaAAgACQAdABhAHIAZwBlAHQAKQApACAAewAgAHQAaAByAG8AdwAgACIATQBpAHMAcwBpAG4AZwAgAHQAYQByAGcAZQB0ACAAZgBpAGwAZQAuACIAIAB9AAoACgAjACAAUgBlAGEAZAAgAEgARQBBAEQAIAB2AGUAcgBzAGkAbwBuACAAdwBpAHQAaABvAHUAdAAgAHQAbwB1AGMAaABpAG4AZwAgAHQAaABlACAAdwBvAHIAawBpAG4AZwAgAGYAaQBsAGUACgAkAHAAcwBpACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEQAaQBhAGcAbgBvAHMAdABpAGMAcwAuAFAAcgBvAGMAZQBzAHMAUwB0AGEAcgB0AEkAbgBmAG8ACgAkAHAAcwBpAC4ARgBpAGwAZQBOAGEAbQBlACAAPQAgACIAZwBpAHQAIgAKACQAcABzAGkALgBBAHIAZwB1AG0AZQBuAHQAcwAgAD0AIAAiAHMAaABvAHcAIABIAEUAQQBEADoAYwBvAG0AcABvAG4AZQBuAHQAcwAvAFAAaAB1AFEAdQBvAGMASgBvAGgAbgBzAEMAYQB0AGEAbABvAGcALgB0AHMAeAAiAAoAJABwAHMAaQAuAFcAbwByAGsAaQBuAGcARABpAHIAZQBjAHQAbwByAHkAIAA9ACAAJAByAG8AbwB0AAoAJABwAHMAaQAuAFIAZQBkAGkAcgBlAGMAdABTAHQAYQBuAGQAYQByAGQATwB1AHQAcAB1AHQAIAA9ACAAJAB0AHIAdQBlAAoAJABwAHMAaQAuAFIAZQBkAGkAcgBlAGMAdABTAHQAYQBuAGQAYQByAGQARQByAHIAbwByACAAPQAgACQAdAByAHUAZQAKACQAcABzAGkALgBVAHMAZQBTAGgAZQBsAGwARQB4AGUAYwB1AHQAZQAgAD0AIAAkAGYAYQBsAHMAZQAKACQAcABzAGkALgBDAHIAZQBhAHQAZQBOAG8AVwBpAG4AZABvAHcAIAA9ACAAJAB0AHIAdQBlAAoAJABwACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEQAaQBhAGcAbgBvAHMAdABpAGMAcwAuAFAAcgBvAGMAZQBzAHMACgAkAHAALgBTAHQAYQByAHQASQBuAGYAbwAgAD0AIAAkAHAAcwBpAAoAWwB2AG8AaQBkAF0AJABwAC4AUwB0AGEAcgB0ACgAKQAKACQAaABlAGEAZAAgAD0AIAAkAHAALgBTAHQAYQBuAGQAYQByAGQATwB1AHQAcAB1AHQALgBSAGUAYQBkAFQAbwBFAG4AZAAoACkACgAkAGUAcgByACAAPQAgACQAcAAuAFMAdABhAG4AZABhAHIAZABFAHIAcgBvAHIALgBSAGUAYQBkAFQAbwBFAG4AZAAoACkACgAkAHAALgBXAGEAaQB0AEYAbwByAEUAeABpAHQAKAApAAoAaQBmACAAKAAkAHAALgBFAHgAaQB0AEMAbwBkAGUAIAAtAG4AZQAgADAAKQAgAHsAIAB0AGgAcgBvAHcAIAAiAGcAaQB0ACAAcwBoAG8AdwAgAGYAYQBpAGwAZQBkADoAIAAkAGUAcgByACIAIAB9AAoACgAkAGMAdQByAHIAZQBuAHQAIAA9ACAAWwBJAE8ALgBGAGkAbABlAF0AOgA6AFIAZQBhAGQAQQBsAGwAVABlAHgAdAAoACQAdABhAHIAZwBlAHQAKQAKAAoAJABvAHYAZQByAGwAYQB5ACAAPQAgACcAPABkAGkAdgAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgBtAHQALQAyACAAaQBuAGwAaQBuAGUALQBmAGwAZQB4ACAAbQBhAHgALQB3AC0AWwAxADUAMABwAHgAXQAgAG8AdgBlAHIAZgBsAG8AdwAtAGgAaQBkAGQAZQBuACAAcgBvAHUAbgBkAGUAZAAtAHgAbAAgAGIAZwAtAHcAaABpAHQAZQAgAHAALQAxAC4ANQAgAHMAaABhAGQAbwB3AC0AbABnACAAcwBtADoAbQBhAHgALQB3AC0AWwAxADcAMABwAHgAXQAiAD4APABpAG0AZwAgAHMAcgBjAD0AIgAvAGIAcgBhAG4AZAAvAGcAbwB2AGkAZQB0AHMAdABhAHkALQBwAGgAdQAtAHEAdQBvAGMALQBsAG8AZwBvAC4AcABuAGcAIgAgAGEAbAB0AD0AIgBHAG8AVgBpAGUAdABTAHQAYQB5ACAAUABoAHUAIABRAHUAbwBjACIAIABjAGwAYQBzAHMATgBhAG0AZQA9ACIAaAAtAGEAdQB0AG8AIAB3AC0AZgB1AGwAbAAgAG8AYgBqAGUAYwB0AC0AYwBvAG4AdABhAGkAbgAiACAALwA+ADwALwBkAGkAdgA+ACcACgAKAGYAdQBuAGMAdABpAG8AbgAgAE4AbwByAG0AYQBsAGkAegBlACgAWwBzAHQAcgBpAG4AZwBdACQAcwApACAAewAKACAAIAAgACAAcgBlAHQAdQByAG4AIAAoACQAcwAgAC0AcgBlAHAAbABhAGMAZQAgACIAYAByAGAAbgAiACwAIgBgAG4AIgApAAoAfQAKAAoAJABoAGUAYQBkAE4AIAA9ACAATgBvAHIAbQBhAGwAaQB6AGUAIAAkAGgAZQBhAGQACgAkAGMAdQByAHIAZQBuAHQATgAgAD0AIABOAG8AcgBtAGEAbABpAHoAZQAgACQAYwB1AHIAcgBlAG4AdAAKAAoAJABvAHYAZQByAGwAYQB5AEMAbwB1AG4AdAAgAD0AIAAoAFsAcgBlAGcAZQB4AF0AOgA6AE0AYQB0AGMAaABlAHMAKAAkAGgAZQBhAGQATgAsACAAWwByAGUAZwBlAHgAXQA6ADoARQBzAGMAYQBwAGUAKAAkAG8AdgBlAHIAbABhAHkAKQApACkALgBDAG8AdQBuAHQACgBpAGYAIAAoACQAbwB2AGUAcgBsAGEAeQBDAG8AdQBuAHQAIAAtAG4AZQAgADEAKQAgAHsACgAgACAAIAAgAHQAaAByAG8AdwAgACIAUwBhAGYAZQB0AHkAIABzAHQAbwBwADoAIABlAHgAcABlAGMAdABlAGQAIABlAHgAYQBjAHQAbAB5ACAAMQAgAGgAZQByAG8ALQBvAHYAZQByAGwAYQB5ACAAbABvAGcAbwAgAGIAbABvAGMAawAgAGkAbgAgAEgARQBBAEQALAAgAGYAbwB1AG4AZAAgACQAbwB2AGUAcgBsAGEAeQBDAG8AdQBuAHQALgAiAAoAfQAKAAoAJABlAHgAcABlAGMAdABlAGQATgAgAD0AIAAkAGgAZQBhAGQATgAuAFIAZQBwAGwAYQBjAGUAKAAkAG8AdgBlAHIAbABhAHkALAAgACIAIgApAAoACgBpAGYAIAAoACQAYwB1AHIAcgBlAG4AdABOACAALQBlAHEAIAAkAGgAZQBhAGQATgApACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBPAEsAXQAgAFcAbwByAGsAaQBuAGcAIABmAGkAbABlACAAbQBhAHQAYwBoAGUAcwAgAEgARQBBAEQALgAgAEEAcABwAGwAeQBpAG4AZwAgAGUAeABhAGMAdAAgAGgAZQByAG8ALQBsAG8AZwBvACAAcgBlAG0AbwB2AGEAbAAuAC4ALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEMAeQBhAG4ACgAgACAAIAAgACQAbgBlAHcAbABpAG4AZQAgAD0AIABpAGYAIAAoACQAYwB1AHIAcgBlAG4AdAAuAEMAbwBuAHQAYQBpAG4AcwAoACIAYAByAGAAbgAiACkAKQAgAHsAIAAiAGAAcgBgAG4AIgAgAH0AIABlAGwAcwBlACAAewAgACIAYABuACIAIAB9AAoAIAAgACAAIAAkAG8AdQB0ACAAPQAgACQAZQB4AHAAZQBjAHQAZQBkAE4ACgAgACAAIAAgAGkAZgAgACgAJABuAGUAdwBsAGkAbgBlACAALQBlAHEAIAAiAGAAcgBgAG4AIgApACAAewAgACQAbwB1AHQAIAA9ACAAJABvAHUAdAAgAC0AcgBlAHAAbABhAGMAZQAgACIAYABuACIALAAiAGAAcgBgAG4AIgAgAH0ACgAgACAAIAAgAFsASQBPAC4ARgBpAGwAZQBdADoAOgBXAHIAaQB0AGUAQQBsAGwAVABlAHgAdAAoACQAdABhAHIAZwBlAHQALAAgACQAbwB1AHQALAAgACgATgBlAHcALQBPAGIAagBlAGMAdAAgAFQAZQB4AHQALgBVAFQARgA4AEUAbgBjAG8AZABpAG4AZwAoACQAZgBhAGwAcwBlACkAKQApAAoAfQAKAGUAbABzAGUAaQBmACAAKAAkAGMAdQByAHIAZQBuAHQATgAgAC0AZQBxACAAJABlAHgAcABlAGMAdABlAGQATgApACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBPAEsAXQAgAFQAaABlACAAcAByAGUAdgBpAG8AdQBzACAAQgBBAFQAIABhAGwAcgBlAGEAZAB5ACAAcgBlAG0AbwB2AGUAZAAgAHQAaABlACAAaABlAHIAbwAgAGwAbwBnAG8AIABsAG8AYwBhAGwAbAB5AC4AIABXAGkAbABsACAAYgB1AGkAbABkAC8AYwBvAG0AbQBpAHQALwBwAHUAcwBoACAAaQB0ACAAbgBvAHcALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFkAZQBsAGwAbwB3AAoAfQAKAGUAbABzAGUAIAB7AAoAIAAgACAAIAB0AGgAcgBvAHcAIAAiAFMAYQBmAGUAdAB5ACAAcwB0AG8AcAA6ACAAUABoAHUAUQB1AG8AYwBKAG8AaABuAHMAQwBhAHQAYQBsAG8AZwAuAHQAcwB4ACAAaABhAHMAIABvAHQAaABlAHIAIABsAG8AYwBhAGwAIABjAGgAYQBuAGcAZQBzAC4AIABOAG8AIABhAHUAdABvAG0AYQB0AGkAYwAgAG8AdgBlAHIAdwByAGkAdABlAC4AIgAKAH0ACgAKACQAYQBmAHQAZQByACAAPQAgAE4AbwByAG0AYQBsAGkAegBlACAAKABbAEkATwAuAEYAaQBsAGUAXQA6ADoAUgBlAGEAZABBAGwAbABUAGUAeAB0ACgAJAB0AGEAcgBnAGUAdAApACkACgAkAGwAbwBnAG8AQwBvAHUAbgB0ACAAPQAgACgAWwByAGUAZwBlAHgAXQA6ADoATQBhAHQAYwBoAGUAcwAoACQAYQBmAHQAZQByACwAIABbAHIAZQBnAGUAeABdADoAOgBFAHMAYwBhAHAAZQAoACcALwBiAHIAYQBuAGQALwBnAG8AdgBpAGUAdABzAHQAYQB5AC0AcABoAHUALQBxAHUAbwBjAC0AbABvAGcAbwAuAHAAbgBnACcAKQApACkALgBDAG8AdQBuAHQACgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAoACIAUABoAHUAIABRAHUAbwBjACAAbABvAGcAbwAgAG8AYwBjAHUAcgByAGUAbgBjAGUAcwAgAGEAZgB0AGUAcgAgAGUAZABpAHQAOgAgACIAIAArACAAJABsAG8AZwBvAEMAbwB1AG4AdAApAAoAaQBmACAAKAAkAGwAbwBnAG8AQwBvAHUAbgB0ACAALQBuAGUAIAAxACkAIAB7AAoAIAAgACAAIAB0AGgAcgBvAHcAIAAiAFMAYQBmAGUAdAB5ACAAcwB0AG8AcAA6ACAAZQB4AHAAZQBjAHQAZQBkACAAZQB4AGEAYwB0AGwAeQAgADEAIABsAG8AZwBvACAAYQBmAHQAZQByACAAZQBkAGkAdAAsACAAZgBvAHUAbgBkACAAJABsAG8AZwBvAEMAbwB1AG4AdAAuACIACgB9AAoACgBpAGYAIAAoACQAYQBmAHQAZQByAC4AQwBvAG4AdABhAGkAbgBzACgAJABvAHYAZQByAGwAYQB5ACkAKQAgAHsACgAgACAAIAAgAHQAaAByAG8AdwAgACIAUwBhAGYAZQB0AHkAIABzAHQAbwBwADoAIABoAGUAcgBvACAAbwB2AGUAcgBsAGEAeQAgAGIAbABvAGMAawAgAHMAdABpAGwAbAAgAGUAeABpAHMAdABzAC4AIgAKAH0ACgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsATwBLAF0AIABFAHgAYQBjAHQAIABkAHUAcABsAGkAYwBhAHQAZQAgAGgAZQByAG8ALQBpAG0AYQBnAGUAIABsAG8AZwBvACAAcgBlAG0AbwB2AGUAZAAuACAATQBhAGkAbgAgAHQAbwBwACAAbABvAGcAbwAgAHIAZQBtAGEAaQBuAHMALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgA=
if errorlevel 1 (
  echo.
  echo [STOP] Patch khong an toan. KHONG commit / KHONG push.
  pause
  exit /b 1
)

echo.
echo [2/6] Thay doi:
git --no-pager diff --stat -- "%TARGET%"
git --no-pager diff --unified=0 -- "%TARGET%"

echo.
echo [3/6] Build production...
if exist ".next" rmdir /s /q ".next"
call npm run build
if errorlevel 1 (
  echo.
  echo [FAIL] BUILD FAIL - KHONG commit, KHONG push.
  pause
  exit /b 1
)
echo [OK] BUILD PASS.

echo.
echo [4/6] Stage CHI component Phu Quoc...
git add -- "%TARGET%"

for /f %%C in ('git diff --cached --name-only ^| find /c /v ""') do set "COUNT=%%C"
if not "!COUNT!"=="1" (
  echo [STOP] Expected exactly 1 staged file, found !COUNT!.
  git --no-pager diff --cached --name-status
  git reset
  pause
  exit /b 1
)

for /f "delims=" %%F in ('git diff --cached --name-only') do set "STAGED=%%F"
if /i not "!STAGED!"=="components/PhuQuocJohnsCatalog.tsx" (
  echo [STOP] Unexpected staged file: !STAGED!
  git reset
  pause
  exit /b 1
)

echo.
echo [5/6] Commit...
git commit -m "fix: remove duplicate Phu Quoc logo from hero image"
if errorlevel 1 (
  echo [STOP] Commit failed. KHONG push.
  pause
  exit /b 1
)

echo.
echo [6/6] Push origin main...
git push origin main
if errorlevel 1 (
  echo [STOP] Push failed. Commit van nam tren may.
  pause
  exit /b 1
)

echo.
echo ============================================================
echo   SUCCESS - DA PUSH LEN GITHUB
echo ============================================================
git --no-pager log -1 --oneline
echo.
echo Vercel se auto-deploy commit tren.
echo Live:
echo https://www.govietstay.com/ru/tours/phu-quoc
echo https://www.govietstay.com/tours/phu-quoc
echo.
echo Neu mo trang cu, bam Ctrl+F5 de bo cache.
pause
