@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title GoVietStay - Operations V3 Deposit Hotel Delete

echo.
echo ================================================================
echo  GOVIETSTAY OPERATIONS V3 - PAYMENT + HOTEL ADDRESS + DELETE
echo ================================================================
echo.
echo  V3 adds:
echo  - Show Deposit and Balance on booking cards
echo  - Hotel name + separate hotel address
echo  - Hotel address included in Customer and Driver copy
echo  - Owner/Admin can delete test bookings
echo  - Sales/Desk can delete ONLY their own Pending draft with zero deposit
echo.

set "PROJECT="
for /f "delims=" %%I in ('git rev-parse --show-toplevel 2^>nul') do set "PROJECT=%%I"
if not defined PROJECT if exist "%USERPROFILE%\Documents\GitHub\govietstay-main-website\.git" set "PROJECT=%USERPROFILE%\Documents\GitHub\govietstay-main-website"
if not defined PROJECT if exist "%USERPROFILE%\govietstay-main-website\.git" set "PROJECT=%USERPROFILE%\govietstay-main-website"
if not defined PROJECT if exist "%USERPROFILE%\Desktop\govietstay-main-website\.git" set "PROJECT=%USERPROFILE%\Desktop\govietstay-main-website"

if not defined PROJECT (
  echo Khong tu tim thay thu muc project.
  set /p "PROJECT=Dan duong dan thu muc govietstay-main-website roi Enter: "
)
if not exist "%PROJECT%\.git" (
  echo [STOP] Khong tim thay Git project: %PROJECT%
  pause
  exit /b 1
)

set "WORKTREE=%TEMP%\gvs_ops_v3_%RANDOM%_%RANDOM%"
set "GVS_WORKTREE=%WORKTREE%"

echo [1/7] Fetch origin/main...
git -C "%PROJECT%" fetch origin main
if errorlevel 1 goto FAIL

echo [2/7] Tao worktree sach...
git -C "%PROJECT%" worktree add --detach "%WORKTREE%" origin/main
if errorlevel 1 goto FAIL

echo [3/7] Patch Operations V3...
set "PATCH_B64=%TEMP%\gvs_ops_v3_%RANDOM%_%RANDOM%.b64"
set "PATCH_PS1=%TEMP%\gvs_ops_v3_%RANDOM%_%RANDOM%.ps1"
> "%PATCH_B64%" (
  echo 77u/JEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICJTdG9wIgokcm9vdCA9ICRlbnY6R1ZTX1dPUktUUkVFCmlmICgtbm90ICRyb290KSB7IHRocm93ICJHVlNfV09SS1RSRUUgaXMgbm90IHNldC4iIH0KJHBhdGggPSBKb2luLVBhdGggJHJvb3QgImNvbXBvbmVudHNcYWRtaW4tdjVcT3BlcmF0aW9uc0NlbnRlci50c3giCmlmICgtbm90IChUZXN0LVBhdGggJHBhdGgpKSB7IHRocm93ICJDYW5ub3QgZmluZCBPcGVyYXRpb25zQ2VudGVyLnRzeCBhdCAkcGF0aCIgfQoKJHV0ZjggPSBOZXctT2JqZWN0IFN5c3RlbS5UZXh0LlVURjhFbmNvZGluZygkZmFsc2UpCiR0ZXh0ID0gW0lPLkZpbGVdOjpSZWFkQWxsVGV4dCgkcGF0aCwgJHV0ZjgpLlJlcGxhY2UoImByYG4iLCAiYG4iKQoKaWYgKCR0ZXh0LkNvbnRhaW5zKCIvLyBHVlMtQk9PS0lORy1QQVlNRU5ULUhPVEVMLURFTEVURS1WMyIpKSB7CiAgV3JpdGUtSG9zdCAiW09LXSBWMyBhbHJlYWR5IGluc3RhbGxlZC4iIC1Gb3JlZ3JvdW5kQ29sb3IgR3JlZW4KICBleGl0IDAKfQoKZnVuY3Rpb24gUmVwbGFjZS1FeGFjdChbc3RyaW5nXSRvbGQsIFtzdHJpbmddJG5ldywgW3N0cmluZ10kbGFiZWwpIHsKICBpZiAoLW5vdCAkc2NyaXB0OnRleHQuQ29udGFpbnMoJG9sZCkpIHsKICAgIHRocm93ICJQYXRjaCBwb2ludCBub3QgZm91bmQ6ICRsYWJlbC4gU291cmNlIGNoYW5nZWQ7IG5vdGhpbmcgd2FzIHdyaXR0ZW4uIgogIH0KICAkc2NyaXB0OnRleHQgPSAkc2NyaXB0OnRleHQuUmVwbGFjZSgkb2xkLCAkbmV3KQogIFdyaXRlLUhvc3QgIltQQVRDSF0gJGxhYmVsIiAtRm9yZWdyb3VuZENvbG9yIEN5YW4KfQoKUmVwbGFjZS1FeGFjdCBAJwovLyBHVlMtQk9PS0lORy1ERVBPU0lULVNIQVJFLVYxCidAIEAnCi8vIEdWUy1CT09LSU5HLURFUE9TSVQtU0hBUkUtVjEKLy8gR1ZTLUJPT0tJTkctUEFZTUVOVC1IT1RFTC1ERUxFVEUtVjMKJ0AgInZlcnNpb24gbWFya2VyIgoKUmVwbGFjZS1FeGFjdCBAJwogIHRvdXJfaWQ6IHN0cmluZyB8IG51bGw7CiAgdG91cl9kYXRlOiBzdHJpbmcgfCBudWxsOwonQCBAJwogIHRvdXJfaWQ6IHN0cmluZyB8IG51bGw7CiAgc3RhZmZfaWQ6IHN0cmluZyB8IG51bGw7CiAgdG91cl9kYXRlOiBzdHJpbmcgfCBudWxsOwonQCAiYm9va2luZyBzdGFmZiBpZCIKClJlcGxhY2UtRXhhY3QgQCcKICBob3RlbDogc3RyaW5nIHwgbnVsbDsKICByb29tOiBzdHJpbmcgfCBudWxsOwonQCBAJwogIGhvdGVsOiBzdHJpbmcgfCBudWxsOwogIGhvdGVsX2FkZHJlc3M6IHN0cmluZyB8IG51bGw7CiAgcm9vbTogc3RyaW5nIHwgbnVsbDsKJ0AgImhvdGVsIGFkZHJlc3MgdHlwZSIKClJlcGxhY2UtRXhhY3QgQCcKLnNlbGVjdCgiaWQsYm9va2luZ19jb2RlLGNvbnRhY3RfaWQsdG91cl9pZCx0b3VyX2RhdGUsYWR1bHRzLGNoaWxkcmVuLHBheCxncm9zc19yZXZlbnVlX3ZuZCxuZXRfcmV2ZW51ZV92bmQsZGVwb3NpdF9yZXF1aXJlZF92bmQsc3RhdHVzLHBheW1lbnRfc3RhdHVzLHBpY2t1cF90aW1lLHN0YXJ0X3RpbWUsZW5kX3RpbWUsaG90ZWwscm9vbSxub3RlcyxndWlkZV9sYW5ndWFnZSxib29raW5nX21vZGUsY3VzdG9tX3RvdXJfbmFtZSxjdXN0b21fZGVzdGluYXRpb24sY3VzdG9tX2l0aW5lcmFyeSxjcmVhdGVkX2F0IikKJ0AgQCcKLnNlbGVjdCgiaWQsYm9va2luZ19jb2RlLGNvbnRhY3RfaWQsdG91cl9pZCxzdGFmZl9pZCx0b3VyX2RhdGUsYWR1bHRzLGNoaWxkcmVuLHBheCxncm9zc19yZXZlbnVlX3ZuZCxuZXRfcmV2ZW51ZV92bmQsZGVwb3NpdF9yZXF1aXJlZF92bmQsc3RhdHVzLHBheW1lbnRfc3RhdHVzLHBpY2t1cF90aW1lLHN0YXJ0X3RpbWUsZW5kX3RpbWUsaG90ZWwsaG90ZWxfYWRkcmVzcyxyb29tLG5vdGVzLGd1aWRlX2xhbmd1YWdlLGJvb2tpbmdfbW9kZSxjdXN0b21fdG91cl9uYW1lLGN1c3RvbV9kZXN0aW5hdGlvbixjdXN0b21faXRpbmVyYXJ5LGNyZWF0ZWRfYXQiKQonQCAibG9hZCBzdGFmZiBpZCBhbmQgaG90ZWwgYWRkcmVzcyIKClJlcGxhY2UtRXhhY3QgQCcKICAgICAgYNCS0LfRgNC+0YHQu9GL0LU6ICR7Yi5hZHVsdHN9IMK3INCU0LXRgtC4OiAke2IuY2hpbGRyZW59YCwKICAgICAgYNCc0LXRgdGC0L4g0LLRgdGC0YDQtdGH0Lg6ICR7Yi5ob3RlbCB8fCAi4oCUIn1gLAogICAgICBg0JLRgNC10LzRjyDQstGB0YLRgNC10YfQuDogJHtwaWNrdXBUaW1lfWAsCiAgICAgIGDQr9C30YvQuiDQs9C40LTQsDogJHtsYW5nTGFiZWwoYi5ndWlkZV9sYW5ndWFnZSl9YCwKJ0Ag
  echo QCcKICAgICAgYNCS0LfRgNC+0YHQu9GL0LU6ICR7Yi5hZHVsdHN9IMK3INCU0LXRgtC4OiAke2IuY2hpbGRyZW59YCwKICAgICAgYNCc0LXRgdGC0L4g0LLRgdGC0YDQtdGH0Lg6ICR7Yi5ob3RlbCB8fCAi4oCUIn1gLAogICAgICBiLmhvdGVsX2FkZHJlc3MgPyBg0JDQtNGA0LXRgSDQvtGC0LXQu9GPOiAke2IuaG90ZWxfYWRkcmVzc31gIDogIiIsCiAgICAgIGDQktGA0LXQvNGPINCy0YHRgtGA0LXRh9C4OiAke3BpY2t1cFRpbWV9YCwKICAgICAgYNCv0LfRi9C6INCz0LjQtNCwOiAke2xhbmdMYWJlbChiLmd1aWRlX2xhbmd1YWdlKX1gLAonQCAiY3VzdG9tZXIgUlUgaG90ZWwgYWRkcmVzcyIKClJlcGxhY2UtRXhhY3QgQCcKICAgICAgYEFkdWx0czogJHtiLmFkdWx0c30gwrcgQ2hpbGRyZW46ICR7Yi5jaGlsZHJlbn1gLAogICAgICBgUGlja3VwOiAke2IuaG90ZWwgfHwgIuKAlCJ9YCwKICAgICAgYFBpY2t1cCB0aW1lOiAke3BpY2t1cFRpbWV9YCwKICAgICAgYEd1aWRlIGxhbmd1YWdlOiAke2xhbmdMYWJlbChiLmd1aWRlX2xhbmd1YWdlKX1gLAonQCBAJwogICAgICBgQWR1bHRzOiAke2IuYWR1bHRzfSDCtyBDaGlsZHJlbjogJHtiLmNoaWxkcmVufWAsCiAgICAgIGBQaWNrdXA6ICR7Yi5ob3RlbCB8fCAi4oCUIn1gLAogICAgICBiLmhvdGVsX2FkZHJlc3MgPyBgUGlja3VwIGFkZHJlc3M6ICR7Yi5ob3RlbF9hZGRyZXNzfWAgOiAiIiwKICAgICAgYFBpY2t1cCB0aW1lOiAke3BpY2t1cFRpbWV9YCwKICAgICAgYEd1aWRlIGxhbmd1YWdlOiAke2xhbmdMYWJlbChiLmd1aWRlX2xhbmd1YWdlKX1gLAonQCAiY3VzdG9tZXIgRU4gaG90ZWwgYWRkcmVzcyIKClJlcGxhY2UtRXhhY3QgQCcKICAgICAgYMSQaeG7h24gdGhv4bqhaTogJHtjb250YWN0Py53aGF0c2FwcCB8fCAi4oCUIn1gLAogICAgICBgxJBp4buDbSDEkcOzbjogJHtiLmhvdGVsIHx8ICLigJQifWAsCiAgICAgIGBHaeG7nSDEkcOzbjogJHtwaWNrdXBUaW1lfWAsCiAgICAgIGBUb3VyOiAke2Jvb2tpbmdOYW1lKGIpfWAsCidAIEAnCiAgICAgIGDEkGnhu4duIHRob+G6oWk6ICR7Y29udGFjdD8ud2hhdHNhcHAgfHwgIuKAlCJ9YCwKICAgICAgYMSQaeG7g20gxJHDs246ICR7Yi5ob3RlbCB8fCAi4oCUIn1gLAogICAgICBiLmhvdGVsX2FkZHJlc3MgPyBgxJDhu4thIGNo4buJOiAke2IuaG90ZWxfYWRkcmVzc31gIDogIiIsCiAgICAgIGBHaeG7nSDEkcOzbjogJHtwaWNrdXBUaW1lfWAsCiAgICAgIGBUb3VyOiAke2Jvb2tpbmdOYW1lKGIpfWAsCidAICJkcml2ZXIgVkkgaG90ZWwgYWRkcmVzcyIKClJlcGxhY2UtRXhhY3QgQCcKICAgICAgYFBob25lIC8gV2hhdHNBcHA6ICR7Y29udGFjdD8ud2hhdHNhcHAgfHwgIuKAlCJ9YCwKICAgICAgYFBpY2t1cDogJHtiLmhvdGVsIHx8ICLigJQifWAsCiAgICAgIGBQaWNrdXAgdGltZTogJHtwaWNrdXBUaW1lfWAsCiAgICAgIGBUb3VyOiAke2Jvb2tpbmdOYW1lKGIpfWAsCidAIEAnCiAgICAgIGBQaG9uZSAvIFdoYXRzQXBwOiAke2NvbnRhY3Q/LndoYXRzYXBwIHx8ICLigJQifWAsCiAgICAgIGBQaWNrdXA6ICR7Yi5ob3RlbCB8fCAi4oCUIn1gLAogICAgICBiLmhvdGVsX2FkZHJlc3MgPyBgUGlja3VwIGFkZHJlc3M6ICR7Yi5ob3RlbF9hZGRyZXNzfWAgOiAiIiwKICAgICAgYFBpY2t1cCB0aW1lOiAke3BpY2t1cFRpbWV9YCwKICAgICAgYFRvdXI6ICR7Ym9va2luZ05hbWUoYil9YCwKJ0AgImRyaXZlciBFTiBob3RlbCBhZGRyZXNzIgoKUmVwbGFjZS1FeGFjdCBAJwogICAgICAgIGhvdGVsOiBTdHJpbmcodi5ob3RlbCB8fCAiIikudHJpbSgpIHx8IG51bGwsCiAgICAgICAgbm90ZXM6IFN0cmluZyh2Lm5vdGVzIHx8ICIiKS50cmltKCkgfHwgbnVsbCwKJ0AgQCcKICAgICAgICBob3RlbDogU3RyaW5nKHYuaG90ZWwgfHwgIiIpLnRyaW0oKSB8fCBudWxsLAogICAgICAgIGhvdGVsX2FkZHJlc3M6IFN0cmluZyh2LmhvdGVsX2FkZHJlc3MgfHwgIiIpLnRyaW0oKSB8fCBudWxsLAogICAgICAgIG5vdGVzOiBTdHJpbmcodi5ub3RlcyB8fCAiIikudHJpbSgpIHx8IG51bGwsCidAICJzYXZlIGhvdGVsIGFkZHJlc3MiCgpSZXBsYWNlLUV4YWN0IEAnCiAgYXN5bmMgZnVuY3Rpb24gZGVsZXRlQ29zdChpZDogc3RyaW5nKSB7CidAIEAnCiAgZnVuY3Rpb24gY2FuRGVsZXRlQm9va2luZyhiOiBCb29raW5nKSB7CiAgICBpZiAoaXNBZG1pbikgcmV0dXJuIHRydWU7CiAgICByZXR1cm4gISFzdGFmZiAmJiBbInNhbGVzIiwgImRlc2siXS5pbmNsdWRlcyhz
  echo dGFmZi5yb2xlKSAmJiBiLnN0YWZmX2lkID09PSBzdGFmZi5pZCAmJiBiLnN0YXR1cyA9PT0gInBlbmRpbmciICYmIGJvb2tpbmdEZXBvc2l0KGIpID09PSAwICYmIGIucGF5bWVudF9zdGF0dXMgPT09ICJ1bnBhaWQiOwogIH0KCiAgYXN5bmMgZnVuY3Rpb24gZGVsZXRlQm9va2luZyhiOiBCb29raW5nKSB7CiAgICBpZiAoIWNhbkRlbGV0ZUJvb2tpbmcoYikpIHsKICAgICAgc2V0RXJyb3IoIk5ow6JuIHZpw6puIGNo4buJIGPDsyB0aOG7gyB4w7NhIGJvb2tpbmcgUGVuZGluZyBkbyBjaMOtbmggbcOsbmggdOG6oW8gdsOgIGNoxrBhIGPDsyB0aeG7gW4gY+G7jWMuIik7CiAgICAgIHJldHVybjsKICAgIH0KICAgIGNvbnN0IGxhYmVsID0gYCR7Yi5ib29raW5nX2NvZGUgfHwgIkJvb2tpbmcifSDCtyAke2Jvb2tpbmdOYW1lKGIpfWA7CiAgICBjb25zdCBxdWVzdGlvbiA9IGlzQWRtaW4KICAgICAgPyBgWMOzYSB2xKluaCB2aeG7hW4gYm9va2luZyBuw6B5P1xuXG4ke2xhYmVsfVxuXG5Dw6FjIGThu68gbGnhu4d1IEhEViAvIGNoaSBwaMOtIC8gcGF5bWVudCBsacOqbiBxdWFuIGPFqW5nIHPhur0gxJHGsOG7o2MgeMOzYS5gCiAgICAgIDogYFjDs2EgYm9va2luZyBuaMOhcCBuw6B5P1xuXG4ke2xhYmVsfWA7CiAgICBpZiAoIXdpbmRvdy5jb25maXJtKHF1ZXN0aW9uKSkgcmV0dXJuOwogICAgc2V0U2F2aW5nKHRydWUpOyBzZXRFcnJvcigiIik7CiAgICB0cnkgewogICAgICBjb25zdCB7IGVycm9yOiBkZWxldGVFcnJvciB9ID0gYXdhaXQgc3VwYWJhc2UuZnJvbSgiYm9va2luZ3MiKS5kZWxldGUoKS5lcSgiaWQiLCBiLmlkKTsKICAgICAgaWYgKGRlbGV0ZUVycm9yKSB0aHJvdyBkZWxldGVFcnJvcjsKICAgICAgc2V0TWVzc2FnZShgxJDDoyB4w7NhICR7Yi5ib29raW5nX2NvZGUgfHwgImJvb2tpbmcifS5gKTsKICAgICAgYXdhaXQgbG9hZEFsbCgpOwogICAgfSBjYXRjaCAoZTogYW55KSB7IHNldEVycm9yKGUubWVzc2FnZSk7IH0gZmluYWxseSB7IHNldFNhdmluZyhmYWxzZSk7IH0KICB9CgogIGFzeW5jIGZ1bmN0aW9uIGRlbGV0ZUNvc3QoaWQ6IHN0cmluZykgewonQCAic2FmZSBib29raW5nIGRlbGV0ZSIKClJlcGxhY2UtRXhhY3QgQCcKICAgICAgICAgICAgICAgICAgICAgICAge2lzQWRtaW4gPyA8c21hbGw+VGh1IHttb25leShyZXZlbnVlKX0gwrcgQ2hpIHttb25leShjb3N0KX0gwrcgTMOjaSB7bW9uZXkocmV2ZW51ZSAtIGNvc3QpfTwvc21hbGw+IDogPHNtYWxsPkPhu41jIHttb25leShib29raW5nRGVwb3NpdChiKSl9IMK3IEPDsm4gbOG6oWkge21vbmV5KGJvb2tpbmdCYWxhbmNlKGIpKX08L3NtYWxsPn0KJ0AgQCcKICAgICAgICAgICAgICAgICAgICAgICAge2lzQWRtaW4gPyA8PjxzbWFsbD5UaHUge21vbmV5KHJldmVudWUpfSDCtyBDaGkge21vbmV5KGNvc3QpfSDCtyBMw6NpIHttb25leShyZXZlbnVlIC0gY29zdCl9PC9zbWFsbD48c21hbGw+Q+G7jWMge21vbmV5KGJvb2tpbmdEZXBvc2l0KGIpKX0gwrcgQ8OybiBs4bqhaSB7bW9uZXkoYm9va2luZ0JhbGFuY2UoYikpfTwvc21hbGw+PC8+IDogPHNtYWxsPkPhu41jIHttb25leShib29raW5nRGVwb3NpdChiKSl9IMK3IEPDsm4gbOG6oWkge21vbmV5KGJvb2tpbmdCYWxhbmNlKGIpKX08L3NtYWxsPn0KJ0AgInNob3cgZGVwb3NpdCBvbiBtb2JpbGUgY2FyZHMiCgpSZXBsYWNlLUV4YWN0IEAnCiAgICAgICAgICAgICAgICAgICAgICB7aXNBZG1pbiAmJiA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgY2xhc3NOYW1lPSJmaW5hbmNlIiBvbkNsaWNrPXsoKSA9PiB7IHNldFNlbGVjdGVkQm9va2luZyhiLmlkKTsgc2V0TW9kYWwoImNvc3QiKTsgfX0+VMOgaSBjaMOtbmg8L2J1dHRvbj59CidAIEAnCiAgICAgICAgICAgICAgICAgICAgICB7aXNBZG1pbiAmJiA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgY2xhc3NOYW1lPSJmaW5hbmNlIiBvbkNsaWNrPXsoKSA9PiB7IHNldFNlbGVjdGVkQm9va2luZyhiLmlkKTsgc2V0TW9kYWwoImNvc3QiKTsgfX0+VMOgaSBjaMOtbmg8L2J1dHRvbj59CiAgICAgICAgICAgICAgICAgICAgICB7Y2FuRGVsZXRlQm9va2luZyhiKSAmJiA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgb25DbGljaz17KCkgPT4gZGVsZXRlQm9va2luZyhiKX0gZGlzYWJsZWQ9e3NhdmluZ30gc3R5bGU9e3sgY29sb3I6ICIjYjQyMzE4IiB9fT57aXNBZG1pbiA/ICJYw7NhIiA6ICJYw7NhIG5ow6FwIn08L2J1dHRvbj59CidAICJtb2JpbGUgZGVsZXRlIGJ1dHRvbiIKClJlcGxhY2UtRXhh
  echo Y3QgQCcKICAgICAgICAgICAgICAgICAgPHNwYW4+8J+PqCB7Yi5ob3RlbCB8fCAi4oCUIn08L3NwYW4+CidAIEAnCiAgICAgICAgICAgICAgICAgIDxzcGFuPvCfj6gge2IuaG90ZWwgfHwgIuKAlCJ9PC9zcGFuPgogICAgICAgICAgICAgICAgICB7Yi5ob3RlbF9hZGRyZXNzICYmIDxzcGFuPvCfk40ge2IuaG90ZWxfYWRkcmVzc308L3NwYW4+fQonQCAic2hvdyBob3RlbCBhZGRyZXNzIG9uIGJvb2tpbmcgY2FyZCIKClJlcGxhY2UtRXhhY3QgQCcKICAgICAgICAgICAgICAgIHtpc0FkbWluID8gPGRpdiBjbGFzc05hbWU9Imd2by1maW5hbmNlLXJvdyI+CiAgICAgICAgICAgICAgICAgIDxzcGFuPlRodTogPGI+e21vbmV5KHJldmVudWUpfTwvYj48L3NwYW4+PHNwYW4+Q2hpOiA8Yj57bW9uZXkoY29zdCl9PC9iPjwvc3Bhbj48c3Bhbj5Mw6NpIGfhu5lwOiA8Yj57bW9uZXkocmV2ZW51ZSAtIGNvc3QpfTwvYj48L3NwYW4+CiAgICAgICAgICAgICAgICAgIDxidXR0b24gY2xhc3NOYW1lPSJndm8tdGV4dC1idG4iIG9uQ2xpY2s9eygpID0+IHsgc2V0U2VsZWN0ZWRCb29raW5nKGIuaWQpOyBzZXRNb2RhbCgiY29zdCIpOyB9fT5RdeG6o24gbMO9IGNoaSBwaMOtPC9idXR0b24+CiAgICAgICAgICAgICAgICA8L2Rpdj4gOiA8ZGl2IGNsYXNzTmFtZT0iZ3ZvLWZpbmFuY2Utcm93Ij4KICAgICAgICAgICAgICAgICAgPHNwYW4+VOG7lW5nOiA8Yj57bW9uZXkocmV2ZW51ZSl9PC9iPjwvc3Bhbj48c3Bhbj5D4buNYzogPGI+e21vbmV5KGJvb2tpbmdEZXBvc2l0KGIpKX08L2I+PC9zcGFuPjxzcGFuPkPDsm4gbOG6oWk6IDxiPnttb25leShib29raW5nQmFsYW5jZShiKSl9PC9iPjwvc3Bhbj4KICAgICAgICAgICAgICAgIDwvZGl2Pn0KICAgICAgICAgICAgICAgIHtzaGFyZUJ1dHRvbnMoYil9CidAIEAnCiAgICAgICAgICAgICAgICB7aXNBZG1pbiA/IDw+CiAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJndm8tZmluYW5jZS1yb3ciPgogICAgICAgICAgICAgICAgICAgIDxzcGFuPlRodTogPGI+e21vbmV5KHJldmVudWUpfTwvYj48L3NwYW4+PHNwYW4+Q2hpOiA8Yj57bW9uZXkoY29zdCl9PC9iPjwvc3Bhbj48c3Bhbj5Mw6NpIGfhu5lwOiA8Yj57bW9uZXkocmV2ZW51ZSAtIGNvc3QpfTwvYj48L3NwYW4+CiAgICAgICAgICAgICAgICAgICAgPGJ1dHRvbiBjbGFzc05hbWU9Imd2by10ZXh0LWJ0biIgb25DbGljaz17KCkgPT4geyBzZXRTZWxlY3RlZEJvb2tpbmcoYi5pZCk7IHNldE1vZGFsKCJjb3N0Iik7IH19PlF14bqjbiBsw70gY2hpIHBow608L2J1dHRvbj4KICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJndm8tZmluYW5jZS1yb3ciPgogICAgICAgICAgICAgICAgICAgIDxzcGFuPvCfkrUgQ+G7jWM6IDxiPnttb25leShib29raW5nRGVwb3NpdChiKSl9PC9iPjwvc3Bhbj48c3Bhbj5Dw7JuIGzhuqFpOiA8Yj57bW9uZXkoYm9va2luZ0JhbGFuY2UoYikpfTwvYj48L3NwYW4+CiAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgPC8+IDogPGRpdiBjbGFzc05hbWU9Imd2by1maW5hbmNlLXJvdyI+CiAgICAgICAgICAgICAgICAgIDxzcGFuPlThu5VuZzogPGI+e21vbmV5KHJldmVudWUpfTwvYj48L3NwYW4+PHNwYW4+Q+G7jWM6IDxiPnttb25leShib29raW5nRGVwb3NpdChiKSl9PC9iPjwvc3Bhbj48c3Bhbj5Dw7JuIGzhuqFpOiA8Yj57bW9uZXkoYm9va2luZ0JhbGFuY2UoYikpfTwvYj48L3NwYW4+CiAgICAgICAgICAgICAgICA8L2Rpdj59CiAgICAgICAgICAgICAgICB7c2hhcmVCdXR0b25zKGIpfQogICAgICAgICAgICAgICAge2NhbkRlbGV0ZUJvb2tpbmcoYikgJiYgPGRpdiBzdHlsZT17eyBtYXJnaW5Ub3A6IDgsIHRleHRBbGlnbjogInJpZ2h0IiB9fT4KICAgICAgICAgICAgICAgICAgPGJ1dHRvbiB0eXBlPSJidXR0b24iIGRpc2FibGVkPXtzYXZpbmd9IG9uQ2xpY2s9eygpID0+IGRlbGV0ZUJvb2tpbmcoYil9IHN0eWxlPXt7IGJvcmRlcjogMCwgYmFja2dyb3VuZDogInRyYW5zcGFyZW50IiwgY29sb3I6ICIjYjQyMzE4IiwgZm9udFdlaWdodDogNzAwLCBjdXJzb3I6ICJwb2ludGVyIiB9fT57aXNBZG1pbiA/ICLwn5eRIFjDs2EgYm9va2luZyIgOiAi8J+XkSBYw7NhIGJvb2tpbmcgbmjDoXAifTwvYnV0dG9uPgogICAgICAgICAgICAgICAgPC9kaXY+fQonQCAiZGVwb3NpdCByb3cgYW5kIGRlbGV0ZSBvbiBkYXkgY2FyZCIKClJlcGxhY2UtRXhh
  echo Y3QgQCcKICAgIDxGaWVsZCBsYWJlbD0iVHLhuqFuZyB0aMOhaSI+PHNlbGVjdCBuYW1lPSJzdGF0dXMiIGNsYXNzTmFtZT0iZ3ZhLXNlbGVjdCI+PG9wdGlvbiB2YWx1ZT0iY29uZmlybWVkIj5jb25maXJtZWQ8L29wdGlvbj48b3B0aW9uIHZhbHVlPSJwZW5kaW5nIj5wZW5kaW5nPC9vcHRpb24+PC9zZWxlY3Q+PC9GaWVsZD4KJ0AgQCcKICAgIDxGaWVsZCBsYWJlbD0iVHLhuqFuZyB0aMOhaSI+PHNlbGVjdCBuYW1lPSJzdGF0dXMiIGNsYXNzTmFtZT0iZ3ZhLXNlbGVjdCI+PG9wdGlvbiB2YWx1ZT0iY29uZmlybWVkIj5jb25maXJtZWQ8L29wdGlvbj48b3B0aW9uIHZhbHVlPSJwZW5kaW5nIj5wZW5kaW5nIC8gbmjDoXA8L29wdGlvbj48L3NlbGVjdD48L0ZpZWxkPgonQCAiY2xlYXIgcGVuZGluZyBkcmFmdCBsYWJlbCIKClJlcGxhY2UtRXhhY3QgQCcKICAgIDxGaWVsZCBsYWJlbD0iUGlja3VwIHRpbWUiPjxpbnB1dCBuYW1lPSJwaWNrdXBfdGltZSIgdHlwZT0idGltZSIgY2xhc3NOYW1lPSJndmEtaW5wdXQiIC8+PC9GaWVsZD4KICAgIDxGaWVsZCBsYWJlbD0iS2jDoWNoIHPhuqFuIj48aW5wdXQgbmFtZT0iaG90ZWwiIGNsYXNzTmFtZT0iZ3ZhLWlucHV0IiAvPjwvRmllbGQ+CidAIEAnCiAgICA8RmllbGQgbGFiZWw9IlBpY2t1cCB0aW1lIj48aW5wdXQgbmFtZT0icGlja3VwX3RpbWUiIHR5cGU9InRpbWUiIGNsYXNzTmFtZT0iZ3ZhLWlucHV0IiAvPjwvRmllbGQ+CiAgICA8RmllbGQgbGFiZWw9Iktow6FjaCBz4bqhbiI+PGlucHV0IG5hbWU9ImhvdGVsIiBjbGFzc05hbWU9Imd2YS1pbnB1dCIgcGxhY2Vob2xkZXI9IlZEOiBNYW5kaWxhIEJlYWNoIEhvdGVsIiAvPjwvRmllbGQ+CiAgICA8RmllbGQgbGFiZWw9IsSQ4buLYSBjaOG7iSBraMOhY2ggc+G6oW4iIHdpZGU+PGlucHV0IG5hbWU9ImhvdGVsX2FkZHJlc3MiIGNsYXNzTmFtZT0iZ3ZhLWlucHV0IiBwbGFjZWhvbGRlcj0iVkQ6IDIxOCBWw7UgTmd1ecOqbiBHacOhcCwgU8ahbiBUcsOgLCDEkMOgIE7hurVuZyIgLz48L0ZpZWxkPgonQCAiaG90ZWwgYWRkcmVzcyBmaWVsZCIKCltJTy5GaWxlXTo6V3JpdGVBbGxUZXh0KCRwYXRoLCAkdGV4dCwgJHV0ZjgpCldyaXRlLUhvc3QgIltPS10gT3BlcmF0aW9uc0NlbnRlciBWMyBwYXRjaGVkIHN1Y2Nlc3NmdWxseS4iIC1Gb3JlZ3JvdW5kQ29sb3IgR3JlZW4K
)
certutil -f -decode "%PATCH_B64%" "%PATCH_PS1%" >nul
if errorlevel 1 goto FAIL_WORKTREE
powershell -NoProfile -ExecutionPolicy Bypass -File "%PATCH_PS1%"
set "PATCH_RC=%ERRORLEVEL%"
del /q "%PATCH_B64%" "%PATCH_PS1%" >nul 2>&1
if not "%PATCH_RC%"=="0" goto FAIL_WORKTREE

if exist "%PROJECT%\.env.local" copy /Y "%PROJECT%\.env.local" "%WORKTREE%\.env.local" >nul
if exist "%PROJECT%\node_modules" (
  echo [4/7] Dung node_modules hien tai...
  cmd /c mklink /J "%WORKTREE%\node_modules" "%PROJECT%\node_modules" >nul 2>&1
) else (
  echo [4/7] Cai dependencies...
  pushd "%WORKTREE%"
  if exist package-lock.json (call npm ci) else (call npm install)
  if errorlevel 1 (popd & goto FAIL_WORKTREE)
  popd
)

echo [5/7] Production build check...
pushd "%WORKTREE%"
call npm run build
if errorlevel 1 (
  popd
  echo [STOP] BUILD FAILED. Khong push production.
  goto FAIL_WORKTREE
)
popd

echo [6/7] Commit change...
git -C "%WORKTREE%" add -- "components/admin-v5/OperationsCenter.tsx"
git -C "%WORKTREE%" diff --cached --quiet
if not errorlevel 1 (
  echo [OK] V3 da co san tren origin/main.
  goto CLEAN_SUCCESS
)
git -C "%WORKTREE%" -c user.name="GoVietStay Installer" -c user.email="govietstay@gmail.com" commit -m "feat(operations): show deposit add hotel address and safe delete" -- "components/admin-v5/OperationsCenter.tsx"
if errorlevel 1 goto FAIL_WORKTREE

echo [7/7] Push main - Vercel auto deploy...
git -C "%WORKTREE%" push origin HEAD:main
if errorlevel 1 goto FAIL_WORKTREE

:CLEAN_SUCCESS
echo.
echo ================================================================
echo  SUCCESS - OPERATIONS V3
echo ================================================================
echo  Database support for hotel address and safe draft delete is ready.
echo  Open after Vercel finishes deployment:
echo  https://www.govietstay.com/admin/operations
echo.
echo  Check:
echo  1. Booking card shows COC + CON LAI
  echo 2. + Booking has DIA CHI KHACH SAN
  echo 3. Customer EN/RU and Driver VI/EN include pickup address
  echo 4. Owner/Admin sees XOA BOOKING
  echo 5. Sales/Desk sees XOA NHAP only on own Pending booking with zero deposit

git -C "%PROJECT%" worktree remove --force "%WORKTREE%" >nul 2>&1
git -C "%PROJECT%" worktree prune >nul 2>&1
pause
exit /b 0

:FAIL_WORKTREE
echo.
echo [STOP] Co loi. Khong push production.
git -C "%PROJECT%" worktree remove --force "%WORKTREE%" >nul 2>&1
git -C "%PROJECT%" worktree prune >nul 2>&1
pause
exit /b 1

:FAIL
echo.
echo [STOP] Khong the chuan bi source. Khong push production.
pause
exit /b 1
