@echo off
setlocal EnableExtensions
title GoVietStay - Install Yandex Metrika 112457261
cd /d "%~dp0"

echo ============================================================
echo   GoVietStay - Install Yandex Metrika
echo   Counter ID: 112457261
echo ============================================================
echo.

if not exist ".git" (
  echo [ERROR] Put this BAT file in the ROOT folder:
  echo         govietstay-main-website
  echo.
  pause
  exit /b 1
)

if not exist "app\layout.tsx" (
  echo [ERROR] app\layout.tsx not found.
  echo This installer is made for the current GoVietStay project.
  pause
  exit /b 1
)

if not exist "components" mkdir "components"

echo [1/5] Creating components\YandexMetrika.tsx ...
powershell -NoProfile -ExecutionPolicy Bypass -Command "[IO.File]::WriteAllBytes('components\YandexMetrika.tsx',[Convert]::FromBase64String('aW1wb3J0IFNjcmlwdCBmcm9tICJuZXh0L3NjcmlwdCI7CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBZYW5kZXhNZXRyaWthKCkgewogIHJldHVybiAoCiAgICA8PgogICAgICA8U2NyaXB0IGlkPSJ5YW5kZXgtbWV0cmlrYSIgc3RyYXRlZ3k9ImFmdGVySW50ZXJhY3RpdmUiPgogICAgICAgIHtgCiAgICAgICAgICAoZnVuY3Rpb24obSxlLHQscixpLGssYSl7CiAgICAgICAgICAgICAgbVtpXT1tW2ldfHxmdW5jdGlvbigpeyhtW2ldLmE9bVtpXS5hfHxbXSkucHVzaChhcmd1bWVudHMpfTsKICAgICAgICAgICAgICBtW2ldLmw9MSpuZXcgRGF0ZSgpOwogICAgICAgICAgICAgIGZvciAodmFyIGogPSAwOyBqIDwgZG9jdW1lbnQuc2NyaXB0cy5sZW5ndGg7IGorKykgewogICAgICAgICAgICAgICAgICBpZiAoZG9jdW1lbnQuc2NyaXB0c1tqXS5zcmMgPT09IHIpIHsgcmV0dXJuOyB9CiAgICAgICAgICAgICAgfQogICAgICAgICAgICAgIGs9ZS5jcmVhdGVFbGVtZW50KHQpLGE9ZS5nZXRFbGVtZW50c0J5VGFnTmFtZSh0KVswXSxrLmFzeW5jPTEsay5zcmM9cixhLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKGssYSkKICAgICAgICAgIH0pKHdpbmRvdywgZG9jdW1lbnQsJ3NjcmlwdCcsJ2h0dHBzOi8vbWMueWFuZGV4LnJ1L21ldHJpa2EvdGFnLmpzP2lkPTExMjQ1NzI2MScsICd5bScpOwoKICAgICAgICAgIHltKDExMjQ1NzI2MSwgJ2luaXQnLCB7CiAgICAgICAgICAgICAgc3NyOnRydWUsCiAgICAgICAgICAgICAgd2Vidmlzb3I6dHJ1ZSwKICAgICAgICAgICAgICBjbGlja21hcDp0cnVlLAogICAgICAgICAgICAgIGVjb21tZXJjZToiZGF0YUxheWVyIiwKICAgICAgICAgICAgICByZWZlcnJlcjogZG9jdW1lbnQucmVmZXJyZXIsCiAgICAgICAgICAgICAgdXJsOiBsb2NhdGlvbi5ocmVmLAogICAgICAgICAgICAgIGFjY3VyYXRlVHJhY2tCb3VuY2U6dHJ1ZSwKICAgICAgICAgICAgICB0cmFja0xpbmtzOnRydWUKICAgICAgICAgIH0pOwogICAgICAgIGB9CiAgICAgIDwvU2NyaXB0PgoKICAgICAgPG5vc2NyaXB0PgogICAgICAgIDxkaXY+CiAgICAgICAgICA8aW1nCiAgICAgICAgICAgIHNyYz0iaHR0cHM6Ly9tYy55YW5kZXgucnUvd2F0Y2gvMTEyNDU3MjYxIgogICAgICAgICAgICBzdHlsZT17eyBwb3NpdGlvbjogImFic29sdXRlIiwgbGVmdDogIi05OTk5cHgiIH19CiAgICAgICAgICAgIGFsdD0iIgogICAgICAgICAgLz4KICAgICAgICA8L2Rpdj4KICAgICAgPC9ub3NjcmlwdD4KICAgIDwvPgogICk7Cn0K'))"
if errorlevel 1 (
  echo [ERROR] Could not create YandexMetrika component.
  pause
  exit /b 1
)

echo.
echo [2/5] Updating app\layout.tsx safely ...
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand CgAkAEUAcgByAG8AcgBBAGMAdABpAG8AbgBQAHIAZQBmAGUAcgBlAG4AYwBlACAAPQAgACIAUwB0AG8AcAAiAAoACgAkAGwAYQB5AG8AdQB0ACAAPQAgACIAYQBwAHAAXABsAGEAeQBvAHUAdAAuAHQAcwB4ACIACgAkAGMAbwBtAHAAbwBuAGUAbgB0ACAAPQAgACIAYwBvAG0AcABvAG4AZQBuAHQAcwBcAFkAYQBuAGQAZQB4AE0AZQB0AHIAaQBrAGEALgB0AHMAeAAiAAoACgBpAGYAIAAoAC0AbgBvAHQAIAAoAFQAZQBzAHQALQBQAGEAdABoACAAJABsAGEAeQBvAHUAdAApACkAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEUAUgBSAE8AUgBdACAAYQBwAHAAXABsAGEAeQBvAHUAdAAuAHQAcwB4ACAAbgBvAHQAIABmAG8AdQBuAGQALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFIAZQBkAAoAIAAgACAAIABlAHgAaQB0ACAAMQAKAH0ACgAKACQAcwB0AGEAbQBwACAAPQAgAEcAZQB0AC0ARABhAHQAZQAgAC0ARgBvAHIAbQBhAHQAIAAiAHkAeQB5AHkATQBNAGQAZAAtAEgASABtAG0AcwBzACIACgAkAGIAYQBjAGsAdQBwACAAPQAgACIAJABsAGEAeQBvAHUAdAAuAGIAYQBrAC0AeQBhAG4AZABlAHgALQAkAHMAdABhAG0AcAAiAAoAQwBvAHAAeQAtAEkAdABlAG0AIAAkAGwAYQB5AG8AdQB0ACAAJABiAGEAYwBrAHUAcAAgAC0ARgBvAHIAYwBlAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBPAEsAXQAgAEIAYQBjAGsAdQBwACAAYwByAGUAYQB0AGUAZAA6ACAAJABiAGEAYwBrAHUAcAAiAAoACgAkAHQAZQB4AHQAIAA9ACAAWwBJAE8ALgBGAGkAbABlAF0AOgA6AFIAZQBhAGQAQQBsAGwAVABlAHgAdAAoACQAbABhAHkAbwB1AHQAKQAKAAoAaQBmACAAKAAkAHQAZQB4AHQAIAAtAG4AbwB0AG0AYQB0AGMAaAAgACcAWQBhAG4AZABlAHgATQBlAHQAcgBpAGsAYQAnACkAIAB7AAoAIAAgACAAIAAkAGEAbgBjAGgAbwByAEkAbQBwAG8AcgB0ACAAPQAgACcAaQBtAHAAbwByAHQAIABIAHQAbQBsAEwAYQBuAGcAdQBhAGcAZQBTAHkAbgBjACAAZgByAG8AbQAgACIALgAuAC8AYwBvAG0AcABvAG4AZQBuAHQAcwAvAEgAdABtAGwATABhAG4AZwB1AGEAZwBlAFMAeQBuAGMAIgA7ACcACgAgACAAIAAgAGkAZgAgACgALQBuAG8AdAAgACQAdABlAHgAdAAuAEMAbwBuAHQAYQBpAG4AcwAoACQAYQBuAGMAaABvAHIASQBtAHAAbwByAHQAKQApACAAewAKACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEUAUgBSAE8AUgBdACAAQwBvAHUAbABkACAAbgBvAHQAIABmAGkAbgBkACAASAB0AG0AbABMAGEAbgBnAHUAYQBnAGUAUwB5AG4AYwAgAGkAbQBwAG8AcgB0ACAAYQBuAGMAaABvAHIALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFIAZQBkAAoAIAAgACAAIAAgACAAIAAgAGUAeABpAHQAIAAxAAoAIAAgACAAIAB9AAoACgAgACAAIAAgACQAdABlAHgAdAAgAD0AIAAkAHQAZQB4AHQALgBSAGUAcABsAGEAYwBlACgACgAgACAAIAAgACAAIAAgACAAJABhAG4AYwBoAG8AcgBJAG0AcABvAHIAdAAsAAoAIAAgACAAIAAgACAAIAAgACQAYQBuAGMAaABvAHIASQBtAHAAbwByAHQAIAArACAAWwBFAG4AdgBpAHIAbwBuAG0AZQBuAHQAXQA6ADoATgBlAHcATABpAG4AZQAgACsAIAAnAGkAbQBwAG8AcgB0ACAAWQBhAG4AZABlAHgATQBlAHQAcgBpAGsAYQAgAGYAcgBvAG0AIAAiAC4ALgAvAGMAbwBtAHAAbwBuAGUAbgB0AHMALwBZAGEAbgBkAGUAeABNAGUAdAByAGkAawBhACIAOwAnAAoAIAAgACAAIAApAAoACgAgACAAIAAgACQAYQBuAGMAaABvAHIAQgBvAGQAeQAgAD0AIAAnADwASAB0AG0AbABMAGEAbgBnAHUAYQBnAGUAUwB5AG4AYwAgAC8APgAnAAoAIAAgACAAIABpAGYAIAAoAC0AbgBvAHQAIAAkAHQAZQB4AHQALgBDAG8AbgB0AGEAaQBuAHMAKAAkAGEAbgBjAGgAbwByAEIAbwBkAHkAKQApACAAewAKACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEUAUgBSAE8AUgBdACAAQwBvAHUAbABkACAAbgBvAHQAIABmAGkAbgBkACAAPABIAHQAbQBsAEwAYQBuAGcAdQBhAGcAZQBTAHkAbgBjACAALwA+ACAAYQBuAGMAaABvAHIALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFIAZQBkAAoAIAAgACAAIAAgACAAIAAgAGUAeABpAHQAIAAxAAoAIAAgACAAIAB9AAoACgAgACAAIAAgACQAdABlAHgAdAAgAD0AIAAkAHQAZQB4AHQALgBSAGUAcABsAGEAYwBlACgACgAgACAAIAAgACAAIAAgACAAJABhAG4AYwBoAG8AcgBCAG8AZAB5ACwACgAgACAAIAAgACAAIAAgACAAJABhAG4AYwBoAG8AcgBCAG8AZAB5ACAAKwAgAFsARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AE4AZQB3AEwAaQBuAGUAIAArACAAJwAgACAAIAAgACAAIAAgACAAPABZAGEAbgBkAGUAeABNAGUAdAByAGkAawBhACAALwA+ACcACgAgACAAIAAgACkACgAKACAAIAAgACAAWwBJAE8ALgBGAGkAbABlAF0AOgA6AFcAcgBpAHQAZQBBAGwAbABUAGUAeAB0ACgAJABsAGEAeQBvAHUAdAAsACAAJAB0AGUAeAB0ACwAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABUAGUAeAB0AC4AVQBUAEYAOABFAG4AYwBvAGQAaQBuAGcAKAAkAGYAYQBsAHMAZQApACkAKQAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBPAEsAXQAgAFkAYQBuAGQAZQB4AE0AZQB0AHIAaQBrAGEAIABhAGQAZABlAGQAIAB0AG8AIABhAHAAcABcAGwAYQB5AG8AdQB0AC4AdABzAHgAIgAKAH0ACgBlAGwAcwBlACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBJAE4ARgBPAF0AIABZAGEAbgBkAGUAeABNAGUAdAByAGkAawBhACAAaQBzACAAYQBsAHIAZQBhAGQAeQAgAHIAZQBmAGUAcgBlAG4AYwBlAGQAIABpAG4AIABhAHAAcABcAGwAYQB5AG8AdQB0AC4AdABzAHgAIgAKAH0ACgAKACQAdgBlAHIAaQBmAHkAIAA9ACAAWwBJAE8ALgBGAGkAbABlAF0AOgA6AFIAZQBhAGQAQQBsAGwAVABlAHgAdAAoACQAbABhAHkAbwB1AHQAKQAKAGkAZgAgACgAJAB2AGUAcgBpAGYAeQAgAC0AbgBvAHQAbQBhAHQAYwBoACAAJwBZAGEAbgBkAGUAeABNAGUAdAByAGkAawBhACcAKQAgAHsACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsARQBSAFIATwBSAF0AIABWAGUAcgBpAGYAaQBjAGEAdABpAG8AbgAgAGYAYQBpAGwAZQBkADoAIABsAGEAeQBvAHUAdAAgAGQAbwBlAHMAIABuAG8AdAAgAGMAbwBuAHQAYQBpAG4AIABZAGEAbgBkAGUAeABNAGUAdAByAGkAawBhAC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABSAGUAZAAKACAAIAAgACAAZQB4AGkAdAAgADEACgB9AAoACgBpAGYAIAAoAC0AbgBvAHQAIAAoAFQAZQBzAHQALQBQAGEAdABoACAAJABjAG8AbQBwAG8AbgBlAG4AdAApACkAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEUAUgBSAE8AUgBdACAAYwBvAG0AcABvAG4AZQBuAHQAcwBcAFkAYQBuAGQAZQB4AE0AZQB0AHIAaQBrAGEALgB0AHMAeAAgAHcAYQBzACAAbgBvAHQAIABjAHIAZQBhAHQAZQBkAC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABSAGUAZAAKACAAIAAgACAAZQB4AGkAdAAgADEACgB9AAoACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAE8ASwBdACAARgBpAGwAZQBzACAAdgBlAHIAaQBmAGkAZQBkAC4AIgAKAA==
if errorlevel 1 (
  echo.
  echo [ERROR] Layout update failed. No Git push was done.
  pause
  exit /b 1
)

echo.
echo [3/5] Checking Git diff ...
git diff -- "app/layout.tsx" "components/YandexMetrika.tsx"
echo.

findstr /C:"112457261" "components\YandexMetrika.tsx" >nul
if errorlevel 1 (
  echo [ERROR] Counter ID check failed.
  pause
  exit /b 1
)

echo [4/5] Commit changes ...
git add "app/layout.tsx" "components/YandexMetrika.tsx"
git diff --cached --quiet
if %errorlevel%==0 (
  echo [INFO] Nothing new to commit. Metrika may already be installed.
) else (
  git commit -m "feat: install Yandex Metrika counter 112457261"
  if errorlevel 1 (
    echo [ERROR] Git commit failed.
    pause
    exit /b 1
  )
)

echo.
echo [5/5] Push to GitHub main ...
git push origin main
if errorlevel 1 (
  echo.
  echo [ERROR] Push failed.
  echo Try:
  echo   git pull --rebase origin main
  echo Then run this BAT again.
  pause
  exit /b 1
)

echo.
echo ============================================================
echo   DONE - Yandex Metrika 112457261 installed
echo ============================================================
echo Vercel will deploy automatically.
echo.
echo IMPORTANT:
echo - Keep ssr:true
echo - Keep webvisor:true
echo - Keep ecommerce:"dataLayer"
echo - Counter is installed ONCE in the root layout,
echo   so it covers /, /ru, /en, /ko, /it and other pages.
echo.
echo After Vercel deployment is READY:
echo   1. Open Yandex Metrika
echo   2. Click "Check tag"
echo   3. Then click "Get started"
echo.
pause
