import type {Metadata} from "next";import {kazakhstanSeoPages} from "../../lib/kazakhstanSeoPages";import {kazakhstanPrices} from "../../lib/kazakhstanPrices";import {kazakhstanGuestPhotos,kazakhstanHubVisuals,getKazakhstanVisual} from "../../lib/kazakhstanVisuals";import styles from "./KazakhstanHub.module.css";
export const metadata:Metadata={title:{absolute:"Вьетнам для туристов из Казахстана 2026 | Дананг и Фукуок | GoVietStay"},description:"Экскурсии и локальная поддержка во Вьетнаме для гостей из Казахстана: Дананг, Хойан, Хюэ, Фукуок, private, семьи, виза и трансфер.",alternates:{canonical:"https://www.govietstay.com/kz",languages:{"ru-KZ":"https://www.govietstay.com/kz"}},robots:{index:true,follow:true}};
const wa="https://wa.me/84937762607";const by=(s:string)=>kazakhstanSeoPages.find(p=>p.slug===s);const featured=["ba-na-hills-golden-bridge","cham-island-tour","hoi-an-coconut-forest","hue-from-danang","phu-quoc-three-islands","phu-quoc-four-islands-hon-thom"];
function price(s:string){const p=by(s);if(!p?.priceKey)return"Запросить цену";const x=kazakhstanPrices[p.priceKey];if(!x)return"Запросить цену";return x.kind==="dual"?x.standardAdult:x.adult}
export default function KazakhstanHub(){return <main className={styles.page}><div className={styles.top}><span>ҚАЗАҚСТАН → VIỆT NAM</span><b>Алматы · Астана → Дананг · Фукуок</b><a href="/ru">Русская версия →</a></div><header className={styles.nav}><a href="/kz" className={styles.brand}><img src="/govietstay-logo.jpg" alt="GoVietStay"/><span><b>GoVietStay</b><small>ДЛЯ ГОСТЕЙ ИЗ КАЗАХСТАНА</small></span></a><nav><a href="#danang">Дананг</a><a href="#phuquoc">Фукуок</a><a href="#kz">Перед вылетом</a><a href="#family">Семья</a><a className={styles.cta} href={wa} target="_blank">WhatsApp</a></nav></header>
<section className={styles.hero}><div className={styles.main}><img src={kazakhstanHubVisuals.hero} alt="Дананг"/><div className={styles.shade}/><div className={styles.copy}><p>ПЕРЕЛЁТ И ОТЕЛЬ УЖЕ КУПЛЕНЫ? ТОГДА НУЖНА ПОМОЩЬ НА МЕСТЕ.</p><h1>Казахстан → Вьетнам. <em>GoVietStay включается после прилёта.</em></h1><h2>Transfer, экскурсии, private, семья и русскоязычная поддержка в Дананге и на Фукуоке — без второго турпакета.</h2><div className={styles.actions}><a href="#danang">Экскурсии Дананг</a><a href="#phuquoc">Фукуок</a><a href={wa} target="_blank">WhatsApp</a></div><div className={styles.proof}><span>✓ до 30 дней без визы*</span><span>✓ цены как на /ru</span><span>✓ private для семьи</span></div></div></div><div className={styles.mosaic}><a href="/kz/danang-from-almaty"><img src={kazakhstanHubVisuals.danang} alt="Алматы Дананг"/><span><small>АЛМАТЫ / АСТАНА</small><b>Дананг</b></span></a><a href="/kz/hoi-an-coconut-forest"><img src={kazakhstanHubVisuals.hoiAn} alt="Хойан"/><span><small>ЦЕНТРАЛЬНЫЙ ВЬЕТНАМ</small><b>Хойан</b></span></a><a className={styles.wide} href="/kz/phu-quoc-tours-russian"><img src={kazakhstanHubVisuals.phuQuoc} alt="Фукуок"/><span><small>RESORT + ОСТРОВА</small><b>Фукуок</b></span></a></div></section>
<section className={styles.strip}><a href="/kz/vietnam-visa-free-kazakhstan"><small>ВИЗА</small><b>До 30 дней*</b><span>Проверить условия →</span></a><a href="/kz/danang-from-almaty"><small>АЛМАТЫ</small><b>Дананг</b><span>После прилёта →</span></a><a href="/kz/phu-quoc-from-astana"><small>АСТАНА</small><b>Фукуок</b><span>Resort + transfer →</span></a><a href="/kz/halal-vietnam-danang-phu-quoc"><small>HALAL</small><b>Без догадок</b><span>Что проверить →</span></a></section>
<section className={styles.section} id="danang"><div className={styles.head}><div><p>01 · ДАНАНГ</p><h2>Только то, что нужно уже во Вьетнаме.</h2></div><span>GoVietStay не конкурирует с казахстанскими агентствами за авиапакет. Наша зона — экскурсии, transfer и помощь после прилёта.</span></div><div className={styles.cards}>{featured.slice(0,4).map(s=>{const p=by(s)!;const v=getKazakhstanVisual(p.slug,p.destination);return <a href={`/kz/${s}`} key={s}><div className={styles.photo}><img src={v.hero} alt={p.h1}/><span>{p.destination}</span></div><div className={styles.body}><h3>{p.h1}</h3><p>{p.description}</p><div><strong>{price(s)}</strong><b>Подробнее →</b></div></div></a>})}</div></section>
<section className={styles.price}><div><p>ЦЕНЫ KZ = ЦЕНЫ РУССКОЙ ВЕРСИИ</p><h2>Отдельной “цены для Казахстана” нет.</h2><span>Основная валюта VND, USD — ориентир. Нужен пример в ₸ — менеджер пересчитает по курсу на день запроса.</span></div><a href="/ru">Сравнить с /ru →</a></section>
<section className={styles.phu} id="phuquoc"><div><p>02 · ФУКУОК</p><h2>Resort уже куплен? Выбирайте только нужные активности.</h2><span>3/4 острова, Хон Тхом, закат, кальмары, private и яхта.</span><a href="/kz/phu-quoc-tours-russian">Все экскурсии →</a></div><div className={styles.phuCards}>{featured.slice(4).map(s=>{const p=by(s)!;const v=getKazakhstanVisual(p.slug,p.destination);return <a href={`/kz/${s}`} key={s}><img src={v.hero} alt={p.h1}/><div><small>{p.destination}</small><h3>{p.h1}</h3><strong>{price(s)}</strong><b>Смотреть →</b></div></a>})}<a href="/kz/phu-quoc-private-sailing"><img src="/tour/phuquoc/tour-08-1.jpg" alt="Private Фукуок"/><div><small>PRIVATE</small><h3>Частный парусный маршрут</h3><strong>3 250 000 VND</strong><b>Смотреть →</b></div></a></div></section>
<section className={styles.family} id="family"><div><img src="/happy-travelers/02462467f09771c928865.jpg" alt="Семья"/></div><div><p>03 · СЕМЬЯ / PRIVATE</p><h2>Сначала скажите, кто едет. Потом строим маршрут.</h2>{["Сколько гостей?","Возраст детей?","Есть старшие родители?","Что любите?","Что точно не хотите?"].map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}<a href="/kz/family-tours-danang">Семейные маршруты →</a></div></section>
<section className={styles.section} id="kz"><div className={styles.head}><div><p>04 · ЗАПРОСЫ ИЗ КАЗАХСТАНА</p><h2>Рейс, виза, дети и halal — вот где нужен отдельный SEO-кластер.</h2></div></div><div className={styles.intent}>{["vietnam-from-kazakhstan","danang-from-almaty","danang-from-astana","phu-quoc-from-almaty","phu-quoc-from-astana","vietnam-visa-free-kazakhstan","danang-first-time-kazakhstan","vietnam-with-kids-kazakhstan","halal-vietnam-danang-phu-quoc","danang-or-phu-quoc"].map(s=>{const p=by(s)!;return <a href={`/kz/${s}`} key={s}><small>{p.destination}</small><h3>{p.h1}</h3><p>{p.description}</p><b>Читать →</b></a>})}</div></section>
<section className={styles.guests}><div className={styles.head}><div><p>05 · РЕАЛЬНЫЕ ГОСТИ</p><h2>Меньше обещаний — больше реальных поездок.</h2></div></div><div>{kazakhstanGuestPhotos.map((x,i)=><figure key={x}><img src={x} alt={`Гость ${i+1}`}/></figure>)}</div></section>
<section className={styles.directory}><div className={styles.head}><div><p>06 · 30 LANDING PAGES</p><h2>Вся карта рынка Kazakhstan.</h2></div></div><div>{[["Экскурсии",kazakhstanSeoPages.filter(p=>p.type==="product")],["Private & transfer",kazakhstanSeoPages.filter(p=>p.type==="private"||p.type==="transfer")],["Алматы / Астана",kazakhstanSeoPages.filter(p=>p.type==="arrival")],["Гайды",kazakhstanSeoPages.filter(p=>p.type==="guide")]].map(([label,items])=><div key={label as string}><h3>{label as string}</h3>{(items as typeof kazakhstanSeoPages).map(p=><a href={`/kz/${p.slug}`} key={p.slug}>{p.h1}<span>→</span></a>)}</div>)}</div></section>
<section className={styles.final}><img src="/tour/cham-island/guest-pickup.jpg" alt="GoVietStay"/><div><p>ҚАЗАҚСТАННАН КЕЛДІҢІЗ БЕ?</p><h2>Билеты уже есть? Пришлите дату и hotel — дальше разберёмся вместе.</h2><a href={wa} target="_blank">WhatsApp GoVietStay</a></div></section><div className={styles.mobile}><a href={wa} target="_blank">💬 WhatsApp</a><a href="/kz/danang-tours-russian">🔥 Дананг</a><a href="/kz/phu-quoc-tours-russian">🏝 Фукуок</a></div></main>}
