"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import Image from "next/image";

type Locale = "ru" | "en";
type Tour = {id:string; image:string; weekday:number; name:{ru:string;en:string}; summary:{ru:string;en:string}; baseline:number; notes:{ru:string;en:string}};
const tours:Tour[]=[
 {id:"bana",image:"/tour/bana.jpg",weekday:2,name:{ru:"Бана Хиллс и Золотой мост",en:"Ba Na Hills & Golden Bridge"},summary:{ru:"Горы, панорамы и знаменитый Золотой мост",en:"Mountains, panoramic views and the Golden Bridge"},baseline:1550000,notes:{ru:"Билеты, питание и трансфер уточняются перед подтверждением.",en:"Tickets, lunch and transfers are confirmed before booking."}},
 {id:"hoian",image:"/tour/coconut.jpg",weekday:4,name:{ru:"Хойан и кокосовый лес",en:"Hoi An & Coconut Forest"},summary:{ru:"Лодки-корзины, старый город и огни фонариков",en:"Basket boats, old town and lantern-lit streets"},baseline:1250000,notes:{ru:"Точный состав программы и время встречи подтверждаются заранее.",en:"Final inclusions and pickup times are confirmed in advance."}},
 {id:"cham",image:"/tour/cham.jpg",weekday:6,name:{ru:"Остров Чам: море и снорклинг",en:"Cham Island Snorkeling"},summary:{ru:"Морская прогулка, пляж и подводный мир",en:"A boat trip, beach time and snorkeling"},baseline:950000,notes:{ru:"Поездка зависит от погоды, состояния моря и разрешения на выход.",en:"Departure depends on weather, sea conditions and sailing clearance."}}
];
const words={
ru:{eyebrow:"ТЕСТ 30 ДНЕЙ · КАЛЕНДАРЬ ДО КОНЦА 2027",title:"Больше попутчиков — выгоднее поездка.",intro:"Три любимые экскурсии каждую неделю до конца 2027 года. Выберите удобную дату и отдельную группу с русскоязычным или англоязычным гидом. До 10 гостей в каждой группе.",choose:"Выберите экскурсию",guide:"Язык гида",russian:"Русскоязычный гид",english:"Англоязычный гид",people:"До 10 гостей",status:"Принимаем заявки",regular:"Ориентир обычной цены",quote:"Групповая цена уточняется до оплаты",request:"Отправить заявку",privacy:"Никто из гостей не увидит ваш телефон.",info:"Как это работает",steps:["Выберите экскурсию, язык гида и дату.","Оставьте бесплатную заявку и пригласите друзей: минимум 5 взрослых на одну дату и один язык.","При 5 подтверждённых взрослых проверяем гида, транспорт и билеты; подтверждаем выезд.","При 6, 8 и 10 участниках цену снижаем всем в группе. Итоговая цена и условия — до оплаты."],discount:"Экономьте вместе",discountBody:"От 5 взрослых мы планируем проводить тур. При 6, 8 и 10 участниках цена становится ниже для каждого. Ранние заявки получают ту же конечную цену. В течение тестового месяца цены являются предложением и требуют проверки себестоимости перед оплатой.",warning:"Дата предварительная. Выезд подтвердим при 5 взрослых после проверки гида и поставщиков. Если группа не наберётся, можно перенести заявку или отказаться без оплаты.",name:"Имя",phone:"WhatsApp с кодом страны",hotel:"Отель / район посадки (необязательно)",adults:"Взрослые",children:"Дети",ages:"Возраст детей (если есть)",notes:"Пожелания (необязательно)",consent:"Разрешаю GoVietStay связаться со мной по этой заявке.",submit:"Открыть WhatsApp с заявкой",invalid:"Проверьте имя, телефон, число гостей и согласие.",close:"Закрыть",share:"Поделиться экскурсией",back:"Другие туры GoVietStay",switch:"English",cutoff:"Выезд и стоимость подтверждаются отдельно до оплаты.",notice:"Для морской экскурсии необходимо подтверждение безопасных условий.",date:"Дата",weekdays:["вс","пн","вт","ср","чт","пт","сб"]},
en:{eyebrow:"30-DAY TRIAL · DATES THROUGH 2027",title:"More travellers. Better value for everyone.",intro:"Three popular experiences every week through 2027. Pick a date and a dedicated Russian- or English-speaking guide group, with up to 10 guests per group.",choose:"Choose an experience",guide:"Guide language",russian:"Russian-speaking guide",english:"English-speaking guide",people:"Up to 10 guests",status:"Requests open",regular:"Regular price reference",quote:"Group price confirmed before payment",request:"Request this date",privacy:"Other guests will never see your phone number.",info:"How it works",steps:["Choose a tour, guide language and date.","Send a free request and invite friends: at least 5 adults for the same date and guide language.","At 5 verified adults, we check the guide, transport and tickets, then confirm departure.","At 6, 8 and 10 adults, everyone in the group receives the lower final approved price, shown before payment."],discount:"Save together",discountBody:"From 5 adults we plan to run the group, and at 6, 8 and 10 the price drops for everyone in that cohort. Early guests get the same final price. Pilot tiers are proposals, subject to actual guide and supplier cost approval before payment.",warning:"Dates are tentative. Departure starts at 5 adults after guide and supplier checks. If fewer than 5 join, move your request or decline without paying.",name:"Name",phone:"WhatsApp including country code",hotel:"Hotel / pickup area (optional)",adults:"Adults",children:"Children",ages:"Children's ages, if any",notes:"Special requests (optional)",consent:"I agree GoVietStay may contact me about this request.",submit:"Open WhatsApp request",invalid:"Check your name, phone, guest count and consent.",close:"Close",share:"Share this trip",back:"More GoVietStay tours",switch:"Русский",cutoff:"Departure and price are confirmed separately before payment.",notice:"Sea conditions and departure clearance must be confirmed.",date:"Date",weekdays:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]}
};
// One published weekly calendar through 31 December 2027. Dates remain tentative until confirmed.
function nextDates(weekday:number){
 const today=new Date(),start=new Date(today.getFullYear(),today.getMonth(),today.getDate());
 const daysUntil=(weekday-start.getDay()+7)%7;
 start.setDate(start.getDate()+daysUntil);
 const result:Date[]=[];
 for(let d=new Date(start);d.getFullYear()<=2027;d.setDate(d.getDate()+7)){
   if(d.getFullYear()===2027 && d.getMonth()===11 && d.getDate()>31)break;
   result.push(new Date(d));
   if(result.length>80)break;
 }
 return result;
}
function monthKey(d:Date){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0");}

function iso(d:Date){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");}
const fmt=(n:number)=>new Intl.NumberFormat("vi-VN").format(n)+" ₫";
// Proposed 30-day pilot adult pricing. Must be cost-approved before accepting payment.
// Separate pricing and departure decisions for each tour/date/guide-language cohort.
const pilotPrices:Record<string,{en:{regular:number;tiers:number[]};ru:{regular:number;tiers:number[];proposed?:boolean}}>={
  bana:{en:{regular:1550000,tiers:[1490000,1450000,1390000,1350000]},ru:{regular:2200000,tiers:[2100000,2000000,1900000,1800000]}},
  hoian:{en:{regular:1250000,tiers:[1190000,1150000,1100000,1050000]},ru:{regular:1800000,tiers:[1700000,1650000,1550000,1490000],proposed:true}},
  cham:{en:{regular:950000,tiers:[930000,910000,890000,870000]},ru:{regular:1350000,tiers:[1300000,1250000,1200000,1150000],proposed:true}}
};
const tierSizes=[5,6,8,10];

export default function GroupDealsLanding({locale}:{locale:Locale}){
 const t=words[locale];const [guide,setGuide]=useState<"ru"|"en">("ru");const [selected,setSelected]=useState<{tour:Tour;date:string}|null>(null);
 const [f,setF]=useState({name:"",phone:"",hotel:"",adults:1,children:0,ages:"",notes:"",consent:false});const [error,setError]=useState("");const [sampleGuests,setSampleGuests]=useState(5);const [selectedMonth,setSelectedMonth]=useState("next");
 function submit(e:FormEvent){e.preventDefault();if(!selected||!f.name.trim()||!/^\+?[0-9 ()-]{8,20}$/.test(f.phone.trim())||f.adults+f.children<1||f.adults+f.children>10||!f.consent){setError(t.invalid);return;}const data=[
 "GoVietStay Weekly Group Deals — NEW REQUEST",
 "Tour: "+selected.tour.name.en,"Proposed date: "+selected.date,"Guide group: "+(guide==="ru"?"Russian-speaking":"English-speaking"),
 "Requested pilot tier: "+fmt(pilotPrices[selected.tour.id][guide].tiers[0])+" (at 5 paying adults, pending cost and availability approval)",
 "Customer language: "+locale,"Name: "+f.name.trim(),"WhatsApp: "+f.phone.trim(),"Adults: "+f.adults,"Children: "+f.children,
 "Child ages: "+(f.ages.trim()||"N/A"),"Pickup: "+(f.hotel.trim()||"Not decided"),"Notes: "+(f.notes.trim()||"None"),
 "Free request only. Group operates from 5 confirmed paying adults. Count verified paid bookings only. Confirm approved tier, inclusions, weather, guide and final VND amount before payment."
 ];window.open("https://wa.me/84937762607?text="+encodeURIComponent(data.join("\n")),"_blank","noopener,noreferrer");}
 return <main className="min-h-screen bg-[#f4f9f5] text-slate-900">
 <div className="mx-auto max-w-7xl px-4 pb-16 pt-5 sm:px-6">
 <header className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link href={locale==="ru"?"/ru":"/"} className="flex items-center gap-3"><Image src="/logo.png" width={56} height={56} alt="GoVietStay logo" className="rounded-full bg-white p-1"/><span className="font-black tracking-wide text-emerald-950">GOVIETSTAY<br/><small className="font-semibold text-emerald-700">WEEKLY GROUP DEALS</small></span></Link><Link className="rounded-full bg-white px-5 py-3 text-sm font-bold text-emerald-900 shadow-sm" href={locale==="ru"?"/group-deals":"/ru/group-deals"}>{t.switch}</Link></header>
 <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-emerald-950 via-emerald-900 to-teal-700 p-7 text-white sm:p-12"><div className="relative z-10 max-w-3xl"><span className="rounded-full bg-lime-300 px-4 py-2 text-xs font-black tracking-wide text-emerald-950">{t.eyebrow}</span><h1 className="mt-7 text-4xl font-black leading-tight sm:text-6xl">{t.title}</h1><p className="mt-5 text-lg leading-relaxed text-emerald-50">{t.intro}</p><div className="mt-5 flex flex-wrap gap-3 text-sm font-semibold"><span className="rounded-full bg-white/15 px-4 py-2">3 tours / week</span><span className="rounded-full bg-white/15 px-4 py-2">{locale==="ru"?"Выезд от 5 гостей · максимум 10":"Departs from 5 guests · max 10"}</span><span className="rounded-full bg-white/15 px-4 py-2">{t.cutoff}</span></div><a href="#trips" className="mt-8 inline-block rounded-full bg-lime-300 px-7 py-4 font-black text-emerald-950">{t.choose} ↓</a></div></section>
 <section className="my-8 rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="mb-4 text-xl font-black text-emerald-950">{t.guide}</h2><div className="grid gap-3 sm:grid-cols-2">{(["ru","en"] as const).map(lang=><button key={lang} type="button" onClick={()=>setGuide(lang)} aria-pressed={guide===lang} className={"rounded-2xl border-2 p-5 text-left text-lg font-bold "+(guide===lang?"border-emerald-600 bg-emerald-50 text-emerald-950":"border-slate-200 text-slate-700")}>{lang==="ru"?"🇷🇺 ":"🇬🇧 "}{lang==="ru"?t.russian:t.english}{guide===lang?" ✓":""}</button>)}</div><p className="mt-3 text-sm text-slate-600">{locale==="ru"?"Группы с русским и английским гидом набираются отдельно.":"Russian- and English-guided groups fill separately."} {t.privacy}</p></section>
 <section id="trips" className="scroll-mt-6">
 <h2 className="mb-3 text-3xl font-black text-emerald-950">{t.choose}</h2>
 <p className="mb-5 text-sm leading-relaxed text-slate-600">{locale==="ru"?"По одному запланированному выезду в неделю по каждой экскурсии — календарь до 31 декабря 2027 года. Выберите месяц, чтобы увидеть даты.":"One proposed departure per tour each week, with dates through 31 December 2027. Select a month to see its dates."}</p>
 <label htmlFor="pilot-month" className="mb-6 block max-w-md text-sm font-bold text-emerald-900">{locale==="ru"?"Месяц поездки":"Travel month"}
 <select id="pilot-month" value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} className="mt-2 w-full rounded-xl border border-emerald-300 bg-white px-4 py-3 text-base text-emerald-950">
 <option value="next">{locale==="ru"?"Ближайшие 4 даты каждого тура":"Next 4 dates per tour"}</option>
 {Array.from(new Set(tours.flatMap(tour=>nextDates(tour.weekday).map(monthKey)))).sort().map(m=><option key={m} value={m}>{new Date(Number(m.slice(0,4)),Number(m.slice(5))-1,1).toLocaleDateString(locale==="ru"?"ru-RU":"en-GB",{month:"long",year:"numeric"})}</option>)}
 </select></label><div className="grid gap-6 lg:grid-cols-3">{tours.map(tour=><article key={tour.id} className="overflow-hidden rounded-3xl bg-white shadow-lg shadow-emerald-900/5"><div className="relative h-56"><Image src={tour.image} alt={tour.name[locale]} fill sizes="(max-width:1024px) 100vw, 33vw" className="object-cover"/></div><div className="p-6"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-900">{t.status}</span><h3 className="mt-4 text-2xl font-black text-emerald-950">{tour.name[locale]}</h3><p className="mt-2 min-h-12 text-sm leading-relaxed text-slate-600">{tour.summary[locale]}</p><div className="my-5 rounded-2xl bg-emerald-50 p-4">
<p className="text-sm text-emerald-900">{locale==="ru"?"Обычная цена":"Regular reference"}</p>
<p className="mt-1 text-xl font-semibold text-slate-500 line-through">{fmt(pilotPrices[tour.id][guide].regular)}</p>
<p className="mt-3 text-xs font-bold uppercase text-emerald-800">{locale==="ru"?"Пилот: от 5 участников":"Pilot: from 5 guests"}</p>
<p className="mt-1 text-3xl font-black text-emerald-950">{fmt(pilotPrices[tour.id][guide].tiers[0])}</p>
<p className="mt-1 text-xs text-slate-600">{locale==="ru"?"Цена для 5 человек · до 10 гостей цена снижается":"5 guests · lower tiers at 6, 8 and 10"}</p>
<div className="mt-4 grid grid-cols-2 gap-2">{tierSizes.map((size,i)=><div key={size} className="rounded-xl border border-emerald-200 bg-white p-2 text-center"><p className="text-xs font-semibold text-emerald-800">{size}{size===6||size===8?"–"+(size===6?7:9):""} {locale==="ru"?"чел.":"guests"}</p><p className="mt-1 text-sm font-black text-emerald-950">{fmt(pilotPrices[tour.id][guide].tiers[i])}</p></div>)}</div>
<p className="mt-3 text-xs leading-relaxed text-amber-900">{locale==="ru"?"Пробные цены: подтвердим после проверки всех расходов. Детский тариф отдельно.":"Proposed trial prices, subject to cost approval. Child pricing separately."}{pilotPrices[tour.id][guide].proposed?" "+(locale==="ru"?"Базовая цена русского гида — проектный расчёт, не действующий прайс.":"Russian-guide baseline is a pilot proposal, not a published rate."):""}</p>
</div><p className="mb-3 text-sm text-slate-600">{tour.notes[locale]}</p><div className="grid grid-cols-2 gap-2">{(selectedMonth==="next"?nextDates(tour.weekday).slice(0,4):nextDates(tour.weekday).filter(d=>monthKey(d)===selectedMonth)).map(d=><button type="button" key={iso(d)} onClick={()=>{setSelected({tour,date:iso(d)});setError("");}} className="rounded-xl border border-emerald-200 px-3 py-3 text-sm font-bold text-emerald-900 hover:border-emerald-700 hover:bg-emerald-50">{t.weekdays[d.getDay()]} {d.toLocaleDateString(locale==="ru"?"ru-RU":"en-GB",{day:"numeric",month:"short"})} →</button>)}</div><button type="button" className="mt-5 text-sm font-bold text-emerald-700 underline underline-offset-4" onClick={()=>{if(navigator.share){navigator.share({title:tour.name[locale],url:window.location.href}).catch(()=>{});}else if(navigator.clipboard){navigator.clipboard.writeText(window.location.href).catch(()=>{});}}}>{t.share}</button></div></article>)}</div></section>
 <section className="mt-10 grid gap-5 md:grid-cols-2"><div className="rounded-3xl bg-white p-7"><h2 className="text-2xl font-black text-emerald-950">{t.discount}</h2><p className="mt-4 leading-relaxed text-slate-700">{t.discountBody}</p><p className="mt-4 rounded-2xl bg-lime-100 p-4 text-sm font-bold text-emerald-950">{locale==="ru"?"5 оплаченных взрослых = минимальная группа, после подтверждения гида и поставщика.":"5 verified paying adults = minimum group, after guide and supplier confirmation."}</p>
<label htmlFor="sample-guests" className="mt-4 block text-sm font-bold text-emerald-950">{locale==="ru"?"Попробуйте: сколько человек в группе?":"Try it: how many guests?"} {sampleGuests}/10</label>
<input id="sample-guests" type="range" min="5" max="10" value={sampleGuests} onChange={e=>setSampleGuests(Number(e.target.value))} className="mt-3 w-full accent-emerald-700"/>
<div className="mt-4 grid grid-cols-4 gap-2">{tierSizes.map(n=><div key={n} className={"rounded-2xl px-2 py-4 text-center font-black "+(sampleGuests>=n?"bg-emerald-700 text-white":"bg-emerald-100 text-emerald-950")}>{n}{n===6||n===8?"–"+(n===6?7:9):""}/10</div>)}</div>
<p className="mt-4 text-xs leading-relaxed text-slate-600">{locale==="ru"?"Это демонстрация цены, а не число реально забронировавших гостей.":"This is a price illustration, not actual booking occupancy."}</p></div><div className="rounded-3xl bg-emerald-950 p-7 text-white"><h2 className="text-2xl font-black">{t.info}</h2><ol className="mt-5 space-y-4">{t.steps.map((x,i)=><li key={i} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-lime-300 font-black text-emerald-950">{i+1}</span><span className="pt-1 text-sm leading-relaxed">{x}</span></li>)}</ol></div></section>
 <p className="mt-7 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-relaxed text-amber-950">{locale==="ru"?"Как только на одну дату и один язык подтверждены 5 оплаченных взрослых, мы проверяем гида, транспорт и наличие билетов и подтверждаем выезд. При 6, 8 и 10 участниках окончательная цена снижается для всех взрослых в той же группе. Если группа не наберётся, предложим другую дату или отменим запрос без оплаты.":"Once 5 paying adults are verified for the same date and guide language, we check the guide, transport and tickets and confirm departure. At 6, 8 and 10 people, the final approved price drops for all adults in that cohort. If fewer than 5 join, choose another date or decline without paying."} {t.warning}</p><footer className="mt-9 text-center text-sm"><Link href={locale==="ru"?"/ru":"/"} className="font-bold text-emerald-900 underline">{t.back}</Link><p className="mt-3 text-slate-600">GoVietStay · Da Nang · Hoi An · Trusted Local Support</p></footer>
 </div>
 {selected&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-3" role="dialog" aria-modal="true" aria-label={t.request} onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null);}}><div className="max-h-[94vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><h2 className="text-2xl font-black text-emerald-950">{selected.tour.name[locale]}</h2><p className="mt-2 text-sm font-medium text-slate-600">{selected.date} · {guide==="ru"?t.russian:t.english}</p></div><button aria-label={t.close} onClick={()=>setSelected(null)} className="rounded-full bg-slate-100 px-3 py-2">✕</button></div><form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2">{([["name",t.name,"text"],["phone",t.phone,"tel"],["hotel",t.hotel,"text"],["ages",t.ages,"text"]] as const).map(([key,label,type])=><label key={key} className={"text-sm font-semibold text-slate-700 "+(key==="ages"&&f.children===0?"hidden":"")}>{label}<input type={type} required={key==="name"||key==="phone"} value={f[key]} onChange={e=>setF(v=>({...v,[key]:e.target.value}))} className="mt-1 w-full rounded-xl border border-slate-300 p-3 outline-emerald-600"/></label>)}{(["adults","children"] as const).map(key=><label key={key} className="text-sm font-semibold text-slate-700">{key==="adults"?t.adults:t.children}<input type="number" min="0" max="10" value={f[key]} onChange={e=>setF(v=>({...v,[key]:Math.max(0,Math.min(10,Number(e.target.value)))}))} className="mt-1 w-full rounded-xl border border-slate-300 p-3"/></label>)}<label className="text-sm font-semibold text-slate-700 sm:col-span-2">{t.notes}<textarea rows={2} value={f.notes} onChange={e=>setF(v=>({...v,notes:e.target.value}))} className="mt-1 w-full rounded-xl border border-slate-300 p-3"/></label><label className="flex gap-3 text-sm text-slate-700 sm:col-span-2"><input type="checkbox" checked={f.consent} onChange={e=>setF(v=>({...v,consent:e.target.checked}))} className="mt-1 accent-emerald-600"/>{t.consent}</label>{error&&<p role="alert" className="rounded-xl bg-rose-100 p-3 text-sm font-semibold text-rose-700 sm:col-span-2">{error}</p>}<p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900 sm:col-span-2">{t.warning}</p><button type="submit" className="rounded-full bg-emerald-600 p-4 font-black text-white sm:col-span-2">{t.submit}</button></form></div></div>}
 </main>;
}
