"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";

type Locale = "ru" | "en";
type Tour = {id:string; image:string; weekday:number; name:{ru:string;en:string}; summary:{ru:string;en:string}; baseline:number; notes:{ru:string;en:string}};
const tours:Tour[]=[
 {id:"bana",image:"/tour/bana.jpg",weekday:2,name:{ru:"Бана Хиллс и Золотой мост",en:"Ba Na Hills & Golden Bridge"},summary:{ru:"Горы, панорамы и знаменитый Золотой мост",en:"Mountains, panoramic views and the Golden Bridge"},baseline:1550000,notes:{ru:"Билеты, питание и трансфер уточняются перед подтверждением.",en:"Tickets, lunch and transfers are confirmed before booking."}},
 {id:"hoian",image:"/tour/coconut.jpg",weekday:4,name:{ru:"Хойан и кокосовый лес",en:"Hoi An & Coconut Forest"},summary:{ru:"Лодки-корзины, старый город и огни фонариков",en:"Basket boats, old town and lantern-lit streets"},baseline:1250000,notes:{ru:"Точный состав программы и время встречи подтверждаются заранее.",en:"Final inclusions and pickup times are confirmed in advance."}},
 {id:"cham",image:"/tour/cham.jpg",weekday:6,name:{ru:"Остров Чам: море и снорклинг",en:"Cham Island Snorkeling"},summary:{ru:"Морская прогулка, пляж и подводный мир",en:"A boat trip, beach time and snorkeling"},baseline:950000,notes:{ru:"Поездка зависит от погоды, состояния моря и разрешения на выход.",en:"Departure depends on weather, sea conditions and sailing clearance."}}
];
const words={
ru:{eyebrow:"ПРОБНЫЙ ЗАПУСК · 30 ДНЕЙ",title:"Больше попутчиков — выгоднее поездка.",intro:"Три любимые экскурсии каждую неделю. Выберите удобную дату и отдельную группу с русскоязычным или англоязычным гидом. До 10 гостей в каждой группе.",choose:"Выберите экскурсию",guide:"Язык гида",russian:"Русскоязычный гид",english:"Англоязычный гид",people:"До 10 гостей",status:"Принимаем заявки",regular:"Ориентир обычной цены",quote:"Групповая цена уточняется до оплаты",request:"Отправить заявку",privacy:"Никто из гостей не увидит ваш телефон.",info:"Как это работает",steps:["Выберите экскурсию, язык гида и дату.","Отправьте бесплатную заявку — без предоплаты.","Мы проверим набор группы, расходы и наличие гида.","Получите итоговую цену и решите, подтверждать ли бронь."],discount:"Экономьте вместе",discountBody:"Мы планируем снижать цену при достижении 4, 6, 8 и 10 гостей. Финальные уровни скидок появятся только после проверки расходов для каждой языковой группы. Ранним участникам доступна та же финальная цена, что и остальным.",warning:"Предварительные даты, а не гарантированный выезд. Если группа не соберётся, предложим перенос или отмену заявки без оплаты.",name:"Имя",phone:"WhatsApp с кодом страны",hotel:"Отель / район посадки (необязательно)",adults:"Взрослые",children:"Дети",ages:"Возраст детей (если есть)",notes:"Пожелания (необязательно)",consent:"Разрешаю GoVietStay связаться со мной по этой заявке.",submit:"Открыть WhatsApp с заявкой",invalid:"Проверьте имя, телефон, число гостей и согласие.",close:"Закрыть",share:"Поделиться экскурсией",back:"Другие туры GoVietStay",switch:"English",cutoff:"Выезд и стоимость подтверждаются отдельно до оплаты.",notice:"Для морской экскурсии необходимо подтверждение безопасных условий.",date:"Дата",weekdays:["вс","пн","вт","ср","чт","пт","сб"]},
en:{eyebrow:"30-DAY TRIAL",title:"More travellers. Better value for everyone.",intro:"Three popular experiences every week. Pick a date and a dedicated Russian- or English-speaking guide group, with up to 10 guests per group.",choose:"Choose an experience",guide:"Guide language",russian:"Russian-speaking guide",english:"English-speaking guide",people:"Up to 10 guests",status:"Requests open",regular:"Regular price reference",quote:"Group price confirmed before payment",request:"Request this date",privacy:"Other guests will never see your phone number.",info:"How it works",steps:["Choose a tour, guide language and date.","Send a free request with no deposit.","We check group size, supplier costs and guide availability.","Get the final quote and choose whether to confirm."],discount:"Save together",discountBody:"We aim to lower the price at group sizes of 4, 6, 8 and 10 guests. Final discounts are published only after costs for each guide-language group are verified. Early guests receive the same final price as everyone else.",warning:"These are proposed dates, not guaranteed departures. If a group does not form, you can move your request or decline without payment.",name:"Name",phone:"WhatsApp including country code",hotel:"Hotel / pickup area (optional)",adults:"Adults",children:"Children",ages:"Children's ages, if any",notes:"Special requests (optional)",consent:"I agree GoVietStay may contact me about this request.",submit:"Open WhatsApp request",invalid:"Check your name, phone, guest count and consent.",close:"Close",share:"Share this trip",back:"More GoVietStay tours",switch:"Русский",cutoff:"Departure and price are confirmed separately before payment.",notice:"Sea conditions and departure clearance must be confirmed.",date:"Date",weekdays:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]}
};
function nextDates(weekday:number){const today=new Date();const monday=new Date(today.getFullYear(),today.getMonth(),today.getDate());monday.setDate(monday.getDate()+((8-monday.getDay())%7||7));return Array.from({length:4},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i*7+weekday-1);return d;});}
function iso(d:Date){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");}
const fmt=(n:number)=>new Intl.NumberFormat("vi-VN").format(n)+" ₫";
export default function GroupDealsLanding({locale}:{locale:Locale}){
 const t=words[locale];const [guide,setGuide]=useState<"ru"|"en">("ru");const [selected,setSelected]=useState<{tour:Tour;date:string}|null>(null);
 const [f,setF]=useState({name:"",phone:"",hotel:"",adults:1,children:0,ages:"",notes:"",consent:false});const [error,setError]=useState("");
 function submit(e:React.FormEvent){e.preventDefault();if(!selected||!f.name.trim()||!/^\+?[0-9 ()-]{8,20}$/.test(f.phone.trim())||f.adults+f.children<1||f.adults+f.children>10||!f.consent){setError(t.invalid);return;}const data=[
 "GoVietStay Weekly Group Deals — NEW REQUEST",
 "Tour: "+selected.tour.name.en,"Proposed date: "+selected.date,"Guide group: "+(guide==="ru"?"Russian-speaking":"English-speaking"),
 "Customer language: "+locale,"Name: "+f.name.trim(),"WhatsApp: "+f.phone.trim(),"Adults: "+f.adults,"Children: "+f.children,
 "Child ages: "+(f.ages.trim()||"N/A"),"Pickup: "+(f.hotel.trim()||"Not decided"),"Notes: "+(f.notes.trim()||"None"),
 "Free request only; please confirm departure, inclusions and final VND price before payment."
 ];window.open("https://wa.me/84937762607?text="+encodeURIComponent(data.join("\n")),"_blank","noopener,noreferrer");}
 return <main className="min-h-screen bg-[#f4f9f5] text-slate-900">
 <div className="mx-auto max-w-7xl px-4 pb-16 pt-5 sm:px-6">
 <header className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link href={locale==="ru"?"/ru":"/"} className="flex items-center gap-3"><Image src="/logo.png" width={56} height={56} alt="GoVietStay logo" className="rounded-full bg-white p-1"/><span className="font-black tracking-wide text-emerald-950">GOVIETSTAY<br/><small className="font-semibold text-emerald-700">WEEKLY GROUP DEALS</small></span></Link><Link className="rounded-full bg-white px-5 py-3 text-sm font-bold text-emerald-900 shadow-sm" href={locale==="ru"?"/group-deals":"/ru/group-deals"}>{t.switch}</Link></header>
 <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-emerald-950 via-emerald-900 to-teal-700 p-7 text-white sm:p-12"><div className="relative z-10 max-w-3xl"><span className="rounded-full bg-lime-300 px-4 py-2 text-xs font-black tracking-wide text-emerald-950">{t.eyebrow}</span><h1 className="mt-7 text-4xl font-black leading-tight sm:text-6xl">{t.title}</h1><p className="mt-5 text-lg leading-relaxed text-emerald-50">{t.intro}</p><div className="mt-5 flex flex-wrap gap-3 text-sm font-semibold"><span className="rounded-full bg-white/15 px-4 py-2">3 tours / week</span><span className="rounded-full bg-white/15 px-4 py-2">{t.people}</span><span className="rounded-full bg-white/15 px-4 py-2">{t.cutoff}</span></div><a href="#trips" className="mt-8 inline-block rounded-full bg-lime-300 px-7 py-4 font-black text-emerald-950">{t.choose} ↓</a></div></section>
 <section className="my-8 rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="mb-4 text-xl font-black text-emerald-950">{t.guide}</h2><div className="grid gap-3 sm:grid-cols-2">{(["ru","en"] as const).map(lang=><button key={lang} type="button" onClick={()=>setGuide(lang)} aria-pressed={guide===lang} className={"rounded-2xl border-2 p-5 text-left text-lg font-bold "+(guide===lang?"border-emerald-600 bg-emerald-50 text-emerald-950":"border-slate-200 text-slate-700")}>{lang==="ru"?"🇷🇺 ":"🇬🇧 "}{lang==="ru"?t.russian:t.english}{guide===lang?" ✓":""}</button>)}</div><p className="mt-3 text-sm text-slate-600">{t.privacy}</p></section>
 <section id="trips" className="scroll-mt-6"><h2 className="mb-6 text-3xl font-black text-emerald-950">{t.choose}</h2><div className="grid gap-6 lg:grid-cols-3">{tours.map(tour=><article key={tour.id} className="overflow-hidden rounded-3xl bg-white shadow-lg shadow-emerald-900/5"><div className="relative h-56"><Image src={tour.image} alt={tour.name[locale]} fill sizes="(max-width:1024px) 100vw, 33vw" className="object-cover"/></div><div className="p-6"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-900">{t.status}</span><h3 className="mt-4 text-2xl font-black text-emerald-950">{tour.name[locale]}</h3><p className="mt-2 min-h-12 text-sm leading-relaxed text-slate-600">{tour.summary[locale]}</p><div className="my-5 rounded-2xl bg-emerald-50 p-4"><p className="text-sm text-emerald-900">{t.regular}</p><p className="mt-1 text-2xl font-black text-emerald-950">{fmt(tour.baseline)}</p><p className="mt-1 text-xs text-slate-600">{t.quote}</p></div><p className="mb-3 text-sm text-slate-600">{tour.notes[locale]}</p><div className="grid grid-cols-2 gap-2">{nextDates(tour.weekday).map(d=><button type="button" key={iso(d)} onClick={()=>{setSelected({tour,date:iso(d)});setError("");}} className="rounded-xl border border-emerald-200 px-3 py-3 text-sm font-bold text-emerald-900 hover:border-emerald-700 hover:bg-emerald-50">{t.weekdays[d.getDay()]} {d.toLocaleDateString(locale==="ru"?"ru-RU":"en-GB",{day:"numeric",month:"short"})} →</button>)}</div><button type="button" className="mt-5 text-sm font-bold text-emerald-700 underline underline-offset-4" onClick={()=>{if(navigator.share){navigator.share({title:tour.name[locale],url:window.location.href}).catch(()=>{});}else if(navigator.clipboard){navigator.clipboard.writeText(window.location.href).catch(()=>{});}}}>{t.share}</button></div></article>)}</div></section>
 <section className="mt-10 grid gap-5 md:grid-cols-2"><div className="rounded-3xl bg-white p-7"><h2 className="text-2xl font-black text-emerald-950">{t.discount}</h2><p className="mt-4 leading-relaxed text-slate-700">{t.discountBody}</p><div className="mt-6 grid grid-cols-4 gap-2">{[4,6,8,10].map(n=><div key={n} className="rounded-2xl bg-emerald-100 px-2 py-4 text-center font-black text-emerald-950">{n}/10</div>)}</div></div><div className="rounded-3xl bg-emerald-950 p-7 text-white"><h2 className="text-2xl font-black">{t.info}</h2><ol className="mt-5 space-y-4">{t.steps.map((x,i)=><li key={i} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-lime-300 font-black text-emerald-950">{i+1}</span><span className="pt-1 text-sm leading-relaxed">{x}</span></li>)}</ol></div></section>
 <p className="mt-7 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-relaxed text-amber-950">{t.warning}</p><footer className="mt-9 text-center text-sm"><Link href={locale==="ru"?"/ru":"/"} className="font-bold text-emerald-900 underline">{t.back}</Link><p className="mt-3 text-slate-600">GoVietStay · Da Nang · Hoi An · Trusted Local Support</p></footer>
 </div>
 {selected&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-3" role="dialog" aria-modal="true" aria-label={t.request} onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null);}}><div className="max-h-[94vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><h2 className="text-2xl font-black text-emerald-950">{selected.tour.name[locale]}</h2><p className="mt-2 text-sm font-medium text-slate-600">{selected.date} · {guide==="ru"?t.russian:t.english}</p></div><button aria-label={t.close} onClick={()=>setSelected(null)} className="rounded-full bg-slate-100 px-3 py-2">✕</button></div><form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2">{([["name",t.name,"text"],["phone",t.phone,"tel"],["hotel",t.hotel,"text"],["ages",t.ages,"text"]] as const).map(([key,label,type])=><label key={key} className={"text-sm font-semibold text-slate-700 "+(key==="ages"&&f.children===0?"hidden":"")}>{label}<input type={type} required={key==="name"||key==="phone"} value={f[key]} onChange={e=>setF(v=>({...v,[key]:e.target.value}))} className="mt-1 w-full rounded-xl border border-slate-300 p-3 outline-emerald-600"/></label>)}{(["adults","children"] as const).map(key=><label key={key} className="text-sm font-semibold text-slate-700">{key==="adults"?t.adults:t.children}<input type="number" min="0" max="10" value={f[key]} onChange={e=>setF(v=>({...v,[key]:Math.max(0,Math.min(10,Number(e.target.value)))}))} className="mt-1 w-full rounded-xl border border-slate-300 p-3"/></label>)}<label className="text-sm font-semibold text-slate-700 sm:col-span-2">{t.notes}<textarea rows={2} value={f.notes} onChange={e=>setF(v=>({...v,notes:e.target.value}))} className="mt-1 w-full rounded-xl border border-slate-300 p-3"/></label><label className="flex gap-3 text-sm text-slate-700 sm:col-span-2"><input type="checkbox" checked={f.consent} onChange={e=>setF(v=>({...v,consent:e.target.checked}))} className="mt-1 accent-emerald-600"/>{t.consent}</label>{error&&<p role="alert" className="rounded-xl bg-rose-100 p-3 text-sm font-semibold text-rose-700 sm:col-span-2">{error}</p>}<p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900 sm:col-span-2">{t.warning}</p><button type="submit" className="rounded-full bg-emerald-600 p-4 font-black text-white sm:col-span-2">{t.submit}</button></form></div></div>}
 </main>;
}
