// Three self-operated GoVietStay experience concepts. Published as bespoke inquiry
// pages: sample times/stops only; no invented price, inclusions, bookings or reviews.
export type SignatureLocale = 'en' | 'ru' | 'it';
export type SignatureSlug = 'da-nang-city-pulse-discovery' | 'da-nang-local-flavors-explorer' | 'da-nang-in-a-day-private-tour';
export const SIGNATURE_SITE = 'https://www.govietstay.com';
export const signatureSlugs: SignatureSlug[] = ['da-nang-city-pulse-discovery','da-nang-local-flavors-explorer','da-nang-in-a-day-private-tour'];
export const signaturePath = (locale: SignatureLocale, slug: SignatureSlug) => `${locale === 'en' ? '/travel' : `/${locale}`}/local-experiences/${slug}`;
export type SignatureCopy = {
  title:string; description:string; keywords:string[]; h1:string; hero:string; eyebrow:string;
  duration:string; guide:string; notice:string; price:string; priceDetail:string; ask:string;
  storyQuestion:string; story:string; whoHeading:string; who:string[];
  routeHeading:string; routeNote:string; stops:{time:string;title:string;body:string}[];
  designHeading:string; design:string[]; includedTitle:string; intended:string[]; extraTitle:string; extras:string[];
  faqTitle:string; faq:{q:string;a:string}[]; ctaHeading:string; ctaDescription:string;
  crossHeading:string; sourceNote:string; creditsHeading:string; back:string; language:string;
  photoAlt:[string,string,string,string];
};
export type Credit = {file:string;author:string;license:string;link:string;licenseUrl:string};
export type SignatureExperience = {slug:SignatureSlug; name:string; photographs:[Credit,Credit,Credit,Credit]; copies:Record<SignatureLocale,SignatureCopy>};
const CC0 = 'https://creativecommons.org/publicdomain/zero/1.0/';
const BYSA4 = 'https://creativecommons.org/licenses/by-sa/4.0/';
const BYSA3 = 'https://creativecommons.org/licenses/by-sa/3.0/';
const CC0FILE = (file:string,author:string):Credit => ({file,author,license:'CC0 1.0',link:`https://commons.wikimedia.org/wiki/File:${file.replaceAll(' ','_')}`,licenseUrl:CC0});
const LICENSED = (file:string,author:string,license:string,licenseUrl:string):Credit => ({file,author,license,link:`https://commons.wikimedia.org/wiki/File:${file.replaceAll(' ','_')}`,licenseUrl});
const bridge = CC0FILE('Da nang dragon bridge.jpg','Thangphan');
const hanRiver = CC0FILE('Han River at night - Da Nang, Vietnam - DSC02111.JPG','Daderot');
const hanMarket = LICENSED('Han Market from above.JPG','Dragfyre','CC BY-SA 3.0',BYSA3);
const marble = LICENSED('Marble Mountain Da Nang.jpg','VeraVidiVici','CC BY-SA 4.0',BYSA4);
const miQuang = LICENSED('Mi-quang-da-nang.jpg','Thindaocong','CC BY-SA 4.0',BYSA4);
const miQuangTwo = LICENSED('Mi Quang 1A Danang.jpg','Jpatokal','CC BY-SA 4.0',BYSA4);
const beach = CC0FILE('Pullman Danang Beach Resort - Da Nang, Vietnam - DSC02282.JPG','Daderot');
const bikes = LICENSED('Motorbike wall Da Nang.JPG','Dragfyre','CC BY-SA 3.0',BYSA3);
export const signatureExperiences:SignatureExperience[] = [
  {slug:'da-nang-city-pulse-discovery',name:'City Pulse Discovery',photographs:[bridge,hanMarket,marble,hanRiver],copies:{
    en:{
      title:'Da Nang Private City Tour | City Pulse Discovery | GoVietStay',description:'Explore Da Nang beyond a checklist: Dragon Bridge, Han River, a local market and cultural stops on a flexible private city tour. English guide standard; request a quote.',keywords:['da nang city tour','private da nang city tour','da nang sightseeing tour','da nang local guide','da nang half day private tour','what to see in da nang'],
      h1:'City Pulse Discovery',hero:'The postcard shows the bridges. What does the city feel like between them?',eyebrow:'GOVIETSTAY · PRIVATE DA NANG CITY TOUR',duration:'Suggested half-day · approximately 3–4 hours',guide:'English-speaking guide is the standard option. Ask us to check Russian or Italian availability and any extra cost.',notice:'A sample private route, tailored and confirmed for your date. We operate the experience ourselves; exact stops, transport, guide and price are agreed before booking.',price:'Private quote on request',priceDetail:'Price depends on party size, vehicle, entrances and date. We do not invent a per-person rate before checking your requirements.',ask:'Plan my private city tour',storyQuestion:'What if your first Da Nang memory were a conversation, not just a photo?',story:'The Han River is a natural place to begin, but there is more to discover: the story of a bridge, the rhythm of a market, the quieter streets and the small details that make this a lived-in city. City Pulse is a private orientation with room for your questions, camera and coffee break.',whoHeading:'An introduction made for your travel style',who:['First-time guests who want to understand the city in a few well-paced hours.','Couples and friends who prefer a private guide to a bus full of strangers.','Families who want to adjust walking, stops and breaks to their needs.','Visitors returning to Da Nang who want a neighbourhood or cultural angle.'],routeHeading:'A sample half-day in the city',routeNote:'Times are illustrative, not confirmed opening times. We arrange the sequence around your hotel, traffic and each venue’s actual opening hours.',stops:[
        {time:'08:30',title:'Meet your guide at the agreed pickup point',body:'Discuss your interests, walking comfort and preferred photo stops. The pickup zone and vehicle are confirmed with your quote.'},
        {time:'09:00',title:'Dragon Bridge and the Han River',body:'See the riverside landmarks and hear how the bridges connect both sides of Da Nang. Stop for photographs where access permits.'},
        {time:'10:00',title:'Choose a cultural or neighbourhood perspective',body:'Consider the Museum of Cham Sculpture if open, or a suitable local-life stop. Admission is included only if specified in your quotation.'},
        {time:'11:00',title:'Explore a local market',body:'Han Market is one possible stop: discover everyday produce and shopping etiquette rather than treating the market as a mandatory sales stop.'},
        {time:'12:00',title:'Coffee or hotel return',body:'Finish at an agreed location; a drink can be added if requested and priced in advance.'}],designHeading:'The GoVietStay difference',design:['A private route with one coherent story, not a race through unrelated sights.','Walking, vehicle type and pickup arranged to suit your group.','Transparent admission and meal details in the final written quote.','An English-speaking guide as standard; another language only after we check the request.'],includedTitle:'What we can arrange',intended:['A private Da Nang city itinerary and WhatsApp planning.','An English-speaking guide and agreed pickup/return, subject to confirmation.','A sensible selection of city stops, breaks and photo time.'],extraTitle:'Confirm before booking',extras:['Final fee, number of guests, hotel pickup zone and vehicle type.','Museum or other admission, food, drinks and personal purchases.','Russian/Italian-speaking guide requests, accessibility, weather and cancellation.'],faqTitle:'Da Nang city tour: useful answers',faq:[
        {q:'What does this private Da Nang city tour cover?',a:'The sample route connects the Han River and Dragon Bridge with a cultural stop, a local market and optional coffee. We confirm actual stops and any tickets before you book.'},
        {q:'How long does a half-day city tour take?',a:'Allow approximately 3–4 hours for this example. Your final pickup, traffic and walking preferences determine the confirmed duration.'},
        {q:'Is the guide Russian-speaking or Italian-speaking?',a:'The standard guide speaks English. Contact GoVietStay before booking to request a Russian- or Italian-speaking guide; availability and any extra fee require confirmation.'},
        {q:'Is this suitable for families or people who walk less?',a:'A private tour can be adapted, but some stops have steps or crowds. Tell us ages and mobility needs; vehicle and route suitability are checked individually.'},
        {q:'Are admission tickets and lunch included?',a:'Not by default. Every included entrance, meal and transfer will be itemised in your written quote so there are no assumed inclusions.'},
        {q:'How much is a private Da Nang city tour?',a:'Request a quote with your date, group size, hotel and guide language. The price depends on these details and any attraction tickets or transport requested.'}],ctaHeading:'Tell us what you are curious about.',ctaDescription:'Send your date, group size, hotel, walking preferences and preferred guide language. We will send a realistic route and itemised quote.',crossHeading:'Keep discovering Da Nang',sourceNote:'Destination photos are illustrations, not images of this completed GoVietStay tour.',creditsHeading:'Photography, authors and reuse licences',back:'Da Nang travel guide',language:'Language',photoAlt:['Dragon Bridge in Da Nang, the city tour’s proposed riverfront area','Han Market seen from above, illustrative of a possible local-market stop','Marble Mountains in Da Nang, an optional separate extension requiring extra time','The Han River illuminated at night, an example of another side of Da Nang']
    },
    ru:{
      title:'Индивидуальная обзорная экскурсия по Данангу | City Pulse | GoVietStay',description:'Дананг без спешки: мост Дракона, река Хан, местный рынок и история города. Индивидуальная экскурсия с англоязычным гидом; русский — по запросу.',keywords:['обзорная экскурсия Дананг','индивидуальная экскурсия по Данангу','Дананг достопримечательности','что посмотреть в Дананге','частный тур Дананг','экскурсия с гидом Дананг'],h1:'City Pulse Discovery',hero:'На открытке — мосты. А что скрывается между ними в повседневной жизни?',eyebrow:'GOVIETSTAY · ИНДИВИДУАЛЬНАЯ ЭКСКУРСИЯ ПО ДАНАНГУ',duration:'Примерно 3–4 часа · индивидуальный маршрут',guide:'Стандартное сопровождение — гид на английском. Русскоязычный или италоязычный гид — только по предварительному запросу, при наличии и с подтверждением возможной доплаты.',notice:'Пример программы, которую мы организуем самостоятельно и адаптируем под вашу дату. Остановки, транспорт, гид и стоимость согласуем до бронирования.',price:'Стоимость — по запросу',priceDetail:'Цена зависит от числа гостей, автомобиля, билетов и даты. Не указываем выдуманную цену без расчёта.',ask:'Запросить индивидуальную программу',storyQuestion:'Что, если первое знакомство с Данангом начнётся с истории, а не с фото?',story:'Река Хан — удобная отправная точка, но город гораздо глубже: истории мостов, звуки рынка, жилые улицы и повседневные привычки. City Pulse — неспешная индивидуальная прогулка с возможностью задавать вопросы, останавливаться для фото и отдыхать за чашкой кофе.',whoHeading:'Для вашего стиля путешествия',who:['Тем, кто впервые в Дананге и хочет разобраться в городе за несколько часов.','Парам и друзьям, предпочитающим частную экскурсию большому автобусу.','Семьям, которым важно согласовать пешие участки и перерывы.','Гостям, уже бывавшим здесь и желающим изучить культуру или местные районы.'],routeHeading:'Пример маршрута на полдня',routeNote:'Время ориентировочное: часы работы, пробки, отель и ваши пожелания уточним при подтверждении.',stops:[
      {time:'08:30',title:'Встреча с гидом',body:'Уточним интересы и удобный темп. Адрес встречи и тип машины согласуем в расчёте.'},
      {time:'09:00',title:'Мост Дракона и река Хан',body:'Прогулка у знаковых мостов, рассказ о городе и фотопаузы там, где это возможно.'},
      {time:'10:00',title:'Культурная остановка',body:'По желанию — Музей чамской скульптуры, если открыт, или другая подходящая точка. Билет входит в стоимость только при отдельном указании.'},
      {time:'11:00',title:'Ритм местного рынка',body:'Один из вариантов — рынок Хан: продукты, покупки и повседневная жизнь без обязательного посещения магазинов.'},
      {time:'12:00',title:'Кофе или возвращение в отель',body:'Завершаем в согласованном месте; напитки добавляются по запросу.'}],designHeading:'Чем отличается подход GoVietStay',design:['Логичный индивидуальный маршрут вместо спешки между разрозненными точками.','Пешие участки, транспорт и встреча по согласованию с вашей группой.','Прозрачный расчёт билетов и питания.','Английский язык гида по умолчанию; русский или итальянский — только после подтверждения.'],includedTitle:'Что можем организовать',intended:['Индивидуальная городская программа и предварительное обсуждение в WhatsApp.','Англоязычный гид и согласованная встреча/возвращение после подтверждения.','Время для прогулки, фотографий и отдыха.'],extraTitle:'Что уточнить до бронирования',extras:['Итоговая цена, число гостей, район встречи и автомобиль.','Билеты, еда, напитки и личные покупки.','Гид на другом языке, доступность маршрута, погода и отмена.'],faqTitle:'Частые вопросы об экскурсии по Данангу',faq:[
      {q:'Что входит в обзорную экскурсию по Данангу?',a:'Примерная программа объединяет мост Дракона, набережную, культурную остановку и местный рынок. Все точки и билеты уточняются до бронирования.'},
      {q:'Сколько длится экскурсия?',a:'Ориентир — 3–4 часа. Фактическая продолжительность зависит от отеля, передвижения и ваших пожеланий.'},
      {q:'Есть ли русскоязычный или италоязычный гид?',a:'По умолчанию гид говорит на английском. Напишите нам заранее, если нужен русский или итальянский; наличие гида и доплату подтвердим отдельно.'},
      {q:'Подойдёт ли маршрут семье?',a:'Частную программу можно скорректировать, но на некоторых остановках бывают ступени и людные места. Сообщите возраст детей и особенности передвижения.'},
      {q:'Входные билеты и обед включены?',a:'Не автоматически. Каждый билет, питание и трансфер указываются в окончательном письменном предложении.'},
      {q:'Сколько стоит индивидуальная экскурсия?',a:'Напишите дату, количество гостей, отель и язык гида. Рассчитаем цену после выбора транспорта и платных остановок.'}],ctaHeading:'Расскажите, что вам интересно.',ctaDescription:'Укажите даты, число гостей, отель, удобный темп и язык гида. Подготовим маршрут и понятный расчёт.',crossHeading:'Другие впечатления в Дананге',sourceNote:'Фотографии показывают город, но не являются снимками проведённой GoVietStay экскурсии.',creditsHeading:'Авторы фотографий и лицензии',back:'Путеводитель по Данангу',language:'Язык',photoAlt:['Мост Дракона в Дананге — возможная остановка на набережной','Рынок Хан сверху — иллюстрация местной жизни','Мраморные горы — возможное отдельное дополнение, требующее времени','Вечерние огни реки Хан в Дананге']
    },
    it:{
      title:'Tour privato della città di Da Nang | City Pulse | GoVietStay',description:'Scopri Da Nang con calma: Ponte del Drago, fiume Han, mercato e cultura. Tour privato con guida in inglese; italiano su richiesta previa conferma.',keywords:['tour privato Da Nang','tour della città Da Nang','cosa vedere a Da Nang','guida Da Nang','escursione privata Da Nang','Da Nang in mezza giornata'],h1:'City Pulse Discovery',hero:'Nelle cartoline ci sono i ponti. Ma com’è la vita della città fra una sponda e l’altra?',eyebrow:'GOVIETSTAY · TOUR PRIVATO DELLA CITTÀ',duration:'Indicativamente 3–4 ore · mezza giornata',guide:'La guida standard parla inglese. Per una guida in italiano o russo contattaci in anticipo: disponibilità ed eventuale supplemento da confermare.',notice:'Proposta gestita da GoVietStay e personalizzata per la vostra data. Tappe, trasporto, guida e prezzo vengono confermati prima della prenotazione.',price:'Prezzo su preventivo',priceDetail:'Dipende da partecipanti, mezzo, ingressi e data. Non pubblichiamo una tariffa inventata.',ask:'Richiedi un tour privato',storyQuestion:'E se il primo ricordo di Da Nang fosse una conversazione, non soltanto una foto?',story:'Il fiume Han è un punto di partenza naturale, ma fra i suoi ponti c’è una città da ascoltare: mercati, vie vissute, architettura e piccoli gesti quotidiani. City Pulse è una visita privata senza fretta, con tempo per domande, foto e una pausa caffè.',whoHeading:'Una visita pensata per voi',who:['Chi visita Da Nang per la prima volta e vuole orientarsi in poche ore.','Coppie e amici che preferiscono un’esperienza privata a un grande pullman.','Famiglie che desiderano adattare soste, pause e distanze a piedi.','Viaggiatori già stati qui che cercano cultura e vita di quartiere.'],routeHeading:'Un esempio di itinerario di mezza giornata',routeNote:'Gli orari sono indicativi: confermiamo aperture, traffico, prelievo e percorso per la vostra data.',stops:[
      {time:'08:30',title:'Incontro con la guida',body:'Raccogliamo interessi, preferenze e ritmo. Punto di incontro e mezzo saranno nel preventivo.'},
      {time:'09:00',title:'Ponte del Drago e fiume Han',body:'Passeggiata tra ponti e lungofiume per capire la città, con soste fotografiche dove accessibile.'},
      {time:'10:00',title:'Uno sguardo alla cultura',body:'Si può scegliere il Museo della Scultura Cham, se aperto, oppure un’altra tappa locale. Biglietti inclusi solo se indicati nella conferma.'},
      {time:'11:00',title:'Vita al mercato',body:'Il mercato Han è una possibilità per osservare prodotti e abitudini, senza obblighi di acquisto.'},
      {time:'12:00',title:'Caffè o rientro',body:'Terminiamo nel luogo concordato; eventuali consumazioni vengono quotate in anticipo.'}],designHeading:'Il nostro modo di esplorare',design:['Un percorso coerente e privato, non una corsa tra foto.','Camminate e trasporto adattati alle esigenze del gruppo.','Ingressi e pasti specificati con chiarezza nel preventivo.','Guida in inglese standard; italiano o russo soltanto dopo conferma.'],includedTitle:'Cosa possiamo organizzare',intended:['Programma cittadino privato e pianificazione via WhatsApp.','Guida in inglese e incontro/rientro concordati e confermati.','Soste culturali, passeggiata, foto e pause ragionevoli.'],extraTitle:'Da confermare prima della prenotazione',extras:['Tariffa finale, numero di ospiti, prelievo e veicolo.','Biglietti, pasti, bevande e acquisti personali.','Richiesta guida in italiano, accessibilità, meteo e cancellazione.'],faqTitle:'Domande pratiche sul tour di Da Nang',faq:[
      {q:'Cosa comprende il tour privato di Da Nang?',a:'La proposta collega il Ponte del Drago, il lungofiume, una tappa culturale e un mercato. Luoghi effettivi e biglietti verranno confermati prima di prenotare.'},
      {q:'Quanto dura?',a:'Indicativamente 3–4 ore. L’orario esatto dipende da hotel, spostamenti e ritmo desiderato.'},
      {q:'È prevista una guida in italiano?',a:'La guida inclusa di base parla inglese. Contattateci per richiedere un accompagnatore in italiano o russo; disponibilità ed eventuale supplemento devono essere confermati.'},
      {q:'È adatto alle famiglie?',a:'Il percorso si può adattare, ma alcune tappe presentano scalini o folla. Comunicate età e necessità di mobilità prima della conferma.'},
      {q:'Sono inclusi ingressi e pranzo?',a:'Non automaticamente. Il preventivo scritto indicherà chiaramente biglietti, pasti e trasferimenti inclusi.'},
      {q:'Quanto costa un tour privato?',a:'Scriveteci data, numero di partecipanti, hotel e lingua. Il prezzo dipende dal mezzo e dalle tappe richieste.'}],ctaHeading:'Raccontateci cosa vi incuriosisce.',ctaDescription:'Inviate date, partecipanti, hotel, esigenze di cammino e lingua. Prepariamo percorso e preventivo dettagliato.',crossHeading:'Altre esperienze a Da Nang',sourceNote:'Fotografie illustrative della destinazione, non di un tour GoVietStay già effettuato.',creditsHeading:'Crediti fotografici e licenze',back:'Guida di Da Nang',language:'Lingua',photoAlt:['Ponte del Drago a Da Nang, possibile tappa sul fiume','Mercato Han visto dall’alto, immagine di vita cittadina','Montagne di Marmo, eventuale estensione da concordare separatamente','Luci serali sul fiume Han a Da Nang']
    }
  }},
  {slug:'da-nang-local-flavors-explorer',name:'Local Flavors Explorer',photographs:[miQuang,miQuangTwo,hanMarket,bikes],copies:{
    en:{
      title:'Da Nang Private Food Tour | Local Flavors Explorer | GoVietStay',description:'Curious about what locals eat in Da Nang? Plan a private food-focused walk with regional tastings, stories and flexible dietary checks. English guide standard; quote on request.',keywords:['da nang food tour','da nang street food tour','private food tour da nang','what to eat in da nang','local food experience da nang','da nang food walking tour'],h1:'Local Flavors Explorer',hero:'One bowl can tell a story. How many Da Nang stories can you taste?',eyebrow:'GOVIETSTAY · PRIVATE DA NANG FOOD TOUR',duration:'Suggested 2.5–3 hours · flexible timing',guide:'English-speaking guide is standard. Russian or Italian only by prior request, subject to availability and a possible supplement.',notice:'We operate and tailor this food experience ourselves. The sample dishes and stops are ideas, not a fixed menu; we verify vendors and allergies before confirming your booking.',price:'Personalised food-tour quote',priceDetail:'Final price depends on guests, actual tastings, drinks, walking or vehicle transfers and date. Dish counts and portions are itemised in your quote.',ask:'Ask about my food tour',storyQuestion:'Could the best way to understand Da Nang be to sit down and eat?',story:'Forget a competition to visit the most stalls. We want every tasting to earn its place: why a bowl of mì Quảng feels different, how herbs change a bite, and why locals return to certain cafés. You set the pace and appetite; GoVietStay checks the kitchens and handles the details.',whoHeading:'For travellers led by appetite and curiosity',who:['Food lovers looking for regional dishes and context rather than a generic buffet.','Couples or small private groups who enjoy taking their time.','First-timers unsure what to order at a local stall.','Guests with dietary requests who are willing to discuss ingredients before the visit.'],routeHeading:'A possible tasting trail',routeNote:'Dish sequence and suggested times are not confirmed inclusions. The venue, portions, ingredients and number of tastings are agreed in the final quote.',stops:[
      {time:'16:30',title:'Meet and discover your taste profile',body:'Tell us your hotel, appetite, disliked ingredients and walking preference. Agree a suitable private route.'},
      {time:'17:00',title:'A bowl with a local identity',body:'Consider mì Quảng at a vetted shop and learn about noodles, broth and toppings. The actual dish depends on the agreed menu.'},
      {time:'17:40',title:'A second texture, a second story',body:'Explore a different local snack or bánh xèo where preparation and ingredients can be verified; no surprise dishes are promised.'},
      {time:'18:20',title:'Follow the neighbourhood',body:'Take a short market or street walk, looking at how residents choose food and what is genuinely open.'},
      {time:'19:00',title:'A final sip or dessert',body:'Choose a suitable drink or sweet ending when included in the quotation; return or end at the agreed spot.'}],designHeading:'Designed around real tastes, not inflated dish counts',design:['A private guide who explains ingredients and food culture in English.','We confirm exact dishes, portions and beverage inclusions in writing.','Optional walking or vehicle logistics adapted to your group.','No claims that every vendor can guarantee allergen-free preparation.'],includedTitle:'Our intended food experience',intended:['Private food planning and an English-speaking guide after confirmation.','Selected local tastings and a drink as itemised in the final quotation.','A comfortable sequence of stops with time to ask questions.'],extraTitle:'Details not automatically included',extras:['Any unspecified dish, alcohol, extra drinks or private-car upgrade.','Allergen-free kitchens, fixed number of tastings or guaranteed restaurants.','Russian/Italian guide, meeting zone, cancellation and rain options until confirmed.'],faqTitle:'Food-tour questions answered',faq:[
      {q:'What should I eat on a Da Nang food tour?',a:'Mì Quảng and bánh xèo are possible regional starting points. The exact menu, vendor and portion sizes are confirmed directly with you before booking.'},
      {q:'How many dishes are included?',a:'We do not advertise an unverified count. Your written quote will state the exact number of tastings, serving sizes and drinks.'},
      {q:'Is it a private walking food tour?',a:'Private is the intended format. Walking versus arranged vehicle transfers will be confirmed for your group and specified in the quote.'},
      {q:'Does a Russian or Italian guide come with the tour?',a:'No. The standard guide speaks English. Russian- and Italian-speaking guides can be requested in advance; availability and any supplement must be confirmed separately.'},
      {q:'Can vegetarian travellers or guests with allergies join?',a:'Tell us the requirements before you book. We can ask vendors about ingredients and preparation, but we cannot guarantee a kitchen free of allergens or any special menu without direct confirmation.'},
      {q:'What is the price of a Da Nang food tour?',a:'Share date, number of guests, hotel, dietary needs and preferred transport. We provide an itemised quote showing the dishes and services included.'}],ctaHeading:'What flavour are you curious about?',ctaDescription:'Message your date, guest count, dietary needs, hotel and preferred guide language. We will check actual vendors and send a clear quote.',crossHeading:'More ways to explore the city',sourceNote:'Licensed food and city photos illustrate the destination, not meals already served to GoVietStay guests.',creditsHeading:'Photo attribution and usage licences',back:'Da Nang food and travel guide',language:'Language',photoAlt:['Mì Quảng photographed in Da Nang, a possible regional tasting','Another bowl of mì Quảng showing local presentation','Han Market in Da Nang from above, illustrative possible neighbourhood context','Motorbikes on a Da Nang street wall, city illustration rather than a GoVietStay rider']
    },
    ru:{
      title:'Индивидуальный гастрономический тур по Данангу | GoVietStay',description:'Что попробовать в Дананге? Индивидуальная гастрономическая прогулка, блюда и истории местной кухни. Гид по умолчанию английский; русский по запросу.',keywords:['гастрономический тур Дананг','гастрономическая экскурсия по Данангу','что попробовать в Дананге','еда в Дананге','индивидуальный фуд тур Дананг','местная кухня Дананг'],h1:'Local Flavors Explorer',hero:'Может ли одна тарелка рассказать историю? Попробуем узнать.',eyebrow:'GOVIETSTAY · ИНДИВИДУАЛЬНЫЙ ГАСТРОНОМИЧЕСКИЙ ТУР',duration:'Ориентировочно 2,5–3 часа · время согласуем',guide:'Стандартный гид говорит на английском. Русский или итальянский — только по запросу, при наличии и с подтверждением возможной доплаты.',notice:'Мы сами организуем и адаптируем тур. Это пример блюд и остановок, не гарантированное меню. Заведения и запросы по питанию проверяем до бронирования.',price:'Индивидуальная цена по запросу',priceDetail:'Зависит от числа гостей, подтверждённых дегустаций, напитков, трансферов и даты. Количество и порции укажем в расчёте.',ask:'Узнать о гастрономическом туре',storyQuestion:'А что, если понять Дананг проще всего за столом?',story:'Не будем соревноваться в числе кафе. Каждая дегустация должна что-то открыть: чем особенна лапша ми куанг, зачем добавляют зелень и почему жители возвращаются к своим любимым местам. Вы выбираете темп и аппетит; GoVietStay проверяет кухни и детали.',whoHeading:'Для любознательных гурманов',who:['Тем, кто любит региональную кухню, а не случайный шведский стол.','Парам и небольшим компаниям, которым важен неспешный темп.','Новичкам, не знающим, что заказывать в местном кафе.','Гостям с особенностями питания, готовым заранее обсудить ингредиенты.'],routeHeading:'Пример маршрута со вкусом',routeNote:'Время и блюда — проект, а не обещанный состав тура. Места, порции, ингредиенты и количество дегустаций согласуются заранее.',stops:[
      {time:'16:30',title:'Встреча и знакомство с вашими вкусами',body:'Уточним отель, аппетит, нежелательные ингредиенты и удобство пеших прогулок.'},
      {time:'17:00',title:'Блюдо с местным характером',body:'Возможна дегустация ми куанг в проверенном кафе с рассказом о лапше, бульоне и добавках; итоговое меню согласуем.'},
      {time:'17:40',title:'Другой вкус, другая история',body:'Рассмотрим местную закуску или бань сео после проверки приготовления и состава.'},
      {time:'18:20',title:'Прогулка по кварталу',body:'Короткий маршрут у рынка или кафе, чтобы увидеть, как выбирают еду местные жители, с учётом часов работы.'},
      {time:'19:00',title:'Напиток или десерт',body:'Завершим подходящим напитком или сладостью, если они включены в расчёт; вернёмся в согласованное место.'}],designHeading:'Важнее вкус и история, чем громкое число блюд',design:['Личное сопровождение и объяснения кухни на английском.','Точный состав еды, напитков и порции укажем письменно.','Пешеходные участки либо транспорт обсуждаются заранее.','Не обещаем отсутствие аллергенов там, где кухня этого не подтверждает.'],includedTitle:'Что планируем организовать',intended:['Индивидуальная программа и англоязычный гид после подтверждения.','Местные дегустации и напиток в точном составе по расчёту.','Время на вопросы, прогулку и спокойную еду.'],extraTitle:'Что не включается автоматически',extras:['Неуказанные блюда, алкоголь, дополнительные напитки и автомобиль.','Гарантированное количество блюд и кухня без аллергенов.','Русский или итальянский гид, точное место встречи и правила отмены до согласования.'],faqTitle:'Вопросы о гастрономическом туре',faq:[
      {q:'Что попробовать в Дананге?',a:'Ми куанг и бань сео — возможные региональные блюда. Конкретные места, порции и меню заранее согласуем с вами.'},
      {q:'Сколько блюд входит в стоимость?',a:'Мы не заявляем неподтверждённое количество. В письменном расчёте будут все дегустации, размеры порций и напитки.'},
      {q:'Это индивидуальная пешая экскурсия?',a:'Мы готовим индивидуальный формат; пешие участки или трансферы согласуем и укажем в предложении.'},
      {q:'Русскоязычный гид включён?',a:'Нет. Стандартный гид говорит на английском. Русскоязычного или италоязычного можно запросить заранее; наличие и возможная доплата подтверждаются отдельно.'},
      {q:'Можно ли учесть вегетарианское питание и аллергию?',a:'Сообщите ограничения до бронирования. Мы уточним состав и приготовление у кафе, но не гарантируем кухню без аллергенов без прямого подтверждения.'},
      {q:'Сколько стоит гастрономический тур?',a:'Напишите дату, количество гостей, отель, особенности питания и транспорт. Вышлем расчёт с точным составом услуг.'}],ctaHeading:'Какой вкус вам особенно интересен?',ctaDescription:'Напишите даты, число гостей, требования к еде, отель и язык гида. Проверим реальные кафе и вышлем прозрачную стоимость.',crossHeading:'Другие способы открыть Дананг',sourceNote:'Фотографии показывают местную еду и город, а не блюда, уже поданные гостям GoVietStay.',creditsHeading:'Источники и лицензии фотографий',back:'Путеводитель по Данангу',language:'Язык',photoAlt:['Ми куанг, приготовленный в Дананге, пример местного блюда','Ещё один вариант подачи ми куанг','Рынок Хан сверху, иллюстрация городской жизни','Мотоциклы на улице Дананга, не транспорт этого тура']
    },
    it:{
      title:'Tour gastronomico privato a Da Nang | Local Flavors | GoVietStay',description:'Cosa mangiare a Da Nang? Esperienza gastronomica privata fra assaggi e racconti locali. Guida in inglese inclusa come opzione standard; italiano su richiesta.',keywords:['tour gastronomico Da Nang','street food Da Nang','tour privato gastronomico Da Nang','cosa mangiare a Da Nang','cucina locale Da Nang','food tour Da Nang'],h1:'Local Flavors Explorer',hero:'Un piatto può raccontare una storia. Quante storie riuscirete ad assaggiare?',eyebrow:'GOVIETSTAY · TOUR GASTRONOMICO PRIVATO',duration:'Circa 2,5–3 ore · orario da concordare',guide:'La guida standard parla inglese. Per italiano o russo contattateci in anticipo: disponibilità ed eventuale supplemento da confermare.',notice:'Organizziamo noi l’esperienza e la adattiamo a voi. Piatti e soste sono esempi, non un menù garantito; verifichiamo i locali prima di confermare.',price:'Preventivo gastronomico personalizzato',priceDetail:'Dipende da gruppo, assaggi reali, bevande, trasferimenti e data. Numero di piatti e porzioni saranno espliciti nel preventivo.',ask:'Richiedi il mio food tour',storyQuestion:'E se per capire Da Nang bastasse sedersi a tavola?',story:'Non è una gara a quanti locali si visitano. Vogliamo che ogni assaggio abbia una storia: cosa rende speciale il mì Quảng, come cambiano i sapori con le erbe e perché gli abitanti tornano in certi posti. Scegliete ritmo e appetito; GoVietStay controlla cucine e logistica.',whoHeading:'Per curiosi e buongustai',who:['Amanti della cucina regionale, oltre i soliti buffet.','Coppie e piccoli gruppi privati che preferiscono mangiare senza fretta.','Chi non sa cosa ordinare in un locale vietnamita.','Viaggiatori con esigenze alimentari da discutere prima della visita.'],routeHeading:'Un possibile percorso di assaggi',routeNote:'Orari, numero di piatti e locali sono indicativi. Menù, porzioni, ingredienti e bevande verranno confermati per iscritto.',stops:[
      {time:'16:30',title:'Incontro e preferenze di gusto',body:'Parliamo di hotel, appetito, ingredienti da evitare e comodità negli spostamenti.'},
      {time:'17:00',title:'Un piatto dalla forte identità',body:'Possibile mì Quảng in un locale controllato, con spiegazione di pasta, brodo e condimenti. Menù effettivo da concordare.'},
      {time:'17:40',title:'Un’altra consistenza, un’altra storia',body:'Valutiamo uno snack locale o bánh xèo solo dopo verifica di ricetta e ingredienti.'},
      {time:'18:20',title:'Il quartiere tra un assaggio e l’altro',body:'Breve passeggiata verso un mercato o una strada del cibo realmente aperta alla data scelta.'},
      {time:'19:00',title:'Un sorso o un dolce finale',body:'Bevanda o dessert se espressamente compresi; termine nel punto concordato.'}],designHeading:'Contano sapori veri, non numeri gonfiati',design:['Guida privata che spiega la cultura del cibo in inglese.','Piatti, porzioni e bevande definiti nel preventivo.','Spostamenti a piedi o con mezzo da scegliere insieme.','Non promettiamo cucine prive di allergeni senza verifica diretta.'],includedTitle:'Esperienza che possiamo preparare',intended:['Programma privato e guida in inglese dopo conferma.','Assaggi e bevanda esattamente elencati nel preventivo.','Tempo per domande, soste e assaggi con calma.'],extraTitle:'Non inclusi automaticamente',extras:['Piatti aggiuntivi, alcol, bevande extra o auto privata.','Numero fisso di assaggi e cucina garantita senza allergeni.','Guida in italiano/russo, punto d’incontro e cancellazione finché non concordati.'],faqTitle:'Domande sul food tour a Da Nang',faq:[
      {q:'Cosa mangiare durante un food tour a Da Nang?',a:'Mì Quảng e bánh xèo sono possibili punti di partenza. Menù, locali e porzioni reali saranno concordati prima di prenotare.'},
      {q:'Quanti piatti sono inclusi?',a:'Non dichiariamo numeri non verificati. Il preventivo scritto elenca tutti gli assaggi, le porzioni e le bevande.'},
      {q:'È un tour gastronomico privato a piedi?',a:'Puntiamo al formato privato; passeggiata e trasferimenti verranno concordati secondo le esigenze del gruppo.'},
      {q:'La guida parla italiano?',a:'La guida standard parla inglese. Una guida in italiano o russo si può richiedere in anticipo; disponibilità e possibile supplemento sono da confermare.'},
      {q:'È possibile richiedere piatti vegetariani o segnalare allergie?',a:'Comunicate le esigenze prima di prenotare. Chiederemo ai locali informazioni sugli ingredienti, ma non possiamo garantire cucine prive di allergeni senza conferma.'},
      {q:'Quanto costa un tour gastronomico privato?',a:'Scrivete data, partecipanti, hotel, dieta e preferenze di trasporto. Riceverete un preventivo dettagliato per assaggi e servizi.'}],ctaHeading:'Quale sapore vi incuriosisce?',ctaDescription:'Comunicate date, numero di ospiti, esigenze alimentari, hotel e lingua desiderata: controlleremo i locali e invieremo un preventivo trasparente.',crossHeading:'Altri modi di esplorare Da Nang',sourceNote:'Immagini autorizzate illustrative della città e del cibo, non foto di pasti serviti da GoVietStay.',creditsHeading:'Autori delle fotografie e licenze',back:'Guida gastronomica di Da Nang',language:'Lingua',photoAlt:['Mì Quảng fotografato a Da Nang, possibile assaggio locale','Un secondo piatto di mì Quảng in stile regionale','Mercato Han visto dall’alto, immagine di vita cittadina','Moto parcheggiate a Da Nang; non sono veicoli di questo tour']
    }
  }},
  {slug:'da-nang-in-a-day-private-tour',name:'Da Nang In A Day',photographs:[marble,hanMarket,miQuang,beach],copies:{
    en:{
      title:'Da Nang Full Day Private Tour | Da Nang In A Day | GoVietStay',description:'Plan one balanced private day in Da Nang: Marble Mountains, city life, a local lunch and coastal views. Sample itinerary, English guide standard, transparent quote on request.',keywords:['da nang full day tour','private full day tour da nang','da nang one day itinerary','da nang local experience','da nang private sightseeing day','what to do in da nang in one day'],h1:'Da Nang In A Day',hero:'Only one day in Da Nang? Make room for the moments between the landmarks.',eyebrow:'GOVIETSTAY · FULL-DAY PRIVATE DA NANG TOUR',duration:'Suggested full day · approximately 7–8 hours',guide:'English-speaking guide standard. Request Russian or Italian before booking; availability and any supplement require confirmation.',notice:'GoVietStay plans and operates this private day. This is a realistic suggested route, not a guaranteed checklist. Tickets, vehicle, meal, price and timing are fixed in your quote.',price:'Full-day private quote',priceDetail:'Price depends on group size, vehicle, confirmed admissions, meal arrangements and preferred language; we quote the complete package before payment.',ask:'Plan my one day in Da Nang',storyQuestion:'Can one day feel like more than a sprint between attractions?',story:'Begin where the stone hills meet the coast, find the pulse of the city and sit down to taste its food. The goal is not to tick every attraction on a map: it is one coherent day with enough time to look around, ask questions and take a breath.',whoHeading:'A day that fits the people travelling',who:['First-time visitors with one free day and no desire to navigate several separate bookings.','Couples who enjoy a balance of scenery, culture and lunch.','Families who prefer an agreed vehicle and planned breaks.','Friends who want to adjust the sights to their interests and energy.'],routeHeading:'Your possible day, from hills to city',routeNote:'An illustrative private itinerary. Marble Mountains have stairs and may not suit everyone; alternative stops, opening hours, admissions and driving times are checked before booking.',stops:[
      {time:'08:00',title:'Pickup and an early start near Marble Mountains',body:'Begin with the limestone hills when suitable. Agree access, steps, entrance fees and an alternative if the climb is not right for your group.'},
      {time:'10:15',title:'The everyday side of Da Nang',body:'Return toward the centre and consider Han Market or another open neighbourhood stop, learning how the city works between its famous landmarks.'},
      {time:'11:30',title:'A local lunch at a comfortable pace',body:'Choose a vetted restaurant and regional meal. Dish, dietary checks and whether lunch is included will be confirmed in the quote.'},
      {time:'13:00',title:'The river and its bridges',body:'Explore the Dragon Bridge and Han River area with time for photographs and context, not a rushed drive-by.'},
      {time:'14:30',title:'Choose a final coastal or coffee moment',body:'If weather and route allow, add a beach viewpoint or a relaxed café. Son Tra is only a separate longer option if travel times and access permit.'},
      {time:'15:30–16:00',title:'Return where we agreed',body:'Head back by private vehicle, with the final return time specified in your confirmed booking.'}],designHeading:'One carefully paced day',design:['A geographically sensible progression, with an early start for any hill walk.','Private transport and breaks shaped around your party.','A real lunch plan and ticket inclusions written out in the quote.','English-speaking guide by default, with Russian/Italian only by request.'],includedTitle:'We will organise after confirmation',intended:['Tailored full-day planning, English-speaking guide and agreed private vehicle.','Pickup and return within the agreed zone.','Selected sights and a lunch arrangement as specifically written in the final quote.'],extraTitle:'What is not promised automatically',extras:['All attraction tickets, unspecified meals and drinks or optional Son Tra extension.','Step-free access at Marble Mountains, a fixed weather outcome or an unrestricted route.','Russian/Italian guide, price or cancellation terms without written confirmation.'],faqTitle:'Planning Da Nang in one day',faq:[
      {q:'What can I see in Da Nang in one day?',a:'A realistic private day can combine Marble Mountains, a local city stop, lunch and the Han River, subject to conditions. We choose fewer stops if children, mobility or weather require it.'},
      {q:'Is this a full-day private tour?',a:'Yes, the intended service is a private, tailored day arranged by GoVietStay. We confirm the guide, vehicle, included services and exact timings before accepting a booking.'},
      {q:'Does the tour include Ba Na Hills or Hoi An?',a:'Not in this sample route. Ba Na Hills and Hoi An are separate substantial excursions; we can build a different itinerary if those are your priority.'},
      {q:'Is a Russian- or Italian-speaking guide included?',a:'No. The standard guide speaks English. Please contact us to request a Russian- or Italian-speaking guide; availability and any additional fee require separate confirmation.'},
      {q:'Is Marble Mountains suitable for older guests or children?',a:'Some routes require stairs and walking. Tell us ages and mobility needs, and we will discuss alternative stops and vehicle arrangements before confirmation.'},
      {q:'Are tickets, lunch and private car included in the price?',a:'We prepare one itemised written quote listing the agreed vehicle, each admission and lunch. No unlisted ticket or meal should be assumed included.'},
      {q:'How much does a full-day Da Nang private tour cost?',a:'Request a quote using your date, guests, hotel, mobility needs and language. We will price the actual itinerary instead of displaying an unverified starting fare.'}],ctaHeading:'One free day. Tell us what matters to you.',ctaDescription:'Send your date, guest count, hotel, ages, walking preferences and guide-language request. We will plan a sensible day and provide an itemised quote.',crossHeading:'More local experiences',sourceNote:'Destination photos are illustrative. They do not claim to show guests on this GoVietStay tour.',creditsHeading:'Image sources and licences',back:'Da Nang travel guide',language:'Language',photoAlt:['Marble Mountains, a potential early stop on the one-day Da Nang tour','Han Market seen from above, an example of daily city life','Mì Quảng, a possible regional lunch','Da Nang beach setting, a possible final coastal viewpoint']
    },
    ru:{
      title:'Дананг за один день: индивидуальная экскурсия | GoVietStay',description:'Дананг за день: Мраморные горы, местный рынок, обед и набережная. Индивидуальный маршрут с англоязычным гидом; русский по запросу.',keywords:['Дананг за один день','индивидуальная экскурсия Дананг на весь день','что посмотреть в Дананге за день','Мраморные горы Дананг экскурсия','частный тур Дананг','Дананг достопримечательности за 1 день'],h1:'Da Nang In A Day',hero:'В Дананге всего один день? Оставьте место не только для достопримечательностей.',eyebrow:'GOVIETSTAY · ИНДИВИДУАЛЬНЫЙ ТУР НА ВЕСЬ ДЕНЬ',duration:'Примерно 7–8 часов · полный день',guide:'Стандартное сопровождение — английский язык. Русский или итальянский гид — только по запросу; наличие и доплату согласуем отдельно.',notice:'GoVietStay самостоятельно организует индивидуальную программу. Ниже пример без гарантии всех остановок: билеты, автомобиль, обед, цена и время уточняются письменно.',price:'Стоимость — по индивидуальному расчёту',priceDetail:'Зависит от состава группы, автомобиля, подтверждённых билетов, обеда и языка. Итоговую стоимость сообщаем до оплаты.',ask:'Спланировать один день в Дананге',storyQuestion:'Может ли один день быть путешествием, а не гонкой по точкам?',story:'Начните там, где каменные горы встречаются с морем, затем узнайте повседневный город и попробуйте местную еду. Наша идея — разумный маршрут со временем на вопросы, фотографии и отдых, а не попытка объехать всё на карте.',whoHeading:'Программа для вашей компании',who:['Тем, кто впервые в Дананге и располагает одним свободным днём.','Парам, желающим соединить пейзажи, культуру и обед.','Семьям, которым нужны согласованный автомобиль и перерывы.','Друзьям, предпочитающим менять остановки по интересам.'],routeHeading:'Пример маршрута: от гор к городу',routeNote:'Время условное. На Мраморных горах есть лестницы: доступность, билеты, часы работы и альтернативы проверяем до бронирования.',stops:[
      {time:'08:00',title:'Встреча и ранний выезд к Мраморным горам',body:'Посетим горы, если пеший подъём подходит группе. Заранее согласуем лестницы, билеты и альтернативный маршрут.'},
      {time:'10:15',title:'Повседневный Дананг',body:'Вернёмся в центр: возможны рынок Хан и другие открытые местные точки без навязанных покупок.'},
      {time:'11:30',title:'Местный обед без спешки',body:'Подберём проверенное кафе и региональное блюдо; меню, питание и включение в стоимость уточним.'},
      {time:'13:00',title:'Река Хан и мосты',body:'Прогулка у моста Дракона и набережной, фото и истории вместо короткой остановки из окна.'},
      {time:'14:30',title:'Море или кофе по выбору',body:'По погоде и времени — пляжная панорама либо уютное кафе. Сон Ча возможен только отдельным расширением при достаточном времени.'},
      {time:'15:30–16:00',title:'Возвращение',body:'Вернёмся на согласованном автомобиле; конкретное время будет в подтверждении.'}],designHeading:'Один день с разумным темпом',design:['Логичная география, раннее время для посещения гор при подходящих условиях.','Индивидуальный транспорт и остановки по вашей компании.','Обед и входные билеты чётко прописаны в расчёте.','Англоязычный гид по умолчанию; русский и итальянский только по запросу.'],includedTitle:'Что организуем после подтверждения',intended:['Индивидуальная программа, англоязычный гид и согласованный частный автомобиль.','Встреча и возвращение в согласованном районе.','Экскурсионные точки и обед в точном составе по письменному предложению.'],extraTitle:'Что не гарантируется автоматически',extras:['Все билеты, неуказанная еда, напитки и дополнительный маршрут по Сон Ча.','Безлестничный доступ на Мраморных горах и фиксированный маршрут при непогоде.','Русский/итальянский гид, цена или условия отмены без подтверждения.'],faqTitle:'Вопросы: Дананг за один день',faq:[
      {q:'Что посмотреть в Дананге за один день?',a:'Можно совместить Мраморные горы, местный городской район, обед и реку Хан, если позволяют условия. Для детей и гостей с ограничениями программу сократим.'},
      {q:'Это индивидуальный тур на весь день?',a:'Да, мы планируем индивидуальный день. Гида, автомобиль, включённые услуги и время письменно подтверждаем до бронирования.'},
      {q:'Бана-Хиллс и Хойан включены?',a:'Нет, в этом примере их нет. Это отдельные большие экскурсии; можем составить другой маршрут, если они важнее.'},
      {q:'Русскоязычный гид входит в стоимость?',a:'Нет. По умолчанию гид говорит на английском. Русскоязычного или италоязычного можно запросить заранее; наличие и доплата подтверждаются отдельно.'},
      {q:'Мраморные горы подходят детям и пожилым?',a:'На некоторых маршрутах много ступеней. Сообщите возраст и ограничения подвижности; предложим альтернативы и проверим транспорт.'},
      {q:'Билеты, обед и машина включены?',a:'В окончательном расчёте будут перечислены согласованный автомобиль, все билеты и обед. Неуказанные услуги не считаются включёнными.'},
      {q:'Сколько стоит индивидуальный тур на день?',a:'Напишите дату, число гостей, отель, особенности передвижения и язык. Рассчитаем реальную программу, а не вымышленную минимальную цену.'}],ctaHeading:'Один день — расскажите, что для вас важнее.',ctaDescription:'Пришлите дату, гостей, отель, возраст детей, удобный темп и запрос на язык гида. Подготовим маршрут и подробную стоимость.',crossHeading:'Другие местные впечатления',sourceNote:'Фотографии иллюстрируют места, но не показывают гостей в туре GoVietStay.',creditsHeading:'Источники изображений и лицензии',back:'Путеводитель по Данангу',language:'Язык',photoAlt:['Мраморные горы — возможная первая остановка в Дананге','Рынок Хан сверху — городская жизнь','Ми куанг — возможный местный обед','Пляж Дананга — вариант завершения маршрута']
    },
    it:{
      title:'Da Nang in un giorno: tour privato completo | GoVietStay',description:'Un giorno a Da Nang: Montagne di Marmo, mercato, pranzo locale e fiume Han. Tour privato con guida in inglese; guida italiana su richiesta.',keywords:['Da Nang in un giorno','tour privato Da Nang intera giornata','cosa vedere a Da Nang in un giorno','Montagne di Marmo Da Nang','escursione privata Da Nang','itinerario un giorno Da Nang'],h1:'Da Nang In A Day',hero:'Avete soltanto un giorno? Lasciate spazio anche ai momenti fra le attrazioni.',eyebrow:'GOVIETSTAY · TOUR PRIVATO DI UN GIORNO',duration:'Indicativamente 7–8 ore · giornata intera',guide:'La guida standard parla inglese. Per italiano o russo contattateci prima: disponibilità e supplemento eventuale da confermare.',notice:'GoVietStay organizza direttamente la giornata privata. Questo è un percorso proposto, non una lista di tappe garantite: biglietti, mezzo, pranzo, prezzo e orari saranno concordati.',price:'Preventivo privato per la giornata',priceDetail:'Dipende da gruppo, mezzo, ingressi, pranzo e lingua. Forniamo un importo completo prima di richiedere il pagamento.',ask:'Organizza il mio giorno a Da Nang',storyQuestion:'Un giorno può essere un viaggio, invece di una corsa tra attrazioni?',story:'Dalle colline di pietra vicino alla costa al ritmo quotidiano del centro, fino a un piatto locale: proponiamo un itinerario coerente, non una collezione forzata di luoghi. Ci sarà spazio per domande, foto e pause.',whoHeading:'Una giornata costruita intorno a voi',who:['Chi visita Da Nang per la prima volta e ha un giorno libero.','Coppie alla ricerca di paesaggi, cultura e buon cibo.','Famiglie che desiderano trasporto privato e pause pianificate.','Amici che preferiscono scegliere tappe in base agli interessi.'],routeHeading:'Possibile itinerario: dalle colline alla città',routeNote:'Orari indicativi. Le Montagne di Marmo presentano scalini; aperture, biglietti, accessibilità e alternative saranno verificati prima di confermare.',stops:[
      {time:'08:00',title:'Partenza e Montagne di Marmo al mattino',body:'Visita se la salita è adatta al vostro gruppo. Concordiamo in anticipo gradini, ingressi ed eventuale alternativa.'},
      {time:'10:15',title:'La Da Nang quotidiana',body:'Ritorno verso il centro, con possibile mercato Han o una tappa di quartiere aperta, senza acquisti obbligati.'},
      {time:'11:30',title:'Pranzo locale con calma',body:'Scegliamo un ristorante verificato; piatto, esigenze alimentari e inclusione nel prezzo saranno confermati.'},
      {time:'13:00',title:'Fiume Han e ponti',body:'Passeggiata fra il Ponte del Drago e il lungofiume, con tempo per foto e spiegazioni.'},
      {time:'14:30',title:'Ultima sosta: costa o caffè',body:'Se meteo e tempi lo consentono, una veduta del mare o un caffè. Son Tra richiede un’estensione separata e una verifica dei tempi.'},
      {time:'15:30–16:00',title:'Rientro concordato',body:'Ritorno con mezzo privato; l’orario preciso sarà scritto nella conferma.'}],designHeading:'Una giornata equilibrata',design:['Sequenza geografica ragionevole, partenza presto per le colline se adatte.','Veicolo privato e pause commisurate al gruppo.','Pranzo e biglietti indicati chiaramente nel preventivo.','Guida in inglese di base; italiano o russo soltanto su richiesta.'],includedTitle:'Organizzazione dopo conferma',intended:['Itinerario su misura, guida in inglese e mezzo privato concordato.','Prelievo e ritorno nell’area confermata.','Attrazioni e pranzo esattamente elencati nel preventivo.' ],extraTitle:'Non garantiti automaticamente',extras:['Tutti i biglietti, pasti non indicati, bevande e deviazione su Son Tra.','Accesso senza gradini alle Montagne di Marmo o stesso programma con maltempo.','Guida in italiano/russo, prezzo e cancellazione prima della conferma.'],faqTitle:'Domande: Da Nang in un giorno',faq:[
      {q:'Cosa vedere a Da Nang in un giorno?',a:'Si possono combinare Montagne di Marmo, una tappa cittadina, pranzo e fiume Han se le condizioni lo permettono. Riduciamo le tappe secondo età, mobilità e meteo.'},
      {q:'È un tour privato di una giornata intera?',a:'Sì, proponiamo una giornata privata. Guida, veicolo, inclusioni e orari verranno confermati per iscritto prima di prenotare.'},
      {q:'Ba Na Hills o Hoi An sono inclusi?',a:'No, sono escursioni diverse e impegnative. Possiamo creare un altro programma se preferite queste mete.'},
      {q:'È inclusa la guida in italiano?',a:'No. La guida standard parla inglese. Contattateci per richiedere una guida in italiano o russo; disponibilità ed eventuale supplemento saranno confermati separatamente.'},
      {q:'Le Montagne di Marmo sono adatte a bambini o persone anziane?',a:'Alcuni tratti hanno molte scale. Comunicate età e necessità di mobilità per valutare tappe alternative.'},
      {q:'Biglietti, pranzo e auto privata sono inclusi?',a:'La conferma scritta specificherà veicolo, ingressi e pranzo effettivamente compresi; nessun servizio non elencato è incluso automaticamente.'},
      {q:'Quanto costa un tour privato completo?',a:'Indicate data, partecipanti, hotel, esigenze di mobilità e lingua. Prepareremo il prezzo per l’itinerario effettivo.'}],ctaHeading:'Un giorno libero. Che cosa conta di più per voi?',ctaDescription:'Mandate date, partecipanti, hotel, età, esigenze di cammino e lingua preferita. Prepariamo un piano equilibrato e il costo dettagliato.',crossHeading:'Altre esperienze locali',sourceNote:'Immagini illustrative delle destinazioni, non fotografie di ospiti in un tour GoVietStay.',creditsHeading:'Fonti delle immagini e licenze',back:'Guida di Da Nang',language:'Lingua',photoAlt:['Montagne di Marmo, possibile prima tappa a Da Nang','Mercato Han dall’alto, vita della città','Mì Quảng, possibile pranzo regionale','Spiaggia di Da Nang, possibile ultima sosta panoramica']
    }
  }}
];
export const findSignature = (slug:string) => signatureExperiences.find((experience)=>experience.slug===slug);
