// Editorial draft ONLY: not a confirmed bookable product. No sales, Offer markup,
// confirmed inclusions or indexing until owner verifies suppliers and costs.
export type NightLocale = 'en' | 'ru' | 'it';
export const NIGHT_SLUG = 'da-nang-night-bites-city-lights';
export const NIGHT_BASE = 'https://www.govietstay.com';
export const nightPath = (locale: NightLocale) => `${locale === 'en' ? '/travel' : `/${locale}`}/local-experiences/${NIGHT_SLUG}`;
export const priceReference = {
  researched: '2026-09-21',
  competitorDirectWithoutCruiseVnd: 950000,
  competitorDirectWithCruiseVnd: 1200000,
  proposedWithoutCruiseVnd: 890000,
  proposedWithCruiseVnd: 1090000,
  minimumGuests: 2,
  benchmark: 'https://aodairidertour.com/2017/12/12/da-nang-by-night-and-han-river-cruise/',
  // OTA packages and inclusions vary. Do NOT claim a universal lowest price.
} as const;

type Q = { q: string; a: string };
type Stop = { time: string; title: string; detail: string };
export type NightCopy = {
 title:string; description:string; keywords:string[]; kicker:string; h1:string; tagline:string;
 ribbon:string; priceLabel:string; noCruise:string; withCruise:string; priceCondition:string; duration:string; availability:string;
 ask:string; explore:string; introTitle:string; intro:string; whoTitle:string; who:string[];
 journeyTitle:string; journeyIntro:string; itinerary:Stop[]; inclusionsTitle:string; intended:string[]; excludedTitle:string; excluded:string[];
 cruiseTitle:string; cruiseText:string; differencesTitle:string; differences:string[];
 priceHeading:string; baseTitle:string; cruisePackageTitle:string; baseFeatures:string[]; cruiseFeatures:string[];
 finalPrice:string; safetyTitle:string; safety:string; faqTitle:string; faq:Q[];
 sourcePhoto:string; credit:string; planningCTA:string; ctaHint:string; language:string; back:string;
 truthTitle:string; truth:string; photoAlt:[string,string,string,string];
};

export const nightCopy: Record<NightLocale,NightCopy> = {
 en: {
  title:'Da Nang Night Food Tour & City Lights | Private Evening | GoVietStay',
  description:'Discover Dragon Bridge, Han River lights and a local dinner on a proposed private Da Nang night tour. Indicative prices from VND 890,000; optional cruise. Confirm availability.',
  keywords:['da nang night tour','da nang night food tour','things to do in da nang at night','private da nang evening tour','dragon bridge night tour','han river cruise da nang','da nang night market'],
  kicker:'GOVIETSTAY · PRIVATE LOCAL EXPERIENCES', h1:'Night Bites & City Lights',
  tagline:'Da Nang has another story after sunset. Follow the river, taste a local favourite and find the streets you might walk straight past on your own.',
  ribbon:'Preview itinerary · supplier and availability verification pending', priceLabel:'Indicative launch price / guest',
  noCruise:'City lights + local dinner', withCruise:'Add a Han River cruise',
  priceCondition:'Indicative planning prices for 2+ guests; not a confirmed offer. For solo travellers, families, different transport or holidays, request an exact written quote.',
  duration:'Approx. 3.5–4 hours · evening', availability:'English / Russian / Italian requested; guide availability to be confirmed',
  ask:'Ask for a tailored quote',explore:'Explore the evening',
  introTitle:'What happens to Da Nang when the sun goes down?',
  intro:'The bridges change colour. Food stalls become meeting places. The riverside fills with people out for an ordinary evening. Night Bites & City Lights is a proposed private, unhurried city-and-food route for travellers who want to understand what they are seeing — not race from photo stop to photo stop.',
  whoTitle:'An evening shaped around your curiosity',
  who:['Couples wanting city lights, local flavours and time together — without a crowded group.','First-time visitors who want a clear orientation to the Han River and Dragon Bridge.','Small private groups interested in a relaxed local dinner with a guide who can explain the food.','Families or mature travellers who prefer comfortable transport and a sensible walking pace; suitability checked individually.'],
  journeyTitle:'A possible evening, moment by moment',journeyIntro:'The times below are a suggested sequence, not a confirmed departure or a promise that every stop operates on your date. The final route will be adjusted for traffic, dinner, cruise schedules and weather.',
  itinerary:[
   {time:'18:00',title:'Start where you are staying',detail:'Proposed pickup in central Da Nang or the nearby beach area after confirmation. Meet the host, agree on walking comfort and choose the evening focus.'},
   {time:'18:20',title:'Find the river and its illuminated landmarks',detail:'Explore the Dragon Bridge and Love Bridge area, with time to see how the Han River connects the city. Exact photo stops depend on access and your pace.'},
   {time:'19:00',title:'One local dinner, with a story',detail:'Sit down for a proposed light regional meal such as mì Quảng or another verified local dish, plus a non-alcoholic drink. Restaurant and menu are confirmed before booking; dietary requests are checked directly.'},
   {time:'19:45',title:'A different rhythm beyond the postcard',detail:'Continue towards an open evening street, market or the APEC Park area. The chosen stop depends on what is genuinely open and comfortable on your date.'},
   {time:'20:15–21:15',title:'Your choice: city lights or river cruise',detail:'Base route: enjoy a riverside viewpoint and finish at a comfortable pace. Cruise route: board a confirmed Han River sailing and enjoy the skyline from the water; exact boarding and departure times replace this indicative slot.'},
   {time:'21:30–22:00',title:'Return without a rushed goodbye',detail:'Proposed hotel return after the chosen route. On Friday–Sunday we can investigate a view of the 21:00 Dragon Bridge show, but the cruise and the show may conflict; neither is guaranteed.'},
  ],
  inclusionsTitle:'What we plan to include',
  intended:['A private, tailor-made local evening itinerary and pre-trip WhatsApp planning.','An arranged city transfer/pickup and return, with vehicle type and pickup zone confirmed in writing.','One light local dinner and one non-alcoholic drink at a checked venue.','An actual available accompanying guide in the language confirmed on your booking.','Han River cruise ticket only in the cruise package, once the operator and sailing are verified.'],
  excludedTitle:'Not assumed to be included',
  excluded:['Extra food, alcohol, shopping, tips and personal expenses.','Unlisted attraction tickets, hotel pickups outside the agreed zone or private vehicle upgrades.','Dragon Bridge fire/water show, a specific cruise show, reserved views or a guaranteed sunset.','Travel insurance; cancellation terms and weather alternatives must be confirmed before payment.'],
  cruiseTitle:'The optional cruise changes the view — not the promise',
  cruiseText:'Cruise timings, vessel, seating, performances and pier may vary by operator and date. We only mark the boat ticket as included once a real sailing has been checked. On fire-show nights, we will discuss whether your priority is watching from land or taking the boat; doing both is not assured.',
  differencesTitle:'Designed for a different kind of traveller',
  differences:['A private pace that puts a comfortable conversation ahead of collecting checkpoints.','Food and local context explained in your requested language if a suitable guide is available.','One clearly priced base plan and one clearly differentiated optional cruise; no hidden automatic upgrades.','Practical alternatives for guests who prefer a vehicle instead of a motorbike.'],
  priceHeading:'Plan the experience, then confirm the price',baseTitle:'City lights & local dinner',cruisePackageTitle:'City lights, dinner & cruise',
  baseFeatures:['Suggested private evening route','Planned light local dinner + soft drink','Arranged pickup/return and guide subject to supplier confirmation','Cruise not included'],
  cruiseFeatures:['Everything proposed in the base version','A Han River cruise ticket subject to confirmed sailing','Boarding point and schedule provided in final booking','No guaranteed fire show or onboard performance'],
  finalPrice:'These are GoVietStay target prices, not bookable rates. We will confirm costs, guide language, transport, inclusions, deposit and cancellation policy in writing before accepting payment.',
  safetyTitle:'What if it rains or the bridge show changes?',
  safety:'We check weather, boat operations and the official event calendar close to departure. A covered stop, an adjusted road route or a rescheduled activity is discussed before confirmation. No motorbike ride is included in this proposed package by default.',
  faqTitle:'Answers before you plan your Da Nang evening',
  faq:[
   {q:'What is the price of this Da Nang private night tour?',a:'GoVietStay is considering an introductory rate of VND 890,000 per guest for the city-and-food route, or VND 1,090,000 with a Han River cruise, for groups of at least two. These are estimates until the itinerary, date and suppliers are confirmed in writing.'},
   {q:'Is the Han River cruise included?',a:'Only in the proposed cruise version, and only after a suitable boat and sailing are confirmed. The VND 890,000 draft base price does not include a cruise.'},
   {q:'Is the Dragon Bridge fire show guaranteed?',a:'No. Da Nang tourism lists the show around 21:00 on Friday, Saturday and Sunday, with possible schedule changes. The cruise sailing may not line up with the show. We check your actual travel date and agree on one priority.'},
   {q:'Is this suitable for couples, families or older travellers?',a:'The route is intended to be private and adaptable. Tell us guest ages, mobility needs and walking preferences; we will verify the vehicle, timing and suitability. We do not promise a motorbike ride.'},
   {q:'Can we request a Russian- or Italian-speaking guide?',a:'Yes, you may request English, Russian or Italian when enquiring. Actual guide availability and any language-related price difference must be checked before booking.'},
   {q:'What food is included, and can you accommodate allergies?',a:'One light dinner and a non-alcoholic drink are planned; restaurant, dish and serving size are not yet final. Please disclose dietary requirements so we can ask the venue. We cannot guarantee an allergen-free kitchen.'},
   {q:'What is there to do in Da Nang at night if it rains?',a:'An indoor dinner or a modified road route may work, but boat operations and outdoor stops can be affected. We will agree on an alternative or a rescheduling/cancellation option before payment.'},
  ],
  sourcePhoto:'Illustrative licensed destination photography; not photos of a completed GoVietStay tour.',credit:'Photo sources and licence details',
  planningCTA:'Tell us your date. We will make the night yours.',ctaHint:'Send travel date, number of guests, hotel, language and whether you prefer the river cruise. We will check real availability and provide a transparent final quote.',
  language:'Language',back:'Back to Da Nang travel guide',truthTitle:'Before you decide',truth:'This is a fully written preview of a new experience. The prices, guide and route have not yet been approved by GoVietStay operations. We do not accept a deposit on this page.',
  photoAlt:['Dragon Bridge glowing above the Han River in Da Nang after dark','A bowl of mì Quảng photographed in Da Nang, illustrative dinner inspiration','Evening lights reflected across the Han River in Da Nang','People strolling along the Han River walkway at night in Da Nang'],
 },
 ru: {
  title:'Вечерняя экскурсия по Данангу с ужином | Night Bites | GoVietStay',
  description:'Индивидуальный вечерний Дананг: мост Дракона, река Хан, местный ужин и круиз по желанию. Предварительно от 890 000 донгов; стоимость и наличие уточняются.',
  keywords:['вечерняя экскурсия по Данангу','Дананг ночью','гастрономическая экскурсия Дананг вечером','мост Дракона шоу','круиз по реке Хан','индивидуальная экскурсия Дананг','что посмотреть в Дананге вечером'],
  kicker:'GOVIETSTAY · ИНДИВИДУАЛЬНЫЕ ВПЕЧАТЛЕНИЯ',h1:'Night Bites & City Lights',
  tagline:'После заката Дананг рассказывает другую историю: огни над рекой, местный ужин и улочки, мимо которых легко пройти в одиночку.',
  ribbon:'Предварительная программа · проверка партнёров и наличия мест',priceLabel:'Предварительная цена запуска / человек',
  noCruise:'Вечерний город и местный ужин',withCruise:'С круизом по реке Хан',
  priceCondition:'Ориентировочная цена при группе от 2 человек; это ещё не подтверждённое предложение. Для одного гостя, семьи, праздников и другого транспорта подготовим отдельный расчёт.',
  duration:'Около 3,5–4 часов · вечер',availability:'Английский / русский / итальянский: наличие гида подтверждаем на дату',
  ask:'Запросить точную стоимость',explore:'Открыть вечерний маршрут',introTitle:'Каким становится Дананг после заката?',
  intro:'Мосты меняют цвет, уличные кафе заполняются местными жителями, а набережная живёт своей жизнью. Night Bites & City Lights — проект неспешного индивидуального вечера с местной едой: не гонка за фотографиями, а знакомство с атмосферой города.',
  whoTitle:'Вечер для тех, кто хочет увидеть больше',
  who:['Для пар: свет огней, местные вкусы и время вдвоём без большой группы.','Для гостей, впервые приехавших в Дананг и желающих понять, как устроен центр у реки Хан.','Для небольших компаний, которые хотят поужинать и услышать истории от сопровождающего.','Для семей и путешественников старшего возраста, предпочитающих удобный транспорт и посильную прогулку; детали проверяем индивидуально.'],
  journeyTitle:'Возможная программа по времени',journeyIntro:'Ниже проект маршрута, а не подтверждённое расписание. Время и остановки скорректируем с учётом погоды, дорожной ситуации, ресторана и рейса теплохода.',
  itinerary:[
   {time:'18:00',title:'Встреча у вашего отеля',detail:'Планируем встречу в центре Дананга или ближайшем пляжном районе после подтверждения. Уточним удобный темп и пожелания.'},
   {time:'18:20',title:'Подсвеченные мосты и берег реки',detail:'Район моста Дракона и моста Влюблённых, панорамы реки Хан и время для фотографий. Точные точки зависят от доступности.'},
   {time:'19:00',title:'Местный ужин с историей',detail:'Небольшой ужин, например ми куанг, или другое блюдо в проверенном кафе, плюс безалкогольный напиток. Меню и ограничения в питании согласуем до бронирования.'},
   {time:'19:45',title:'Жизнь города за пределами открыток',detail:'Прогулка по работающей вечерней улице, рынку либо в районе парка АТЭС. Остановку выбираем по реальным часам работы.'},
   {time:'20:15–21:15',title:'Выбор: огни города или речной круиз',detail:'Базовая версия — красивые виды с набережной. Версия с круизом — подтверждённый рейс по реке Хан. Реальное время отправления заменит предварительный слот.'},
   {time:'21:30–22:00',title:'Возвращение без спешки',detail:'Планируем возвращение в отель. По пятницам, субботам и воскресеньям проверим возможность увидеть шоу на мосту Дракона в 21:00, но круиз может совпасть с шоу.'},
  ],
  inclusionsTitle:'Что планируем включить',intended:['Индивидуальный маршрут и помощь в планировании через WhatsApp.','Организованный трансфер по городу с подтверждением машины и зоны встречи.','Один лёгкий местный ужин и один безалкогольный напиток в проверенном заведении.','Сопровождение гида на языке, который реально подтвердим в бронировании.','Билет на речной круиз только в версии с круизом после подтверждения рейса.'],
  excludedTitle:'Что не входит автоматически',excluded:['Дополнительные блюда, алкоголь, покупки, чаевые и личные расходы.','Неуказанные билеты, дальний трансфер и улучшение класса машины.','Гарантированное огненное шоу, выступление на борту, особое место для просмотра или закат.','Туристическая страховка; условия отмены и непогоды согласуем до оплаты.'],
  cruiseTitle:'Круиз — другой взгляд на город, но без ложных обещаний',
  cruiseText:'Отправление, судно, посадка и шоу на борту зависят от оператора и даты. Билет считается включённым только после подтверждения. В вечер шоу на мосту Дракона решим, что для вас важнее: наблюдение с берега или прогулка по воде; оба события одновременно не гарантируем.',
  differencesTitle:'Другой формат путешествия',differences:['Индивидуальный темп вместо спешки по стандартному списку точек.','Объяснение еды и городской жизни на выбранном языке при наличии подходящего гида.','Два понятных варианта: с круизом или без него, без скрытых дополнений.','Возможность удобного автомобиля вместо обязательной поездки на мотоцикле.'],
  priceHeading:'Выберите формат — мы подтвердим итоговую цену',baseTitle:'Вечерний город и местный ужин',cruisePackageTitle:'Вечерний город, ужин и круиз',
  baseFeatures:['Проект индивидуального вечернего маршрута','Планируемый лёгкий ужин и напиток','Встреча, обратный трансфер и гид после подтверждения поставщика','Круиз не включён'],
  cruiseFeatures:['Всё запланированное в базовой версии','Билет на подтверждённый круиз по реке Хан','Время и причал укажем в итоговом подтверждении','Шоу огня и выступления на борту не гарантируются'],
  finalPrice:'Это целевые цены GoVietStay, не открытые тарифы для бронирования. До оплаты письменно подтвердим партнёров, транспорт, язык, услуги, депозит и условия отмены.',
  safetyTitle:'Что делать, если дождь или изменение шоу?',safety:'Перед выездом проверим погоду, работу теплоходов и актуальную программу города. Возможны крытая остановка, изменение маршрута или перенос по согласованным условиям. По умолчанию поездка на мотоцикле не предусмотрена.',
  faqTitle:'Важные ответы перед вечерней прогулкой',
  faq:[
   {q:'Сколько стоит индивидуальная вечерняя экскурсия по Данангу?',a:'Рассматриваем стартовую цену 890 000 донгов с человека без круиза и 1 090 000 донгов с круизом для группы от двух гостей. Это предварительный расчёт: маршрут, дату и поставщиков подтвердим письменно до оплаты.'},
   {q:'Включён ли круиз по реке Хан?',a:'Только в проекте расширенного пакета после подтверждения рейса и мест. В базовую цену 890 000 донгов речная прогулка не входит.'},
   {q:'Увидим ли обязательно огненное шоу на мосту Дракона?',a:'Нет. Городской туристический портал указывает ориентировочно 21:00 по пятницам, субботам и воскресеньям, но расписание меняется. Рейс теплохода может совпасть с шоу; согласуем ваш приоритет.'},
   {q:'Подойдёт ли экскурсия для пары, семьи или пожилых гостей?',a:'Планируем индивидуальный маршрут. Сообщите возраст, ограничения по ходьбе и пожелания — проверим транспорт и условия. Мотоциклы не обещаем.'},
   {q:'Можно ли заказать русскоязычного или италоязычного гида?',a:'Вы можете запросить английский, русский или итальянский. Свободного гида и возможную разницу в цене проверим на конкретную дату.'},
   {q:'Какой ужин включён? Что делать при аллергии?',a:'Планируем один лёгкий местный ужин и безалкогольный напиток. Конкретное кафе, порции и меню ещё не утверждены. Проверим ингредиенты заранее, но не обещаем кухню без аллергенов.'},
   {q:'Что посмотреть вечером в Дананге, если идёт дождь?',a:'Иногда можно заменить открытую прогулку ужином в помещении или изменить поездку. Круиз может быть отменён по погоде; вариант замены или переноса согласуем до оплаты.'},
  ],
  sourcePhoto:'Лицензированные фотографии города для иллюстрации; это не фотографии проведённой экскурсии GoVietStay.',credit:'Авторы фотографий и лицензии',
  planningCTA:'Напишите даты — мы составим ваш вечер.',ctaHint:'Сообщите дату, число гостей, отель, язык и нужен ли круиз. Мы уточним наличие мест и отправим окончательную прозрачную стоимость.',
  language:'Язык',back:'Путеводитель по Данангу',truthTitle:'Перед принятием решения',truth:'Это готовый черновик новой экскурсии. Цена, маршрут и наличие гида пока не утверждены операционным отделом. Мы не принимаем предоплату через эту страницу.',
  photoAlt:['Подсвеченный мост Дракона над рекой Хан в вечернем Дананге','Миска лапши ми куанг в Дананге — иллюстрация блюда','Отражения вечерних огней на реке Хан в Дананге','Вечерняя прогулочная зона набережной реки Хан'],
 },
 it: {
  title:'Da Nang di sera: tour privato, cena e luci | GoVietStay',
  description:'Scopri Da Nang di sera: Ponte del Drago, fiume Han, cena locale e crociera facoltativa. Prezzo indicativo da 890.000 VND, disponibilità e servizi da confermare.',
  keywords:['Da Nang di sera','tour serale privato Da Nang','cosa fare a Da Nang la sera','tour gastronomico serale Da Nang','Ponte del Drago spettacolo','crociera fiume Han Da Nang','mercato notturno Da Nang'],
  kicker:'GOVIETSTAY · ESPERIENZE LOCALI PRIVATE',h1:'Night Bites & City Lights',
  tagline:'Dopo il tramonto Da Nang racconta un’altra storia: riflessi sul fiume, una cena locale e strade che da soli potresti non notare.',
  ribbon:'Programma in anteprima · fornitori e disponibilità da verificare',priceLabel:'Prezzo indicativo di lancio / persona',
  noCruise:'Luci della città e cena locale',withCruise:'Con crociera sul fiume Han',
  priceCondition:'Prezzi indicativi per almeno 2 partecipanti, non ancora prenotabili. Per una persona, famiglie, festivi o altro mezzo prepareremo un preventivo scritto.',
  duration:'Circa 3,5–4 ore · sera',availability:'Inglese / russo / italiano su richiesta, disponibilità guida da confermare',
  ask:'Richiedi preventivo personalizzato',explore:'Scopri il percorso',introTitle:'Che cosa succede a Da Nang quando cala il sole?',
  intro:'I ponti cambiano colore, i locali diventano punti d’incontro e il lungofiume si anima. Night Bites & City Lights è la nostra proposta privata e senza fretta, pensata per capire la città attraverso l’atmosfera e il cibo, non per accumulare soltanto fotografie.',
  whoTitle:'Una serata per persone curiose',who:['Coppie in cerca di scorci luminosi, sapori locali e tempo insieme, lontano dai grandi gruppi.','Chi arriva per la prima volta e vuole orientarsi fra Ponte del Drago e fiume Han.','Piccoli gruppi privati che preferiscono cenare con calma e scoprire le storie dietro i piatti.','Famiglie e viaggiatori maturi che desiderano un mezzo comodo e camminate ragionevoli; idoneità valutata caso per caso.'],
  journeyTitle:'Un possibile itinerario, tappa dopo tappa',journeyIntro:'Gli orari descrivono soltanto la proposta. L’itinerario effettivo dipenderà da traffico, meteo, apertura dei locali e partenze della crociera.',
  itinerary:[
   {time:'18:00',title:'Incontro presso il vostro alloggio',detail:'Prelievo proposto nel centro di Da Nang o nella vicina zona balneare, previa conferma. Concordiamo interessi, capacità di camminare e ritmo.'},
   {time:'18:20',title:'Il fiume e i ponti illuminati',detail:'Area del Ponte del Drago e del Ponte dell’Amore, con soste fotografiche e racconti. I punti esatti saranno scelti in base all’accessibilità.'},
   {time:'19:00',title:'Una cena locale con una storia',detail:'Proposta di pasto leggero, per esempio mì Quảng, oppure un altro piatto presso un locale verificato, con bevanda analcolica. Menù e richieste alimentari da confermare.'},
   {time:'19:45',title:'Oltre le classiche cartoline',detail:'Passeggiata in una strada serale effettivamente aperta, in un mercato o nella zona del parco APEC. La sosta dipende dagli orari reali.'},
   {time:'20:15–21:15',title:'La scelta: luci dalla riva o crociera',detail:'Versione base: un bel punto sul lungofiume. Versione crociera: imbarco su una partenza confermata. L’orario reale della nave sostituirà quello orientativo.'},
   {time:'21:30–22:00',title:'Rientro senza fretta',detail:'Ritorno previsto in hotel. Venerdì, sabato e domenica valuteremo lo spettacolo del Ponte del Drago delle 21:00, ma potrebbe coincidere con la navigazione.'},
  ],
  inclusionsTitle:'Servizi che prevediamo di includere',intended:['Programma serale privato personalizzato e organizzazione via WhatsApp.','Trasferimento urbano all’andata e al ritorno, con mezzo e zona di prelievo confermati per iscritto.','Una cena locale leggera e una bevanda analcolica in un locale verificato.','Accompagnamento nella lingua realmente confermata nella prenotazione.','Biglietto per la crociera soltanto nella versione con crociera, dopo verifica dell’operatore.'],
  excludedTitle:'Servizi non automaticamente inclusi',excluded:['Piatti aggiuntivi, alcolici, acquisti, mance e spese personali.','Ingressi non elencati, trasferimenti lontani e upgrade del veicolo.','Spettacolo del fuoco garantito, spettacolo di bordo, posto riservato o tramonto assicurato.','Assicurazione di viaggio; politica meteo e cancellazione da concordare prima di pagare.'],
  cruiseTitle:'La crociera cambia la prospettiva, non le promesse',
  cruiseText:'Orari, nave, imbarco e spettacoli cambiano per operatore e giorno. Il biglietto sarà incluso solo dopo la conferma effettiva. Nelle sere dello spettacolo del Ponte del Drago sceglieremo la priorità fra la riva e il battello; non garantiamo entrambi.',
  differencesTitle:'Un modo diverso di esplorare',differences:['Ritmo privato e dialogo, non una corsa fra tappe fotografiche.','Cultura gastronomica nella lingua richiesta, se disponibile una guida adatta.','Due formule trasparenti con e senza crociera, senza supplementi automatici nascosti.','Possibilità di mezzo comodo anziché obbligo di spostarsi in moto.'],
  priceHeading:'Scegli la formula; poi confermiamo il prezzo',baseTitle:'Luci della città e cena locale',cruisePackageTitle:'Luci, cena e crociera sul fiume',
  baseFeatures:['Progetto di itinerario serale privato','Cena leggera e bevanda analcolica previste','Prelievo, rientro e guida previa conferma dei fornitori','Crociera esclusa'],
  cruiseFeatures:['Tutto il programma previsto nella formula base','Biglietto crociera previa verifica della partenza','Molo e orario nella conferma definitiva','Spettacolo del fuoco e show a bordo non garantiti'],
  finalPrice:'Questi sono prezzi-obiettivo GoVietStay, non tariffe prenotabili. Prima del pagamento confermeremo per iscritto servizi, fornitori, mezzo, lingua, acconto e condizioni di cancellazione.',
  safetyTitle:'E se piove o cambia l’orario dello spettacolo?',safety:'Controlliamo meteo, operatività delle navi e calendario ufficiale prima della partenza. Potremo discutere una sosta al coperto, un percorso modificato o uno spostamento della data. Non è previsto automaticamente alcun tour in moto.',
  faqTitle:'Risposte utili prima di organizzare la serata',
  faq:[
   {q:'Quanto costa un tour serale privato a Da Nang?',a:'GoVietStay sta valutando 890.000 VND a persona senza crociera oppure 1.090.000 VND con crociera, per almeno due partecipanti. Sono cifre indicative: data, percorso e fornitori verranno confermati per iscritto prima del pagamento.'},
   {q:'La crociera sul fiume Han è inclusa?',a:'Soltanto nella proposta con crociera e dopo conferma della partenza e dei posti. Non è compresa nel prezzo base indicativo di 890.000 VND.'},
   {q:'Lo spettacolo del fuoco del Ponte del Drago è garantito?',a:'No. Il portale turistico cittadino segnala le 21:00 di venerdì, sabato e domenica, ma il calendario può cambiare. La crociera potrebbe coincidere con lo spettacolo; concordiamo una priorità.'},
   {q:'È adatto a coppie, famiglie o viaggiatori maturi?',a:'Pensiamo a un’esperienza privata e flessibile. Comunicate età, mobilità e preferenze; verificheremo mezzo e tempi. Nessuna escursione in moto è promessa.'},
   {q:'È possibile avere una guida in italiano o russo?',a:'Sì, potete richiedere italiano, russo o inglese. Disponibilità effettiva ed eventuale differenza di prezzo saranno verificate prima della prenotazione.'},
   {q:'Che cosa prevede la cena? Potete gestire allergie?',a:'Progettiamo una cena locale leggera con una bevanda analcolica. Locale, piatto e porzioni non sono ancora definiti. Verificheremo gli ingredienti, senza garantire una cucina priva di allergeni.'},
   {q:'Cosa fare a Da Nang di sera se piove?',a:'Una cena al coperto o un percorso stradale diverso potrebbero essere possibili; le uscite in barca possono subire cancellazioni. Concorderemo alternative e regole di rinvio prima di pagare.'},
  ],
  sourcePhoto:'Foto della destinazione con licenza verificata; non raffigurano un tour GoVietStay realmente svolto.',credit:'Fonti fotografiche e licenze',
  planningCTA:'Indicaci la data: la serata prenderà forma intorno a te.',ctaHint:'Scrivi data, partecipanti, hotel, lingua e preferenza per la crociera. Verificheremo la disponibilità e invieremo il preventivo definitivo.',
  language:'Lingua',back:'Guida di Da Nang',truthTitle:'Prima di decidere',truth:'Questa pagina presenta una proposta completa ma ancora in verifica. Prezzi, itinerario e guida non sono stati approvati operativamente. Non accettiamo acconti tramite questa pagina.',
  photoAlt:['Ponte del Drago illuminato sul fiume Han a Da Nang','Una ciotola di mì Quảng fotografata a Da Nang, immagine illustrativa','Riflessi delle luci notturne sul fiume Han a Da Nang','Passeggiata lungo il fiume Han di sera a Da Nang'],
 },
};
