import type { PhuQuocSeoPageData } from "../components/phu-quoc-seo/PhuQuocSeoPage";

const commonRelated = [
  { label: "Phu Quoc Private Tour", href: "/travel/phu-quoc-private-tour", text: "Flexible private routes with hotel pickup and local support." },
  { label: "Phu Quoc Snorkeling", href: "/travel/phu-quoc-snorkeling", text: "South-island reefs, sea conditions and tour styles." },
  { label: "Sunset Town Phu Quoc", href: "/travel/phu-quoc-sunset-town", text: "Plan the south-island evening, Kiss Bridge and shows." },
  { label: "Where to Stay in Phu Quoc", href: "/travel/where-to-stay-phu-quoc", text: "Choose the right base before you book the hotel." },
];

export const phuQuocSeoPages: Record<string, PhuQuocSeoPageData> = {
  "phu-quoc-private-tour": {
    slug: "phu-quoc-private-tour",
    keyword: "Phu Quoc private tour",
    metaTitle: "Phu Quoc Private Tour: Flexible Local Itineraries | GoVietStay",
    metaDescription: "Plan a Phu Quoc private tour around your hotel, pace and interests. Compare south island, north island, snorkeling, Sunset Town and family-friendly private routes.",
    eyebrow: "PHU QUOC PRIVATE TOUR · LOCAL OPERATOR",
    title: "Your Phu Quoc day,",
    titleAccent: "built around you.",
    lead: "Private car, flexible timing and a route designed around what your group actually wants to see — with GoVietStay local support before, during and after the trip.",
    status: "10 SEPTEMBER 2026 · Private routes reviewed for 2026–2027 season",
    chips: ["Private vehicle", "Flexible pace", "Hotel pickup", "Family friendly", "English support"],
    quickTitle: "A private tour is useful when flexibility matters more than the cheapest seat.",
    quickIntro: "Choose private when your hotel location, children, mobility, photography time or mixed interests make a fixed group schedule inconvenient.",
    quickCards: [
      { badge: "Best for first trip", title: "South Island + Sunset", text: "Beaches, viewpoints, cultural stops and a late-afternoon finish in Sunset Town." },
      { badge: "Nature", title: "North Island", text: "Rach Vem, quieter northern scenery and optional Grand World / Ganh Dau area." },
      { badge: "Sea day", title: "Private snorkeling", text: "A private boat or speedboat day when you want more control over pacing and stops." },
    ],
    sections: [
      {
        id: "private-vs-join",
        eyebrow: "CHOOSING THE FORMAT",
        title: "Private tour vs join-in tour",
        table: {
          headers: ["What matters", "Private tour", "Join-in tour"],
          rows: [
            ["Start time", "More flexible", "Fixed pickup window"],
            ["Route", "Can be tailored within practical limits", "Pre-set program"],
            ["Children / seniors", "Easier to slow down or rest", "Group pace"],
            ["Photo / beach time", "More control", "Time is shared with the group"],
            ["Price", "Quoted for your group", "Usually lower per person"],
          ],
        },
      },
      {
        id: "route-ideas",
        eyebrow: "ROUTE IDEAS",
        title: "Four practical private-tour styles",
        cards: [
          { title: "South Island", text: "Ho Quoc Pagoda, beaches, local stops and Sunset Town. Good for a first-time overview without a boat day." },
          { title: "North Island", text: "Rach Vem / Starfish Beach season, countryside and north-island attractions. Best when road and weather conditions are good." },
          { title: "Family day", text: "Fewer stops, later start, longer meal break and a child-friendly attraction chosen around age and energy." },
          { title: "Sunset evening", text: "Start later and focus on Sunset Town, Kiss Bridge, dinner and the current show schedule." },
        ],
      },
      {
        id: "what-is-included",
        eyebrow: "BEFORE YOU PAY",
        title: "What GoVietStay confirms in a private quote",
        bullets: [
          "Vehicle type and hotel pickup area.",
          "Guide language if a guide is requested.",
          "Entrance tickets that are included versus paid directly.",
          "Boat / snorkeling arrangement if the route includes the sea.",
          "Child age or height rules for ticketed attractions.",
          "Holiday, remote pickup or late-return surcharges if any.",
          "A clear cancellation / weather policy for weather-dependent activities.",
        ],
        note: "Private tours do not use one public fixed price because the correct total depends on group size, vehicle, route, guide, ticket package and hotel location.",
      },
      {
        id: "build-route",
        eyebrow: "HOW TO PLAN",
        title: "Send five details and we can build the day",
        bullets: [
          "Travel date.",
          "Number of adults and children, including children's ages.",
          "Hotel name or area.",
          "Your two or three must-see places.",
          "Preferred pace: easy, balanced or packed.",
        ],
      },
    ],
    faqs: [
      { q: "Can a Phu Quoc private tour start later than a group tour?", a: "Usually yes. The start time can be planned around the route, attraction opening times and sunset or show schedules." },
      { q: "Is a private guide always required?", a: "No. Some travelers only need a private car and driver, while others prefer an English-speaking guide for explanation and coordination." },
      { q: "Can we combine snorkeling and Sunset Town in one day?", a: "Often yes, but sea conditions, boat return time and the evening show schedule need to be checked for your date." },
      { q: "Do you publish one fixed private-tour price?", a: "No. GoVietStay confirms a private quote based on group size, route, vehicle, guide, tickets and hotel area." },
    ],
    whatsappKeyword: "PHU QUOC PRIVATE TOUR",
    whatsappIntro: "I want a private Phu Quoc itinerary and quote.",
    related: commonRelated,
  },

  "phu-quoc-snorkeling": {
    slug: "phu-quoc-snorkeling",
    keyword: "Phu Quoc snorkeling",
    metaTitle: "Phu Quoc Snorkeling: Best Islands, Season & Tour Tips | GoVietStay",
    metaDescription: "A practical Phu Quoc snorkeling guide: south-island reefs, Gam Ghi, May Rut, Mong Tay, dry-season conditions, speedboats, private trips and coral-safe tips.",
    eyebrow: "PHU QUOC SNORKELING · SOUTH ISLANDS",
    title: "Snorkel Phu Quoc",
    titleAccent: "without guessing the sea.",
    lead: "The best snorkeling day is not just the prettiest photo. It depends on wind, visibility, current conditions, the boat format and how much time your group wants in the water.",
    status: "10 SEPTEMBER 2026 · Dry-season planning updated",
    chips: ["Gam Ghi", "May Rut", "Mong Tay", "Speedboat", "Private option", "Weather dependent"],
    quickTitle: "South-island snorkeling is the classic choice for first-time visitors.",
    quickIntro: "The An Thoi island group gives operators multiple reef and beach options, allowing the exact stop order to change when sea conditions require it.",
    quickCards: [
      { badge: "Reef focus", title: "Gam Ghi area", text: "Known for reef snorkeling; the exact usable spot depends on current conditions." },
      { badge: "Beach + swim", title: "May Rut", text: "Often used for beach time, swimming, photos and a relaxed island stop." },
      { badge: "Flexible format", title: "Private speedboat", text: "Best when you want more control over pace, family breaks or photography time." },
    ],
    sections: [
      {
        id: "best-time",
        eyebrow: "SEASON",
        title: "Best time for Phu Quoc snorkeling",
        intro: "The dry season, roughly November to April, usually brings calmer sea and better underwater visibility. Conditions still change day by day.",
        bullets: [
          "Do not book only from a weather icon; wind and sea state matter more for a boat day.",
          "The operator may change the island order or reef stop for safety and visibility.",
          "During rough conditions, a responsible operator may postpone or cancel.",
        ],
      },
      {
        id: "tour-styles",
        eyebrow: "TOUR FORMAT",
        title: "Join-in, small group or private?",
        table: {
          headers: ["Format", "Best for", "Trade-off"],
          rows: [
            ["Join-in", "Budget and first-time visitors", "Fixed timing and shared pace"],
            ["Small group", "More space and easier coordination", "Still follows a shared route"],
            ["Private speedboat", "Families, couples, flexible timing", "Higher total cost"],
          ],
        },
      },
      {
        id: "safety",
        eyebrow: "WATER SAFETY",
        title: "What matters more than the photo",
        bullets: [
          "Use a life jacket if you are not a confident swimmer.",
          "Tell the guide before entering the water if you are a weak swimmer or have a relevant limitation.",
          "Stay inside the guide's recommended area and return when conditions change.",
          "Children should be supervised directly by their own adult even when crew are present.",
          "Do not stand on, kick, break or remove coral.",
        ],
      },
      {
        id: "what-to-bring",
        eyebrow: "PACKING",
        title: "Bring less, but bring the right things",
        bullets: [
          "Swimwear and a dry change of clothes.",
          "Reef-conscious sun protection, hat and light cover-up.",
          "Waterproof phone pouch if you use one reliably.",
          "Motion-sickness preparation if you know you are sensitive to speedboats.",
          "A small towel if the operator does not provide one.",
        ],
      },
    ],
    faqs: [
      { q: "What is the best month for snorkeling in Phu Quoc?", a: "The dry season from about November to April is generally the easiest period, but the final decision should follow current sea conditions." },
      { q: "Can non-swimmers join a snorkeling tour?", a: "Many can join the boat day, but entering the water depends on the operator, equipment, sea conditions and the guest's comfort. Tell the operator in advance." },
      { q: "Which Phu Quoc islands are popular for snorkeling?", a: "South-island routes commonly use areas around Gam Ghi, May Rut and Mong Tay, with exact stops adjusted to conditions." },
      { q: "Is a private speedboat worth it?", a: "It can be worth it for families, couples or groups that value flexible pacing and fewer compromises over the lowest price per person." },
    ],
    whatsappKeyword: "PHU QUOC SNORKELING",
    whatsappIntro: "I want help choosing a snorkeling tour for my travel date.",
    sources: [
      { label: "Vinpearl travel guide — Phu Quoc snorkeling", href: "https://vinpearl.com/en/phu-quoc-snorkeling-a-noteworthy-experience", note: "Overview of popular snorkeling areas and dry-season conditions." },
    ],
    related: [
      ...commonRelated,
      { label: "Phu Quoc Tours", href: "/tours/phu-quoc", text: "Compare current GoVietStay Phu Quoc tour options." },
    ],
  },

  "phu-quoc-sunset-town": {
    slug: "phu-quoc-sunset-town",
    keyword: "Phu Quoc Sunset Town",
    metaTitle: "Phu Quoc Sunset Town: What to Do, Shows & Best Time | GoVietStay",
    metaDescription: "Plan Sunset Town Phu Quoc: Kiss Bridge, evening shows, sunset timing, dining, Hon Thom cable car combinations and practical south-island itinerary tips.",
    eyebrow: "SUNSET TOWN · SOUTH PHU QUOC",
    title: "Sunset Town is best",
    titleAccent: "planned backwards from sunset.",
    lead: "Arrive too early and the evening feels long. Arrive too late and you miss the best light. Build the visit around sunset, Kiss Bridge, dinner and the current show schedule.",
    status: "10 SEPTEMBER 2026 · 2026 evening attractions reviewed",
    chips: ["Kiss Bridge", "Kiss of the Sea", "Symphony of the Sea", "Sunset", "South Island"],
    quickTitle: "For most travelers, late afternoon into evening is the sweet spot.",
    quickIntro: "Sunset Town is not one single attraction. It is a south-island entertainment district where bridges, waterfront streets, restaurants and shows work best as one timed evening.",
    quickCards: [
      { badge: "Golden hour", title: "Arrive before sunset", text: "Walk the streets, choose viewpoints and reach Kiss Bridge without rushing." },
      { badge: "After dark", title: "Check the show calendar", text: "Kiss of the Sea and Symphony of the Sea are major evening draws, but operating schedules can change." },
      { badge: "Full south day", title: "Combine with Hon Thom", text: "A cable-car / island day can finish in Sunset Town if the return timing leaves enough margin." },
    ],
    sections: [
      {
        id: "timing",
        eyebrow: "TIMING",
        title: "A practical Sunset Town evening flow",
        table: {
          headers: ["Time block", "What to do"],
          rows: [
            ["Late afternoon", "Arrive, walk the Mediterranean-style streets and choose a sunset viewpoint"],
            ["Sunset", "Kiss Bridge / waterfront photos and slow exploration"],
            ["Early evening", "Dinner or drinks near the show area"],
            ["Night", "Watch the current scheduled show(s) if operating"],
          ],
        },
        note: "Exact sunset and show times vary by date. Check the official operator schedule on the day you visit.",
      },
      {
        id: "highlights",
        eyebrow: "HIGHLIGHTS",
        title: "What travelers actually come for",
        cards: [
          { title: "Kiss Bridge", text: "The signature seafront bridge and one of the strongest sunset photo locations in south Phu Quoc." },
          { title: "Kiss of the Sea", text: "A large outdoor multimedia performance using water, light, laser, fire, music and fireworks." },
          { title: "Symphony of the Sea", text: "A high-energy water-sports, laser and fireworks production presented in Sunset Town Bay during its operating season." },
          { title: "Sunset Bazaar / waterfront", text: "Dining, shopping and evening atmosphere around the core Sunset Town area." },
        ],
      },
      {
        id: "combine",
        eyebrow: "COMBINATIONS",
        title: "What to combine with Sunset Town",
        bullets: [
          "Hon Thom cable car and Aquatopia earlier in the day.",
          "A south-island sightseeing route with beaches and Ho Quoc Pagoda.",
          "A snorkeling / island-hopping day, only if the boat returns with enough buffer.",
          "A private late-start route focused mainly on sunset, dinner and shows.",
        ],
      },
      {
        id: "mistakes",
        eyebrow: "AVOID THESE",
        title: "Three easy mistakes",
        bullets: [
          "Assuming every show runs every night at the same time.",
          "Booking a boat tour with a late return and a show ticket with no transfer buffer.",
          "Treating Sunset Town as a 30-minute photo stop when your group actually wants dinner and a show.",
        ],
      },
    ],
    faqs: [
      { q: "What is the best time to visit Sunset Town Phu Quoc?", a: "Late afternoon through evening is usually best because you can see the town in daylight, catch sunset and stay for dinner or shows." },
      { q: "Is Kiss Bridge inside Sunset Town?", a: "Yes. Kiss Bridge is one of the central attractions in the Sunset Town / south-island entertainment area." },
      { q: "Can I combine Sunset Town and Hon Thom in one day?", a: "Yes, this is a common combination. Leave enough time after returning by cable car to walk, eat and reach any booked show." },
      { q: "Should I buy show tickets in advance?", a: "For fixed travel dates in busy periods, advance planning is sensible, but always verify the current operating calendar and ticket conditions." },
    ],
    whatsappKeyword: "SUNSET TOWN PHU QUOC",
    whatsappIntro: "I want help planning Sunset Town, Kiss Bridge and the evening shows.",
    sources: [
      { label: "Sun World Hon Thom — Sunset Town updates", href: "https://sunworld.vn/en/hon-thom/", note: "Operator information for Hon Thom / Sunset Town attractions and shows." },
      { label: "Sun World — Symphony of the Sea guide", href: "https://sunworld.vn/en/hon-thom/check-in/huong-dan-chi-tiet-cach-mua-ve-ban-giao-huong-dai-duong-12683", note: "2026 operator guide for the current season." },
    ],
    related: commonRelated,
  },

  "phu-quoc-rach-vem-starfish-beach": {
    slug: "phu-quoc-rach-vem-starfish-beach",
    keyword: "Phu Quoc Starfish Beach",
    metaTitle: "Phu Quoc Starfish Beach: Rach Vem Guide & Best Season | GoVietStay",
    metaDescription: "Visit Rach Vem Starfish Beach in north Phu Quoc: best season, road conditions, private car tips, responsible starfish viewing and what to combine nearby.",
    eyebrow: "RACH VEM · STARFISH BEACH · NORTH PHU QUOC",
    title: "See the starfish",
    titleAccent: "without harming them.",
    lead: "Rach Vem is a northern coastal village known for shallow water and seasonal starfish sightings. The right month, road condition and respectful behavior matter more than chasing one photo.",
    status: "10 SEPTEMBER 2026 · Dry-season access and starfish guidance reviewed",
    chips: ["Rach Vem", "North Phu Quoc", "November–April", "Private car", "Nature"],
    quickTitle: "November to April is generally the easiest period for Rach Vem.",
    quickIntro: "Dry-season weather usually gives calmer water, clearer visibility and easier road access. Starfish are wildlife, so sightings are never a guaranteed product.",
    quickCards: [
      { badge: "Best season", title: "November–April", text: "Typically clearer water, calmer conditions and easier access than the wetter months." },
      { badge: "From central Phu Quoc", title: "About 25 km north", text: "Allow enough time because the final approach can be slower than the map distance suggests." },
      { badge: "Wildlife first", title: "Keep starfish underwater", text: "Do not lift, stack or move starfish for photos. Observe them where they are." },
    ],
    sections: [
      {
        id: "what-is-rach-vem",
        eyebrow: "PLACE",
        title: "Rach Vem is more than a starfish photo stop",
        intro: "It is a northern fishing-village area with shallow coastal water, raft restaurants and a slower atmosphere than the main resort zones.",
        bullets: [
          "Plan it as a half-day or as part of a north-island private route.",
          "Morning can feel calmer and less rushed than arriving around lunch.",
          "Sea clarity and starfish location can change naturally.",
        ],
      },
      {
        id: "getting-there",
        eyebrow: "ACCESS",
        title: "Private car, taxi or scooter?",
        table: {
          headers: ["Option", "Best for", "What to know"],
          rows: [
            ["Private car", "Families / easy day", "Comfortable, flexible waiting time and easier north-island combinations"],
            ["Taxi", "Simple point-to-point visit", "Agree on return or waiting plan before going far north"],
            ["Scooter", "Confident riders in good conditions", "Final road sections can be rougher, especially in wet weather"],
          ],
        },
      },
      {
        id: "responsible",
        eyebrow: "RESPONSIBLE VISIT",
        title: "The starfish rule is simple: leave them in the water",
        bullets: [
          "Do not pick starfish up for photos.",
          "Do not move them into a group or arrange them on the sand.",
          "Avoid stepping on seagrass, coral, starfish or other marine life.",
          "Keep children close and explain the rule before entering the shallows.",
        ],
        note: "A responsible visit is better than a staged photo. Starfish visibility is seasonal and natural, not guaranteed.",
      },
      {
        id: "combine",
        eyebrow: "NORTH ISLAND",
        title: "What to combine with Rach Vem",
        bullets: [
          "Ganh Dau / north-coast viewpoints.",
          "Grand World for a later afternoon or evening.",
          "Vinpearl Safari or VinWonders on a separate day if you want a slower nature visit.",
          "A countryside / pepper-farm stop depending on the chosen route.",
        ],
      },
    ],
    faqs: [
      { q: "When is the best time for Starfish Beach Phu Quoc?", a: "November to April is generally the best period because the sea is often calmer and road access easier." },
      { q: "Is Starfish Beach the same as Sao Beach?", a: "No. Starfish Beach refers to the Rach Vem area in north Phu Quoc. Bai Sao is a different beach in the south." },
      { q: "Can I take a starfish out of the water for a photo?", a: "No. Keep starfish underwater and do not move or arrange them. Observe wildlife where it naturally is." },
      { q: "Is Rach Vem easy to reach in rainy season?", a: "It can be less comfortable because road and water conditions may worsen. Check the current conditions before committing to the trip." },
    ],
    whatsappKeyword: "RACH VEM STARFISH BEACH",
    whatsappIntro: "I want a north Phu Quoc route including Rach Vem / Starfish Beach.",
    sources: [
      { label: "Vinpearl travel guide — Rach Vem", href: "https://vinpearl.com/en/check-in-rach-vem-phu-quoc-in-the-starfish-season", note: "Season, location and access overview." },
      { label: "Vinpearl travel guide — Starfish Beach", href: "https://vinpearl.com/en/starfish-beach-phu-quoc-your-dream-like-vacation", note: "Dry-season and first-visit planning notes." },
    ],
    related: commonRelated,
  },

  "where-to-stay-phu-quoc": {
    slug: "where-to-stay-phu-quoc",
    keyword: "where to stay in Phu Quoc",
    metaTitle: "Where to Stay in Phu Quoc: Best Areas for Your Trip | GoVietStay",
    metaDescription: "Choose where to stay in Phu Quoc by travel style: Duong Dong / Long Beach, Ong Lang, Ganh Dau / Bai Dai, Sunset Town / An Thoi and Khem Beach.",
    eyebrow: "WHERE TO STAY IN PHU QUOC · AREA GUIDE",
    title: "Choose the area first.",
    titleAccent: "Then choose the hotel.",
    lead: "A beautiful resort in the wrong part of Phu Quoc can add hours of driving. Start with what you want to do, then pick the hotel zone that reduces unnecessary transfers.",
    status: "10 SEPTEMBER 2026 · Area strategy updated for 2026–2027 season",
    chips: ["Long Beach", "Duong Dong", "Ong Lang", "North Island", "Sunset Town", "Khem Beach"],
    quickTitle: "There is no single best area — only the best base for your itinerary.",
    quickIntro: "Phu Quoc is long enough that north, center and south feel like different travel bases. Your hotel location changes transfer time every day.",
    quickCards: [
      { badge: "First trip", title: "Duong Dong / Long Beach", text: "Central convenience, airport access, dining and an easy base for mixed sightseeing." },
      { badge: "Theme parks", title: "Ganh Dau / Bai Dai", text: "Best for VinWonders, Safari and the north-island entertainment cluster." },
      { badge: "South focus", title: "Sunset Town / An Thoi", text: "Best if Hon Thom, island hopping and south-island evenings dominate your plan." },
    ],
    sections: [
      {
        id: "area-comparison",
        eyebrow: "FAST COMPARISON",
        title: "Phu Quoc areas by travel style",
        table: {
          headers: ["Area", "Best for", "Main trade-off"],
          rows: [
            ["Duong Dong / Long Beach", "First timers, restaurants, mixed itinerary", "Not next door to north or far-south attractions"],
            ["Ong Lang", "Couples, quieter beach stay", "Fewer walk-out nightlife options"],
            ["Ganh Dau / Bai Dai", "VinWonders, Safari, resort families", "Longer trips to Sunset Town / An Thoi"],
            ["Sunset Town / An Thoi", "Hon Thom, island hopping, evening shows", "Longer trips to north attractions"],
            ["Khem Beach", "Resort relaxation, couples, families", "More resort-focused and less central for mixed touring"],
          ],
        },
      },
      {
        id: "long-beach",
        eyebrow: "CENTRAL / WEST COAST",
        title: "Duong Dong & Long Beach",
        intro: "This is usually the easiest first base when your itinerary mixes beaches, local dining, night-market time, airport transfers and day tours.",
        bullets: [
          "Good for travelers who do not want every meal inside a resort.",
          "Convenient for airport arrival and departure days.",
          "Balanced location when you have both north and south day trips.",
        ],
      },
      {
        id: "north",
        eyebrow: "NORTH ISLAND",
        title: "Ganh Dau / Bai Dai",
        intro: "Choose the north when VinWonders, Vinpearl Safari, Grand World and resort time are the core of the trip.",
        bullets: [
          "Excellent for families prioritizing major ticketed attractions.",
          "Easy to return to the hotel for rest when staying near the parks.",
          "Expect a longer transfer on south-island / Hon Thom days.",
        ],
      },
      {
        id: "south",
        eyebrow: "SOUTH ISLAND",
        title: "Sunset Town / An Thoi / Khem Beach",
        intro: "Choose the south when island hopping, Hon Thom cable car, Khem Beach and Sunset Town are more important than north-island theme parks.",
        bullets: [
          "Excellent for travelers planning multiple south-island days.",
          "Sunset Town gives strong evening entertainment without a long ride home.",
          "Khem Beach works well for a more resort-focused stay.",
        ],
      },
      {
        id: "split-stay",
        eyebrow: "SMART OPTION",
        title: "When a split stay makes sense",
        bullets: [
          "You have five or more nights and want both north attractions and south-island activities.",
          "You dislike long daily transfers more than you dislike changing hotels once.",
          "You are combining a family theme-park stay with a couple / beach-focused second half.",
        ],
        note: "A split stay is not automatically better. For a short 3–4 night trip, one well-chosen base is often simpler.",
      },
    ],
    faqs: [
      { q: "Where should first-time visitors stay in Phu Quoc?", a: "Duong Dong / Long Beach is often the easiest all-round base because it balances airport access, dining and day trips." },
      { q: "Where should families stay for VinWonders and Safari?", a: "Ganh Dau / Bai Dai in the north is the most convenient zone when those attractions are the main priority." },
      { q: "Where should I stay for Sunset Town and Hon Thom?", a: "Sunset Town / An Thoi or nearby south-island resort areas reduce transfer time for Hon Thom and evening shows." },
      { q: "Should I split my Phu Quoc stay between north and south?", a: "It can be useful for longer trips with strong north and south priorities, but short trips are often easier from one balanced base." },
    ],
    whatsappKeyword: "WHERE TO STAY PHU QUOC",
    whatsappIntro: "I want help choosing the best Phu Quoc hotel area for my itinerary.",
    sources: [
      { label: "Vinpearl travel guide — Phu Quoc itinerary", href: "https://vinpearl.com/en/phu-quoc-itinerary", note: "Destination-area context for north, west coast and south-island planning." },
    ],
    related: commonRelated,
  },

  "phu-quoc-vinwonders-vs-safari": {
    slug: "phu-quoc-vinwonders-vs-safari",
    keyword: "VinWonders vs Safari Phu Quoc",
    metaTitle: "VinWonders vs Safari Phu Quoc: Which One Should You Choose? | GoVietStay",
    metaDescription: "Compare VinWonders Phu Quoc vs Vinpearl Safari: rides, aquarium, water park, wildlife, opening times, family fit and whether to do both in one day.",
    eyebrow: "VINWONDERS VS VINPEARL SAFARI · PHU QUOC",
    title: "Theme park or wildlife?",
    titleAccent: "Choose by energy, not hype.",
    lead: "VinWonders and Vinpearl Safari are close to each other in north Phu Quoc, but they are very different days. One is built around rides, themed worlds and shows; the other around animals and a semi-wild safari experience.",
    status: "10 SEPTEMBER 2026 · Official 2026 operating information checked",
    chips: ["VinWonders", "Vinpearl Safari", "Families", "North Phu Quoc", "One-day plan"],
    quickTitle: "Choose VinWonders for entertainment. Choose Safari for animals and a slower pace.",
    quickIntro: "If your family has enough time, both are worth considering. If you only have one day, match the attraction to the children's ages and your group's energy level.",
    quickCards: [
      { badge: "Rides + shows", title: "VinWonders", text: "Large theme park with themed zones, aquarium, water park, rides and an evening show program." },
      { badge: "Animals", title: "Vinpearl Safari", text: "Open-zoo and semi-wild areas, safari-bus experience, animal programs and family activities." },
      { badge: "Do both?", title: "Possible, but long", text: "Safari first is logical because it closes earlier; combining both can be tiring for younger children." },
    ],
    sections: [
      {
        id: "comparison",
        eyebrow: "SIDE BY SIDE",
        title: "VinWonders vs Safari Phu Quoc",
        table: {
          headers: ["Question", "VinWonders", "Vinpearl Safari"],
          rows: [
            ["Main experience", "Theme park, rides, aquarium, water park, shows", "Wildlife, open zoo, safari-bus area, animal programs"],
            ["Best for", "Kids who love rides / active entertainment", "Animal lovers, younger children, mixed-age families"],
            ["Typical pace", "High-energy full day", "Slower half-day to most of a day"],
            ["2026 operator hours", "09:00–19:30 daily", "09:00–16:00 daily"],
            ["Stay area", "North Phu Quoc / Ganh Dau", "North Phu Quoc / Ganh Dau"],
          ],
        },
        note: "Operating hours and individual show times can change. Recheck the official operator website before your visit.",
      },
      {
        id: "choose",
        eyebrow: "WHO SHOULD PICK WHAT",
        title: "Choose by the people in your group",
        cards: [
          { title: "Young children", text: "Safari can be easier because the day is more observation-based and less dependent on height rules for rides." },
          { title: "Older kids / teens", text: "VinWonders usually wins when rides, water attractions and a high-energy day are the priority." },
          { title: "Grandparents + children", text: "Safari often creates a more shared experience across age groups, with fewer ride-related limitations." },
          { title: "One big entertainment day", text: "VinWonders offers more variety from morning into evening if your group has the stamina." },
        ],
      },
      {
        id: "both-one-day",
        eyebrow: "ONE-DAY COMBO",
        title: "Can you do Safari and VinWonders in one day?",
        intro: "Yes, but it should be treated as a long, selective day rather than a complete visit to both.",
        bullets: [
          "Start with Safari because its published operating day ends earlier.",
          "Choose the Safari highlights instead of trying to see every corner.",
          "Move to VinWonders after lunch / early afternoon.",
          "Prioritize only the VinWonders zones your group cares about most.",
          "Young children may enjoy two separate days much more than a rushed combo.",
        ],
      },
      {
        id: "planning",
        eyebrow: "PLANNING",
        title: "Hotel location changes the experience",
        bullets: [
          "Staying in Ganh Dau / Bai Dai makes park days much easier.",
          "From central or south Phu Quoc, factor in return transfer time after a long day.",
          "If you plan Sunset Town on the same trip, avoid stacking north and far-south attractions into one day.",
        ],
      },
    ],
    faqs: [
      { q: "Which is better, VinWonders or Safari Phu Quoc?", a: "VinWonders is better for rides, themed entertainment and a full high-energy day. Safari is better for wildlife, younger children and a calmer mixed-age experience." },
      { q: "Can I visit VinWonders and Safari on the same day?", a: "Yes, but it is a long day. Visit Safari first because it closes earlier, then choose only priority zones at VinWonders." },
      { q: "What are the 2026 opening hours?", a: "The operator currently lists VinWonders at 09:00–19:30 daily and Vinpearl Safari at 09:00–16:00 daily. Recheck before visiting." },
      { q: "Where should I stay for both parks?", a: "The Ganh Dau / Bai Dai area in north Phu Quoc is the most convenient base for repeated visits to VinWonders, Safari and nearby attractions." },
    ],
    whatsappKeyword: "VINWONDERS VS SAFARI",
    whatsappIntro: "I want help choosing or planning VinWonders and Vinpearl Safari Phu Quoc.",
    sources: [
      { label: "VinWonders Phu Quoc — official 2026 opening-hours guide", href: "https://vinwonders.com/en/wonderpedia/news/vinwonders-phu-quoc-opening-hours/", note: "Operator-listed hours and zone schedules." },
      { label: "Vinpearl Safari Phu Quoc — official website", href: "https://vinwonders.com/en/vinpearl-safari-phu-quoc/", note: "Operator information for Safari hours and experiences." },
    ],
    related: [
      { label: "Where to Stay in Phu Quoc", href: "/travel/where-to-stay-phu-quoc", text: "Choose a north-island base if the parks are a major priority." },
      { label: "Rach Vem Starfish Beach", href: "/travel/phu-quoc-rach-vem-starfish-beach", text: "A slower nature-focused day in north Phu Quoc." },
      { label: "Phu Quoc Private Tour", href: "/travel/phu-quoc-private-tour", text: "Build a flexible north-island transfer and sightseeing route." },
      { label: "Phu Quoc Tours", href: "/tours/phu-quoc", text: "See current GoVietStay Phu Quoc tour options." },
    ],
  },
};
