export type VietnamSeoPage = {
  slug: string;
  type: "product" | "combo" | "private" | "guide";
  destination: string;
  priceKey: string | null;
  depositPercent: number;
  title: string;
  h1: string;
  description: string;
  hero: string;
  focus: string;
  updated: string;
};

export const vietnamSeoPages: VietnamSeoPage[] = [
  {
    "slug": "tour-ba-na-hills",
    "type": "product",
    "destination": "Đà Nẵng",
    "priceKey": "bana",
    "depositPercent": 20,
    "title": "Tour Bà Nà Hills 2026 từ Đà Nẵng | GoVietStay",
    "h1": "Tour Bà Nà Hills từ Đà Nẵng: đi gọn một ngày, biết rõ chi phí trước",
    "description": "Nếu không muốn tự lo vé, xe và giờ đón, đây là cách đơn giản nhất. Chỉ cần gửi ngày đi, số người và khách sạn, GoVietStay sẽ kiểm tra rồi báo lại rõ ràng.",
    "hero": "Nếu không muốn tự lo vé, xe và giờ đón, đây là cách đơn giản nhất. Chỉ cần gửi ngày đi, số người và khách sạn, GoVietStay sẽ kiểm tra rồi báo lại rõ ràng.",
    "focus": "Bà Nà Hills, trẻ em theo chiều cao, tour ghép, tour riêng gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-cu-lao-cham",
    "type": "product",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": "cham",
    "depositPercent": 20,
    "title": "Tour Cù Lao Chàm 2026 | Cano, snorkeling | GoVietStay",
    "h1": "Tour Cù Lao Chàm: một ngày đi biển, cano và snorkeling",
    "description": "Cù Lao Chàm đẹp nhất khi biển êm. GoVietStay sẽ kiểm tra tình hình sát ngày để bạn đỡ phải đoán xem tour có chạy hay không.",
    "hero": "Cù Lao Chàm đẹp nhất khi biển êm. GoVietStay sẽ kiểm tra tình hình sát ngày để bạn đỡ phải đoán xem tour có chạy hay không.",
    "focus": "Cano, snorkeling, thời tiết, gia đình, tour riêng",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-hoi-an-rung-dua",
    "type": "product",
    "destination": "Hội An",
    "priceKey": "hoian",
    "depositPercent": 20,
    "title": "Tour Hội An Rừng Dừa 2026 | GoVietStay",
    "h1": "Tour Hội An + Rừng Dừa: đi buổi chiều, tối ngắm phố đèn lồng",
    "description": "Đi Rừng Dừa trước rồi vào phố cổ lúc trời dịu nắng là lịch khá dễ chịu. Bạn vừa có trải nghiệm thuyền thúng, vừa có thời gian đi bộ Hội An vào buổi tối.",
    "hero": "Đi Rừng Dừa trước rồi vào phố cổ lúc trời dịu nắng là lịch khá dễ chịu. Bạn vừa có trải nghiệm thuyền thúng, vừa có thời gian đi bộ Hội An vào buổi tối.",
    "focus": "Rừng Dừa, thuyền thúng, Hội An buổi tối, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-hue-tu-da-nang",
    "type": "product",
    "destination": "Huế",
    "priceKey": "hue",
    "depositPercent": 20,
    "title": "Tour Huế từ Đà Nẵng 2026 | GoVietStay",
    "h1": "Tour Huế từ Đà Nẵng: một ngày vừa đủ để cảm nhận cố đô",
    "description": "Huế không hợp kiểu chạy thật nhiều điểm. Lịch nên vừa sức, có thời gian xem Đại Nội, ăn trưa và nghỉ một chút trước khi về Đà Nẵng.",
    "hero": "Huế không hợp kiểu chạy thật nhiều điểm. Lịch nên vừa sức, có thời gian xem Đại Nội, ăn trưa và nghỉ một chút trước khi về Đà Nẵng.",
    "focus": "Đại Nội, di sản, xe riêng, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "don-san-bay-da-nang",
    "type": "product",
    "destination": "Đà Nẵng",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Đón sân bay Đà Nẵng 2026 | GoVietStay",
    "h1": "Đón sân bay Đà Nẵng: gửi chuyến bay, GoVietStay lo xe",
    "description": "Chỉ cần gửi số chuyến bay, số người, số vali và tên khách sạn. GoVietStay sẽ chọn loại xe phù hợp để bạn không phải lo xe chật hay thiếu chỗ hành lý.",
    "hero": "Chỉ cần gửi số chuyến bay, số người, số vali và tên khách sạn. GoVietStay sẽ chọn loại xe phù hợp để bạn không phải lo xe chật hay thiếu chỗ hành lý.",
    "focus": "Sân bay Đà Nẵng, khách sạn, Hội An, xe riêng",
    "updated": "2026-08-26"
  },
  {
    "slug": "thue-xe-da-nang-hoi-an",
    "type": "product",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Thuê xe Đà Nẵng Hội An 2026 | GoVietStay",
    "h1": "Thuê xe Đà Nẵng – Hội An: đi giờ nào, dừng đâu, mình thống nhất trước",
    "description": "Nếu đi cùng gia đình, có nhiều hành lý hoặc muốn ghé thêm một điểm trên đường, xe riêng sẽ thoải mái hơn. Bạn gửi lịch, GoVietStay báo xe và giá trước.",
    "hero": "Nếu đi cùng gia đình, có nhiều hành lý hoặc muốn ghé thêm một điểm trên đường, xe riêng sẽ thoải mái hơn. Bạn gửi lịch, GoVietStay báo xe và giá trước.",
    "focus": "Xe riêng, hành lý, gia đình, không ghép khách",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-3-dao-phu-quoc",
    "type": "product",
    "destination": "Phú Quốc",
    "priceKey": "pq3",
    "depositPercent": 20,
    "title": "Tour 3 đảo Phú Quốc 2026 | GoVietStay",
    "h1": "Tour 3 đảo Phú Quốc: dành một ngày trọn vẹn cho biển",
    "description": "Nếu đã chọn đi tour đảo thì nên dành hẳn một ngày cho cano, snorkeling và nghỉ trên biển. Lịch thực tế sẽ được điều chỉnh theo điều kiện trong ngày.",
    "hero": "Nếu đã chọn đi tour đảo thì nên dành hẳn một ngày cho cano, snorkeling và nghỉ trên biển. Lịch thực tế sẽ được điều chỉnh theo điều kiện trong ngày.",
    "focus": "3 đảo, cano, snorkeling, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-4-dao-phu-quoc-cap-treo",
    "type": "product",
    "destination": "Phú Quốc",
    "priceKey": "pq4",
    "depositPercent": 20,
    "title": "Tour 4 đảo Phú Quốc + cáp treo 2026 | GoVietStay",
    "h1": "Tour 4 đảo Phú Quốc + cáp treo Hòn Thơm: xem kỹ quyền lợi trước khi đặt",
    "description": "Gói này có khá nhiều hạng mục nên điều quan trọng là biết vé cáp treo, cano, ăn uống và điểm đón đã gồm những gì. GoVietStay sẽ xác nhận lại trước khi nhận cọc.",
    "hero": "Gói này có khá nhiều hạng mục nên điều quan trọng là biết vé cáp treo, cano, ăn uống và điểm đón đã gồm những gì. GoVietStay sẽ xác nhận lại trước khi nhận cọc.",
    "focus": "4 đảo, Hòn Thơm, cáp treo, quyền lợi rõ",
    "updated": "2026-08-26"
  },
  {
    "slug": "don-san-bay-phu-quoc",
    "type": "product",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Đón sân bay Phú Quốc 2026 | GoVietStay",
    "h1": "Đón sân bay Phú Quốc: báo đúng resort để chọn xe và tính giá",
    "description": "Phú Quốc khá rộng, resort ở nam đảo, trung tâm hay bắc đảo sẽ có quãng đường khác nhau. Gửi đúng tên resort là cách nhanh nhất để có giá chính xác.",
    "hero": "Phú Quốc khá rộng, resort ở nam đảo, trung tâm hay bắc đảo sẽ có quãng đường khác nhau. Gửi đúng tên resort là cách nhanh nhất để có giá chính xác.",
    "focus": "Sân bay Phú Quốc, resort, xe riêng, không cần cọc với transfer tiêu chuẩn",
    "updated": "2026-08-26"
  },
  {
    "slug": "thue-xe-phu-quoc",
    "type": "product",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Thuê xe Phú Quốc 2026 | GoVietStay",
    "h1": "Thuê xe Phú Quốc: đi theo lịch của gia đình, không chạy vòng cả đảo",
    "description": "Bạn muốn đi nam đảo, bắc đảo hay chỉ đi ăn và ngắm hoàng hôn? GoVietStay sẽ gom điểm theo khu vực để bớt thời gian ngồi xe.",
    "hero": "Bạn muốn đi nam đảo, bắc đảo hay chỉ đi ăn và ngắm hoàng hôn? GoVietStay sẽ gom điểm theo khu vực để bớt thời gian ngồi xe.",
    "focus": "Xe riêng, resort, nam đảo, bắc đảo",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-da-nang-3-tour",
    "type": "combo",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": "comboDN3",
    "depositPercent": 20,
    "title": "Combo Đà Nẵng 3 tour 2026 | GoVietStay",
    "h1": "Combo Đà Nẵng 3 tour: Bà Nà + Hội An + Cù Lao Chàm",
    "description": "Nếu đã xác định đi cả ba điểm, gom chung một booking sẽ đỡ phải hỏi giá và sắp lịch nhiều lần. GoVietStay cũng dễ hỗ trợ đổi thứ tự khi thời tiết thay đổi.",
    "hero": "Nếu đã xác định đi cả ba điểm, gom chung một booking sẽ đỡ phải hỏi giá và sắp lịch nhiều lần. GoVietStay cũng dễ hỗ trợ đổi thứ tự khi thời tiết thay đổi.",
    "focus": "Bà Nà, Hội An, Cù Lao Chàm, combo tiết kiệm",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-da-nang-3n2d",
    "type": "combo",
    "destination": "Đà Nẵng",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Đà Nẵng 3N2Đ 2026 | GoVietStay",
    "h1": "Combo Đà Nẵng 3N2Đ: bạn lo vé máy bay, phần ở Đà Nẵng để GoVietStay lo",
    "description": "Bạn có thể tự săn vé máy bay, còn xe sân bay, khách sạn và tour thì ghép theo nhu cầu. Cách này linh hoạt hơn một gói cố định từ đầu đến cuối.",
    "hero": "Bạn có thể tự săn vé máy bay, còn xe sân bay, khách sạn và tour thì ghép theo nhu cầu. Cách này linh hoạt hơn một gói cố định từ đầu đến cuối.",
    "focus": "Land combo, sân bay, tour, khách sạn tùy chọn",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-da-nang-4n3d",
    "type": "combo",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Đà Nẵng 4N3Đ 2026 | GoVietStay",
    "h1": "Combo Đà Nẵng 4N3Đ: đủ thời gian đi chơi mà không cần chạy quá nhiều",
    "description": "Bốn ngày ba đêm đủ để đi Bà Nà, Hội An và thêm một trải nghiệm nữa. Quan trọng là chừa khoảng nghỉ để cả chuyến đi không biến thành chạy từ điểm này sang điểm khác.",
    "hero": "Bốn ngày ba đêm đủ để đi Bà Nà, Hội An và thêm một trải nghiệm nữa. Quan trọng là chừa khoảng nghỉ để cả chuyến đi không biến thành chạy từ điểm này sang điểm khác.",
    "focus": "Bà Nà, Hội An, biển, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-da-nang-gia-dinh",
    "type": "combo",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Đà Nẵng gia đình 2026 | GoVietStay",
    "h1": "Combo Đà Nẵng cho gia đình: đi vừa sức, ưu tiên thời gian bên nhau",
    "description": "Nhà có trẻ nhỏ hay bố mẹ lớn tuổi thì lịch nên khác nhóm bạn trẻ. Hãy cho GoVietStay biết ai đi cùng để chọn giờ, xe và số điểm phù hợp.",
    "hero": "Nhà có trẻ nhỏ hay bố mẹ lớn tuổi thì lịch nên khác nhóm bạn trẻ. Hãy cho GoVietStay biết ai đi cùng để chọn giờ, xe và số điểm phù hợp.",
    "focus": "Trẻ nhỏ, người lớn tuổi, tour riêng, lịch nhẹ",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-phu-quoc-3n2d",
    "type": "combo",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Phú Quốc 3N2Đ 2026 | GoVietStay",
    "h1": "Combo Phú Quốc 3N2Đ: ít ngày thì chọn đúng thứ mình thích nhất",
    "description": "Ba ngày hai đêm khá ngắn. Nếu thích biển thì dành một ngày cho biển; nếu thích nghỉ dưỡng thì đừng cố nhồi quá nhiều điểm tham quan.",
    "hero": "Ba ngày hai đêm khá ngắn. Nếu thích biển thì dành một ngày cho biển; nếu thích nghỉ dưỡng thì đừng cố nhồi quá nhiều điểm tham quan.",
    "focus": "Land combo, resort, tour đảo, xe sân bay",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-phu-quoc-4n3d",
    "type": "combo",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Phú Quốc 4N3Đ 2026 | GoVietStay",
    "h1": "Combo Phú Quốc 4N3Đ: có biển, có nghỉ, vẫn đủ thời gian khám phá",
    "description": "Bốn ngày ba đêm là khoảng thời gian khá đẹp cho Phú Quốc. Có thể dành một ngày đi đảo, một ngày vui chơi hoặc khám phá và vẫn còn thời gian ở resort.",
    "hero": "Bốn ngày ba đêm là khoảng thời gian khá đẹp cho Phú Quốc. Có thể dành một ngày đi đảo, một ngày vui chơi hoặc khám phá và vẫn còn thời gian ở resort.",
    "focus": "Resort, tour đảo, Hòn Thơm, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-phu-quoc-gia-dinh",
    "type": "combo",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Phú Quốc gia đình 2026 | GoVietStay",
    "h1": "Combo Phú Quốc cho gia đình: chọn lịch theo tuổi và khu resort",
    "description": "Gia đình ở khu nào, có bé nhỏ hay người lớn tuổi không và thích biển hay vui chơi sẽ quyết định lịch đi. GoVietStay hỏi những điều này trước rồi mới ghép dịch vụ.",
    "hero": "Gia đình ở khu nào, có bé nhỏ hay người lớn tuổi không và thích biển hay vui chơi sẽ quyết định lịch đi. GoVietStay hỏi những điều này trước rồi mới ghép dịch vụ.",
    "focus": "Gia đình nhiều thế hệ, tour riêng, trẻ em, resort",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-rieng-da-nang-gia-dinh",
    "type": "private",
    "destination": "Đà Nẵng · Hội An · Huế",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Tour riêng Đà Nẵng gia đình 2026 | GoVietStay",
    "h1": "Tour riêng Đà Nẵng cho gia đình: chỉ có người nhà mình",
    "description": "Bạn cho GoVietStay biết số người, ngày đi, độ tuổi, sở thích và điều không muốn. Từ đó mới lên lịch, thay vì lấy một tour mẫu rồi bắt cả nhà đi theo.",
    "hero": "Bạn cho GoVietStay biết số người, ngày đi, độ tuổi, sở thích và điều không muốn. Từ đó mới lên lịch, thay vì lấy một tour mẫu rồi bắt cả nhà đi theo.",
    "focus": "Không ghép khách, riêng tư, giờ đi linh hoạt, sở thích",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-rieng-hoi-an",
    "type": "private",
    "destination": "Hội An",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Tour riêng Hội An 2026 | GoVietStay",
    "h1": "Tour riêng Hội An: muốn đi chậm, chụp lâu hay về sớm đều dễ sắp xếp hơn",
    "description": "Có người thích Rừng Dừa, có người chỉ muốn phố cổ và ăn tối. Tour riêng giúp bạn bỏ bớt những phần không hợp với nhóm mình.",
    "hero": "Có người thích Rừng Dừa, có người chỉ muốn phố cổ và ăn tối. Tour riêng giúp bạn bỏ bớt những phần không hợp với nhóm mình.",
    "focus": "Không ghép khách, chụp ảnh, ẩm thực, lịch riêng",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-rieng-hue",
    "type": "private",
    "destination": "Huế",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Tour riêng Huế từ Đà Nẵng 2026 | GoVietStay",
    "h1": "Tour riêng Huế: đi theo sức của gia đình, không phải theo giờ của cả đoàn",
    "description": "Nếu nhà có người lớn tuổi hoặc muốn tìm hiểu lịch sử kỹ hơn, tour riêng sẽ dễ sắp giờ nghỉ và thời gian ở mỗi điểm hơn.",
    "hero": "Nếu nhà có người lớn tuổi hoặc muốn tìm hiểu lịch sử kỹ hơn, tour riêng sẽ dễ sắp giờ nghỉ và thời gian ở mỗi điểm hơn.",
    "focus": "Xe riêng, hướng dẫn viên tùy chọn, gia đình, di sản",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-rieng-phu-quoc-gia-dinh",
    "type": "private",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Tour riêng Phú Quốc gia đình 2026 | GoVietStay",
    "h1": "Tour riêng Phú Quốc cho gia đình: cần riêng phần nào thì làm riêng phần đó",
    "description": "Không phải lúc nào cũng cần cano riêng và xe riêng cả ngày. GoVietStay sẽ dựa vào số người, ngân sách và nhu cầu để chọn mức riêng tư vừa đủ.",
    "hero": "Không phải lúc nào cũng cần cano riêng và xe riêng cả ngày. GoVietStay sẽ dựa vào số người, ngân sách và nhu cầu để chọn mức riêng tư vừa đủ.",
    "focus": "Cano riêng, xe riêng, không ghép khách, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "du-lich-da-nang-tu-tuc",
    "type": "guide",
    "destination": "Đà Nẵng",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Du lịch Đà Nẵng tự túc 2026 | GoVietStay",
    "h1": "Du lịch Đà Nẵng tự túc: tự đặt phần dễ, nhờ local hỗ trợ phần mất thời gian",
    "description": "Vé máy bay và khách sạn bạn hoàn toàn có thể tự đặt. Những phần như xe sân bay, Bà Nà hay tour biển thì dùng dịch vụ khi thấy tiện hơn.",
    "hero": "Vé máy bay và khách sạn bạn hoàn toàn có thể tự đặt. Những phần như xe sân bay, Bà Nà hay tour biển thì dùng dịch vụ khi thấy tiện hơn.",
    "focus": "Lịch trình, khu ở, tour, xe, hỗ trợ địa phương",
    "updated": "2026-08-26"
  },
  {
    "slug": "lich-trinh-da-nang-4-ngay-3-dem",
    "type": "guide",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Lịch trình Đà Nẵng 4 ngày 3 đêm 2026 | GoVietStay",
    "h1": "Lịch trình Đà Nẵng 4N3Đ: đi đủ đẹp mà vẫn có thời gian nghỉ",
    "description": "Ngày đầu đi nhẹ, một ngày dành cho Bà Nà, một chiều tối ở Hội An và ngày cuối linh hoạt là lịch khá dễ áp dụng cho lần đầu đến Đà Nẵng.",
    "hero": "Ngày đầu đi nhẹ, một ngày dành cho Bà Nà, một chiều tối ở Hội An và ngày cuối linh hoạt là lịch khá dễ áp dụng cho lần đầu đến Đà Nẵng.",
    "focus": "Bà Nà, Hội An, biển, sân bay",
    "updated": "2026-08-26"
  },
  {
    "slug": "chi-phi-du-lich-da-nang",
    "type": "guide",
    "destination": "Đà Nẵng",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Chi phí du lịch Đà Nẵng 2026 | GoVietStay",
    "h1": "Chi phí du lịch Đà Nẵng: chia từng khoản sẽ dễ tính hơn",
    "description": "Đừng cố tìm một con số chung cho tất cả. Hãy tách vé máy bay, khách sạn, tour, xe và ăn uống, rồi mới xem phần nào cần tiết kiệm và phần nào đáng chi thêm.",
    "hero": "Đừng cố tìm một con số chung cho tất cả. Hãy tách vé máy bay, khách sạn, tour, xe và ăn uống, rồi mới xem phần nào cần tiết kiệm và phần nào đáng chi thêm.",
    "focus": "Ngân sách, combo, giá tour, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "gia-ve-ba-na-hills",
    "type": "guide",
    "destination": "Đà Nẵng",
    "priceKey": "bana",
    "depositPercent": 0,
    "title": "Giá vé Bà Nà Hills 2026 | GoVietStay",
    "h1": "Giá Bà Nà Hills: xem đúng loại vé rồi mới so giá",
    "description": "Vé lẻ, gói buffet, tour có xe và giá trẻ em là những thứ khác nhau. Muốn so cho đúng thì phải xem cùng một quyền lợi.",
    "hero": "Vé lẻ, gói buffet, tour có xe và giá trẻ em là những thứ khác nhau. Muốn so cho đúng thì phải xem cùng một quyền lợi.",
    "focus": "Giá vé, buffet, trẻ em, tour",
    "updated": "2026-08-26"
  },
  {
    "slug": "da-nang-gia-dinh-co-tre-em",
    "type": "guide",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Đà Nẵng cho gia đình có trẻ em 2026 | GoVietStay",
    "h1": "Đà Nẵng với trẻ em: đừng xếp lịch kín từ sáng đến tối",
    "description": "Nhà có trẻ nhỏ thì một hoạt động lớn mỗi ngày thường là vừa. Chừa thời gian ăn, ngủ và chơi tự do sẽ giúp cả bố mẹ lẫn bé đỡ mệt.",
    "hero": "Nhà có trẻ nhỏ thì một hoạt động lớn mỗi ngày thường là vừa. Chừa thời gian ăn, ngủ và chơi tự do sẽ giúp cả bố mẹ lẫn bé đỡ mệt.",
    "focus": "Trẻ em, Bà Nà, Hội An, tour riêng gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "du-lich-phu-quoc-tu-tuc",
    "type": "guide",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Du lịch Phú Quốc tự túc 2026 | GoVietStay",
    "h1": "Du lịch Phú Quốc tự túc: chọn khu ở trước, rồi mới xếp điểm đi",
    "description": "Phú Quốc rộng hơn nhiều người nghĩ. Chọn resort đúng khu sẽ giúp tiết kiệm khá nhiều thời gian và tiền xe trong cả chuyến.",
    "hero": "Phú Quốc rộng hơn nhiều người nghĩ. Chọn resort đúng khu sẽ giúp tiết kiệm khá nhiều thời gian và tiền xe trong cả chuyến.",
    "focus": "Khu ở, tour đảo, xe sân bay, ngân sách",
    "updated": "2026-08-26"
  },
  {
    "slug": "lich-trinh-phu-quoc-4-ngay-3-dem",
    "type": "guide",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Lịch trình Phú Quốc 4 ngày 3 đêm 2026 | GoVietStay",
    "h1": "Lịch trình Phú Quốc 4N3Đ: một ngày biển, một ngày khám phá, còn lại để nghỉ",
    "description": "Đừng cố đi hết Phú Quốc trong bốn ngày. Chọn vài trải nghiệm chính rồi dành thời gian tận hưởng resort, bãi biển và ăn uống sẽ dễ chịu hơn.",
    "hero": "Đừng cố đi hết Phú Quốc trong bốn ngày. Chọn vài trải nghiệm chính rồi dành thời gian tận hưởng resort, bãi biển và ăn uống sẽ dễ chịu hơn.",
    "focus": "Tour đảo, resort, Hòn Thơm, sân bay",
    "updated": "2026-08-26"
  },
  {
    "slug": "chi-phi-du-lich-phu-quoc",
    "type": "guide",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Chi phí du lịch Phú Quốc 2026 | GoVietStay",
    "h1": "Chi phí Phú Quốc: resort và số ngày đi tour ảnh hưởng nhiều nhất",
    "description": "Hai nhóm đi cùng số ngày vẫn có thể chênh ngân sách khá xa. Khu resort, loại xe và số ngày đi tour thường là ba khoản tạo khác biệt lớn.",
    "hero": "Hai nhóm đi cùng số ngày vẫn có thể chênh ngân sách khá xa. Khu resort, loại xe và số ngày đi tour thường là ba khoản tạo khác biệt lớn.",
    "focus": "Resort, tour đảo, xe, combo",
    "updated": "2026-08-26"
  },
  {
    "slug": "phu-quoc-mua-nao-dep",
    "type": "guide",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Phú Quốc mùa nào đẹp 2026 | GoVietStay",
    "h1": "Phú Quốc mùa nào đẹp? Còn tùy bạn muốn nghỉ dưỡng hay đi biển",
    "description": "Nếu ưu tiên snorkeling và cano, điều kiện biển quan trọng hơn. Nếu chủ yếu nghỉ resort, bạn có thể linh hoạt thời gian hơn.",
    "hero": "Nếu ưu tiên snorkeling và cano, điều kiện biển quan trọng hơn. Nếu chủ yếu nghỉ resort, bạn có thể linh hoạt thời gian hơn.",
    "focus": "Thời tiết, biển, snorkeling, tour đảo",
    "updated": "2026-08-26"
  }
];

export const getVietnamSeoPage=(slug:string)=>vietnamSeoPages.find(p=>p.slug===slug);
export const getVietnamRelated=(page:VietnamSeoPage)=>[
  ...vietnamSeoPages.filter(p=>p.slug!==page.slug&&p.destination.split(" · ")[0]===page.destination.split(" · ")[0]),
  ...vietnamSeoPages.filter(p=>p.slug!==page.slug&&p.type===page.type),
].filter((p,i,a)=>a.findIndex(x=>x.slug===p.slug)===i).slice(0,4);
