export type VietnamSeoPage = {
  slug: string;
  type: "product" | "combo" | "private" | "guide";
  destination: string;
  priceKey: string | null;
  depositPercent: number;
  title: string;
  h1: string;
  description: string;
  hero: string;
  focus: string;
  updated: string;
};
export const vietnamSeoPages: VietnamSeoPage[] = [
  {
    "slug": "tour-ba-na-hills",
    "type": "product",
    "destination": "Đà Nẵng",
    "priceKey": "bana",
    "depositPercent": 20,
    "title": "Tour Bà Nà Hills 2026 từ Đà Nẵng | GoVietStay",
    "h1": "Tour Bà Nà Hills: biết rõ mình trả gì trước khi đặt",
    "description": "Không cần tự ghép vé, xe và giờ đón. Cho GoVietStay ngày đi, số người và khách sạn; chúng tôi xác nhận tổng chi phí trước.",
    "hero": "Không cần tự ghép vé, xe và giờ đón. Cho GoVietStay ngày đi, số người và khách sạn; chúng tôi xác nhận tổng chi phí trước.",
    "focus": "Bà Nà Hills, trẻ em theo chiều cao, tour ghép hoặc riêng gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-cu-lao-cham",
    "type": "product",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": "cham",
    "depositPercent": 20,
    "title": "Tour Cù Lao Chàm 2026 | Cano, snorkeling | GoVietStay",
    "h1": "Cù Lao Chàm: một ngày biển đáng đi khi điều kiện phù hợp",
    "description": "Đi biển đẹp nhất khi lịch có thể linh hoạt theo gió, sóng và vận hành thực tế.",
    "hero": "Đi biển đẹp nhất khi lịch có thể linh hoạt theo gió, sóng và vận hành thực tế.",
    "focus": "Cano, snorkeling, thời tiết, gia đình, private",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-hoi-an-rung-dua",
    "type": "product",
    "destination": "Hội An",
    "priceKey": "hoian",
    "depositPercent": 20,
    "title": "Tour Hội An Rừng Dừa 2026 | GoVietStay",
    "h1": "Hội An + Rừng Dừa: đi buổi chiều để chuyến đi có nhịp đẹp hơn",
    "description": "Rừng Dừa trước, phố cổ lúc hoàng hôn và đèn lồng sau. Không cần chạy checklist.",
    "hero": "Rừng Dừa trước, phố cổ lúc hoàng hôn và đèn lồng sau. Không cần chạy checklist.",
    "focus": "Rừng Dừa, thuyền thúng, Hội An buổi tối, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-hue-tu-da-nang",
    "type": "product",
    "destination": "Huế",
    "priceKey": "hue",
    "depositPercent": 20,
    "title": "Tour Huế từ Đà Nẵng 2026 | GoVietStay",
    "h1": "Huế từ Đà Nẵng: một ngày di sản cần đủ thời gian",
    "description": "Huế không nên là một ngày chạy điểm. Chọn ít hơn nhưng hiểu và tận hưởng nhiều hơn.",
    "hero": "Huế không nên là một ngày chạy điểm. Chọn ít hơn nhưng hiểu và tận hưởng nhiều hơn.",
    "focus": "Đại Nội, di sản, xe riêng, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "don-san-bay-da-nang",
    "type": "product",
    "destination": "Đà Nẵng",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Đón sân bay Đà Nẵng 2026 | GoVietStay",
    "h1": "Đón sân bay Đà Nẵng: đúng xe, đúng hành lý, đúng điểm đến",
    "description": "Gửi chuyến bay, số người, số vali và khách sạn. GoVietStay chọn xe theo nhu cầu thật.",
    "hero": "Gửi chuyến bay, số người, số vali và khách sạn. GoVietStay chọn xe theo nhu cầu thật.",
    "focus": "DAD, khách sạn, Hội An, transfer 0% deposit",
    "updated": "2026-08-26"
  },
  {
    "slug": "thue-xe-da-nang-hoi-an",
    "type": "product",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Thuê xe Đà Nẵng Hội An 2026 | GoVietStay",
    "h1": "Đà Nẵng ↔ Hội An bằng xe riêng: linh hoạt khi bạn cần",
    "description": "Đi một chiều, khứ hồi hay thêm điểm dừng? Xe riêng phục vụ lịch của gia đình, không ngược lại.",
    "hero": "Đi một chiều, khứ hồi hay thêm điểm dừng? Xe riêng phục vụ lịch của gia đình, không ngược lại.",
    "focus": "xe riêng, hành lý, gia đình, không ghép khách",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-3-dao-phu-quoc",
    "type": "product",
    "destination": "Phú Quốc",
    "priceKey": "pq3",
    "depositPercent": 20,
    "title": "Tour 3 đảo Phú Quốc 2026 | GoVietStay",
    "h1": "Tour 3 đảo Phú Quốc: dành cả ngày cho biển thay vì chạy điểm",
    "description": "Nếu mục tiêu là biển, hãy dành đúng một ngày cho cano và snorkeling, giữ lịch linh hoạt theo điều kiện.",
    "hero": "Nếu mục tiêu là biển, hãy dành đúng một ngày cho cano và snorkeling, giữ lịch linh hoạt theo điều kiện.",
    "focus": "3 đảo, cano, snorkeling, gia đình",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-4-dao-phu-quoc-cap-treo",
    "type": "product",
    "destination": "Phú Quốc",
    "priceKey": "pq4",
    "depositPercent": 20,
    "title": "Tour 4 đảo Phú Quốc + cáp treo 2026 | GoVietStay",
    "h1": "4 đảo + cáp treo Hòn Thơm: gộp đúng trải nghiệm, không gộp cho thật nhiều",
    "description": "Một ngày lớn chỉ đáng tiền khi quyền lợi, vé và thời gian ăn khớp nhau.",
    "hero": "Một ngày lớn chỉ đáng tiền khi quyền lợi, vé và thời gian ăn khớp nhau.",
    "focus": "4 đảo, Hòn Thơm, cáp treo, quyền lợi rõ",
    "updated": "2026-08-26"
  },
  {
    "slug": "don-san-bay-phu-quoc",
    "type": "product",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Đón sân bay Phú Quốc 2026 | GoVietStay",
    "h1": "Đón sân bay Phú Quốc: chọn xe theo resort và hành lý",
    "description": "Phú Quốc dài. Gửi đúng resort để biết trước thời gian, loại xe và chi phí.",
    "hero": "Phú Quốc dài. Gửi đúng resort để biết trước thời gian, loại xe và chi phí.",
    "focus": "PQC, resort, transfer riêng, 0% deposit",
    "updated": "2026-08-26"
  },
  {
    "slug": "thue-xe-phu-quoc",
    "type": "product",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Thuê xe Phú Quốc 2026 | GoVietStay",
    "h1": "Thuê xe Phú Quốc: đi theo lịch của bạn, không chạy theo xe tour",
    "description": "Nam đảo, bắc đảo hay đi ăn theo danh sách của bạn — gom tuyến để bớt thời gian ngồi xe.",
    "hero": "Nam đảo, bắc đảo hay đi ăn theo danh sách của bạn — gom tuyến để bớt thời gian ngồi xe.",
    "focus": "xe riêng, resort, nam đảo, bắc đảo",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-da-nang-3-tour",
    "type": "combo",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": "comboDN3",
    "depositPercent": 20,
    "title": "Combo Đà Nẵng 3 tour 2026 | GoVietStay",
    "h1": "Combo Đà Nẵng 3 tour: mua một lần, giảm việc phải tìm ba lần",
    "description": "Bà Nà + Hội An/Rừng Dừa + Cù Lao Chàm trong một booking, một đầu mối Zalo.",
    "hero": "Bà Nà + Hội An/Rừng Dừa + Cù Lao Chàm trong một booking, một đầu mối Zalo.",
    "focus": "Bà Nà, Hội An, Cù Lao Chàm, tiết kiệm tổng",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-da-nang-3n2d",
    "type": "combo",
    "destination": "Đà Nẵng",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Đà Nẵng 3N2Đ 2026 | GoVietStay",
    "h1": "Combo Đà Nẵng 3N2Đ: bạn lo vé máy bay, chúng tôi lo phần còn lại",
    "description": "Land combo giúp bạn tự săn vé máy bay nhưng vẫn có một lịch trình thống nhất sau khi hạ cánh.",
    "hero": "Land combo giúp bạn tự săn vé máy bay nhưng vẫn có một lịch trình thống nhất sau khi hạ cánh.",
    "focus": "land combo, sân bay, tour, khách sạn tùy chọn",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-da-nang-4n3d",
    "type": "combo",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Đà Nẵng 4N3Đ 2026 | GoVietStay",
    "h1": "Đà Nẵng 4N3Đ: đủ thời gian để đi đẹp mà không phải chạy",
    "description": "Một lịch tốt không phải lịch có nhiều điểm nhất; là lịch bạn vẫn còn năng lượng để tận hưởng.",
    "hero": "Một lịch tốt không phải lịch có nhiều điểm nhất; là lịch bạn vẫn còn năng lượng để tận hưởng.",
    "focus": "Bà Nà, Hội An, biển, family",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-da-nang-gia-dinh",
    "type": "combo",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Đà Nẵng gia đình 2026 | GoVietStay",
    "h1": "Combo Đà Nẵng cho gia đình: ưu tiên sức khỏe, riêng tư và thời gian bên nhau",
    "description": "Hãy cho biết ai đang đi cùng bạn; lịch trình phải thích nghi với gia đình, không ngược lại.",
    "hero": "Hãy cho biết ai đang đi cùng bạn; lịch trình phải thích nghi với gia đình, không ngược lại.",
    "focus": "trẻ nhỏ, người lớn tuổi, private, nghỉ hợp lý",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-phu-quoc-3n2d",
    "type": "combo",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Phú Quốc 3N2Đ 2026 | GoVietStay",
    "h1": "Phú Quốc 3N2Đ: chọn một trọng tâm thay vì cố đi hết đảo",
    "description": "Ba ngày ngắn. Chọn biển, nghỉ dưỡng hoặc vui chơi làm trọng tâm.",
    "hero": "Ba ngày ngắn. Chọn biển, nghỉ dưỡng hoặc vui chơi làm trọng tâm.",
    "focus": "land combo, resort, tour đảo, transfer",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-phu-quoc-4n3d",
    "type": "combo",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Phú Quốc 4N3Đ 2026 | GoVietStay",
    "h1": "Phú Quốc 4N3Đ: đủ chỗ cho biển, resort và một ngày khám phá",
    "description": "Bốn ngày cho phép có một ngày biển, một ngày khám phá và vẫn còn thời gian nghỉ dưỡng.",
    "hero": "Bốn ngày cho phép có một ngày biển, một ngày khám phá và vẫn còn thời gian nghỉ dưỡng.",
    "focus": "resort, tour đảo, Hòn Thơm, family",
    "updated": "2026-08-26"
  },
  {
    "slug": "combo-phu-quoc-gia-dinh",
    "type": "combo",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Combo Phú Quốc gia đình 2026 | GoVietStay",
    "h1": "Phú Quốc cho gia đình: một chuyến đi riêng tư, không phải lịch trình đại trà",
    "description": "Bắt đầu bằng tuổi, sở thích và khu resort; sau đó mới chọn trải nghiệm.",
    "hero": "Bắt đầu bằng tuổi, sở thích và khu resort; sau đó mới chọn trải nghiệm.",
    "focus": "gia đình 3 thế hệ, private, trẻ em, resort",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-rieng-da-nang-gia-dinh",
    "type": "private",
    "destination": "Đà Nẵng · Hội An · Huế",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Tour riêng Đà Nẵng gia đình 2026 | GoVietStay",
    "h1": "Tour riêng Đà Nẵng: chuyến đi chỉ dành cho gia đình bạn",
    "description": "Chỉ cần cho số người, ngày đi, độ tuổi, sở thích và điều không muốn. Lịch trình được thiết kế quanh gia đình.",
    "hero": "Chỉ cần cho số người, ngày đi, độ tuổi, sở thích và điều không muốn. Lịch trình được thiết kế quanh gia đình.",
    "focus": "không ghép khách, riêng tư, nhịp độ, sở thích",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-rieng-hoi-an",
    "type": "private",
    "destination": "Hội An",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Tour riêng Hội An 2026 | GoVietStay",
    "h1": "Hội An riêng tư: dành thời gian cho điều bạn thật sự thích",
    "description": "Muốn chụp ảnh lâu, bỏ Rừng Dừa, ăn món riêng hay về sớm? Tour riêng cho phép bạn chọn.",
    "hero": "Muốn chụp ảnh lâu, bỏ Rừng Dừa, ăn món riêng hay về sớm? Tour riêng cho phép bạn chọn.",
    "focus": "không ghép khách, ảnh, ẩm thực, lịch riêng",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-rieng-hue",
    "type": "private",
    "destination": "Huế",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Tour riêng Huế từ Đà Nẵng 2026 | GoVietStay",
    "h1": "Huế riêng: bớt chạy điểm, thêm thời gian để hiểu",
    "description": "Gia đình thích lịch sử thì dành thời gian cho lịch sử; thích cảnh và ẩm thực thì lịch phải khác.",
    "hero": "Gia đình thích lịch sử thì dành thời gian cho lịch sử; thích cảnh và ẩm thực thì lịch phải khác.",
    "focus": "xe riêng, guide tùy chọn, gia đình, di sản",
    "updated": "2026-08-26"
  },
  {
    "slug": "tour-rieng-phu-quoc-gia-dinh",
    "type": "private",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 20,
    "title": "Tour riêng Phú Quốc gia đình 2026 | GoVietStay",
    "h1": "Phú Quốc riêng cho gia đình: đảo của bạn, nhịp của bạn",
    "description": "Cano riêng, xe riêng hay chỉ cần một phần private — chọn mức riêng tư theo nhu cầu và ngân sách.",
    "hero": "Cano riêng, xe riêng hay chỉ cần một phần private — chọn mức riêng tư theo nhu cầu và ngân sách.",
    "focus": "cano riêng, xe riêng, không ghép khách, family",
    "updated": "2026-08-26"
  },
  {
    "slug": "du-lich-da-nang-tu-tuc",
    "type": "guide",
    "destination": "Đà Nẵng",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Du lịch Đà Nẵng tự túc 2026 | GoVietStay",
    "h1": "Du lịch Đà Nẵng tự túc: tự do nhưng không cần tự lo mọi thứ",
    "description": "Bạn tự đặt vé máy bay và khách sạn; GoVietStay chỉ xuất hiện ở phần giúp tiết kiệm thời gian hoặc tránh mua sai.",
    "hero": "Bạn tự đặt vé máy bay và khách sạn; GoVietStay chỉ xuất hiện ở phần giúp tiết kiệm thời gian hoặc tránh mua sai.",
    "focus": "lịch trình, khu ở, tour, xe, local support",
    "updated": "2026-08-26"
  },
  {
    "slug": "lich-trinh-da-nang-4-ngay-3-dem",
    "type": "guide",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Lịch trình Đà Nẵng 4 ngày 3 đêm 2026 | GoVietStay",
    "h1": "Đà Nẵng 4N3Đ: lịch đủ đẹp nhưng vẫn còn thời gian thở",
    "description": "Ngày đến nhẹ, một ngày lớn, một chiều Hội An và ngày cuối linh hoạt là cấu trúc khó sai.",
    "hero": "Ngày đến nhẹ, một ngày lớn, một chiều Hội An và ngày cuối linh hoạt là cấu trúc khó sai.",
    "focus": "Bà Nà, Hội An, beach, sân bay",
    "updated": "2026-08-26"
  },
  {
    "slug": "chi-phi-du-lich-da-nang",
    "type": "guide",
    "destination": "Đà Nẵng",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Chi phí du lịch Đà Nẵng 2026 | GoVietStay",
    "h1": "Chi phí Đà Nẵng: tính theo chuyến đi của bạn, không theo một con số trên mạng",
    "description": "Tách khách sạn, trải nghiệm, xe và ăn uống; sau đó mới quyết định phần nào đáng nâng cấp.",
    "hero": "Tách khách sạn, trải nghiệm, xe và ăn uống; sau đó mới quyết định phần nào đáng nâng cấp.",
    "focus": "ngân sách, combo, giá tour, family",
    "updated": "2026-08-26"
  },
  {
    "slug": "gia-ve-ba-na-hills",
    "type": "guide",
    "destination": "Đà Nẵng",
    "priceKey": "bana",
    "depositPercent": 0,
    "title": "Giá vé Bà Nà Hills 2026 | GoVietStay",
    "h1": "Giá Bà Nà Hills: đừng so giá trước khi biết mình đang so gói nào",
    "description": "Vé lẻ, tour, buffet, trẻ em và đối tượng khách có thể là những mức giá khác nhau.",
    "hero": "Vé lẻ, tour, buffet, trẻ em và đối tượng khách có thể là những mức giá khác nhau.",
    "focus": "giá vé, buffet, trẻ em, tour",
    "updated": "2026-08-26"
  },
  {
    "slug": "da-nang-gia-dinh-co-tre-em",
    "type": "guide",
    "destination": "Đà Nẵng · Hội An",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Đà Nẵng cho gia đình có trẻ em 2026 | GoVietStay",
    "h1": "Đà Nẵng với trẻ em: chuyến đi tốt là chuyến đi cả nhà còn vui vào cuối ngày",
    "description": "Đừng thiết kế lịch cho người lớn rồi bắt trẻ em theo. Bắt đầu bằng giờ ngủ, khả năng đi bộ và sở thích.",
    "hero": "Đừng thiết kế lịch cho người lớn rồi bắt trẻ em theo. Bắt đầu bằng giờ ngủ, khả năng đi bộ và sở thích.",
    "focus": "trẻ em, Bà Nà, Hội An, private family",
    "updated": "2026-08-26"
  },
  {
    "slug": "du-lich-phu-quoc-tu-tuc",
    "type": "guide",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Du lịch Phú Quốc tự túc 2026 | GoVietStay",
    "h1": "Phú Quốc tự túc: chọn đúng khu ở trước khi chọn danh sách điểm",
    "description": "Phú Quốc rộng. Một resort đẹp nhưng sai khu có thể khiến bạn mất hàng giờ di chuyển.",
    "hero": "Phú Quốc rộng. Một resort đẹp nhưng sai khu có thể khiến bạn mất hàng giờ di chuyển.",
    "focus": "khu ở, tour đảo, transfer, ngân sách",
    "updated": "2026-08-26"
  },
  {
    "slug": "lich-trinh-phu-quoc-4-ngay-3-dem",
    "type": "guide",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Lịch trình Phú Quốc 4 ngày 3 đêm 2026 | GoVietStay",
    "h1": "Phú Quốc 4N3Đ: một ngày biển, một ngày khám phá, phần còn lại để nghỉ",
    "description": "Đừng dùng 4N3Đ để đi hết đảo; dùng nó để có một chuyến đi cân bằng.",
    "hero": "Đừng dùng 4N3Đ để đi hết đảo; dùng nó để có một chuyến đi cân bằng.",
    "focus": "tour đảo, resort, Hòn Thơm, airport",
    "updated": "2026-08-26"
  },
  {
    "slug": "chi-phi-du-lich-phu-quoc",
    "type": "guide",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Chi phí du lịch Phú Quốc 2026 | GoVietStay",
    "h1": "Chi phí Phú Quốc: khu ở và kiểu trải nghiệm quyết định ngân sách",
    "description": "Hai gia đình ở cùng số đêm có thể chênh ngân sách lớn vì resort và số ngày đi tour.",
    "hero": "Hai gia đình ở cùng số đêm có thể chênh ngân sách lớn vì resort và số ngày đi tour.",
    "focus": "resort, tour đảo, xe, combo",
    "updated": "2026-08-26"
  },
  {
    "slug": "phu-quoc-mua-nao-dep",
    "type": "guide",
    "destination": "Phú Quốc",
    "priceKey": null,
    "depositPercent": 0,
    "title": "Phú Quốc mùa nào đẹp 2026 | GoVietStay",
    "h1": "Phú Quốc mùa nào đẹp? Hãy hỏi: bạn muốn làm gì ở Phú Quốc?",
    "description": "Một chuyến nghỉ resort và một chuyến snorkeling không cần cùng điều kiện thời tiết.",
    "hero": "Một chuyến nghỉ resort và một chuyến snorkeling không cần cùng điều kiện thời tiết.",
    "focus": "thời tiết, biển, snorkeling, tour đảo",
    "updated": "2026-08-26"
  }
];
export const getVietnamSeoPage=(slug:string)=>vietnamSeoPages.find(p=>p.slug===slug);
export const getVietnamRelated=(page:VietnamSeoPage)=>[
  ...vietnamSeoPages.filter(p=>p.slug!==page.slug&&p.destination.split(" · ")[0]===page.destination.split(" · ")[0]),
  ...vietnamSeoPages.filter(p=>p.slug!==page.slug&&p.type===page.type),
].filter((p,i,a)=>a.findIndex(x=>x.slug===p.slug)===i).slice(0,4);
