import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import JsonLd from "../../../components/JsonLd";

const BASE = "https://www.govietstay.com";
const CANONICAL = `${BASE}/ru/morskaya-rybalka-danang-phu-quoc`;
const HERO = "/ru/fishing/day-catch-sunset.webp";
const WHATSAPP = `https://wa.me/84937762607?text=${encodeURIComponent("Здравствуйте! Интересует морская рыбалка. Локация: Дананг / Фукуок. Дата: ___. Гостей: ___. Опыт рыбалки: ___. Вид ловли: профессиональная / дневная / ночная ловля кальмара. Желаемая длительность: ___. Нужны снасти: да / нет. Отель: ___.")}`;

export const metadata: Metadata = {
  title: "Морская рыбалка в Дананге и на Фукуоке",
  description: "Морская рыбалка в Дананге и на Фукуоке: профессиональные выходы для опытных рыболовов, дневная рыбалка и ночная ловля кальмара. Цена и программа — по запросу.",
  keywords: ["морская рыбалка", "рыбалка в Дананге", "морская рыбалка в Дананге", "рыбалка на Фукуоке", "морская рыбалка на Фукуоке", "профессиональная рыбалка Вьетнам", "ночная ловля кальмара", "ловля кальмаров Вьетнам"],
  alternates: { canonical: CANONICAL, languages: { ru: CANONICAL, "ru-KZ": CANONICAL } },
  robots: { index: true, follow: true },
  openGraph: { type: "website", locale: "ru_RU", url: CANONICAL, siteName: "GoVietStay", title: "Морская рыбалка в Дананге и на Фукуоке | GoVietStay", description: "Профессиональная морская рыбалка для опытных гостей, дневные выходы и ночная ловля кальмара. Только Дананг и Фукуок.", images: [{ url: `${BASE}${HERO}`, width: 720, height: 540, alt: "Морская рыбалка GoVietStay во Вьетнаме" }] },
  twitter: { card: "summary_large_image", title: "Морская рыбалка в Дананге и на Фукуоке | GoVietStay", description: "Профессиональная рыбалка, дневные выходы и ночная ловля кальмара. Дананг и Фукуок.", images: [`${BASE}${HERO}`] },
};

const faqs = [
  ["Где проходят рыболовные туры GoVietStay?", "На этой странице мы предлагаем морские рыболовные форматы только в Дананге и на Фукуоке. Конкретная точка выхода зависит от выбранного формата, моря и доступного судна."],
  ["Нужен ли опыт для профессиональной морской рыбалки?", "Да. Профессиональный формат рассчитан на гостей, которые уже умеют рыбачить. До подтверждения мы спрашиваем ваш опыт, привычный способ ловли и ожидания от выхода."],
  ["Сколько стоит профессиональная рыбалка?", "Фиксированной публичной цены нет. Стоимость зависит от локации, судна, количества участников, длительности, дальности выхода, снастей и условий моря. Точную цену подтверждаем после уточнения деталей."],
  ["Нужен ли опыт для дневной рыбалки и ловли кальмара?", "Для обычного дневного выхода и ночной ловли кальмара требования мягче. Мы всё равно уточняем уровень гостей заранее, чтобы подобрать подходящий формат и инструктаж."],
  ["Гарантирован ли улов?", "Нет. Улов зависит от сезона, течения, погоды, места и активности рыбы или кальмара. Мы показываем реальные фотографии гостей, но не обещаем гарантированный результат."],
] as const;

const graph = { "@context": "https://schema.org", "@graph": [
  { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "GoVietStay на русском", item: `${BASE}/ru` }, { "@type": "ListItem", position: 2, name: "Морская рыбалка", item: CANONICAL }] },
  { "@type": "Service", "@id": `${CANONICAL}#service`, name: "Морская рыбалка в Дананге и на Фукуоке", serviceType: "Морская рыбалка и ночная ловля кальмара", description: "Профессиональная морская рыбалка для опытных гостей, дневные выходы и ночная ловля кальмара в Дананге и на Фукуоке.", inLanguage: "ru", url: CANONICAL, image: `${BASE}${HERO}`, areaServed: [{ "@type": "City", name: "Da Nang" }, { "@type": "Place", name: "Phu Quoc" }], provider: { "@id": `${BASE}/#organization` } },
  { "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
] };

const formats = [
  { number: "01", tag: "ОПЫТ ОБЯЗАТЕЛЕН", title: "Профессиональная морская рыбалка", text: "Выход для гостей, которые уже умеют рыбачить и хотят именно рыбалку, а не стандартную морскую прогулку. Судно, длительность и снасти подбираются после обсуждения вашего опыта.", bullets: ["Только по предварительному запросу", "Навыки рыбалки обязательны", "Цена рассчитывается индивидуально", "Выход подтверждается по состоянию моря"], image: "/ru/fishing/pro-catch-big.webp", alt: "Профессиональная морская рыбалка — крупный улов" },
  { number: "02", tag: "ДАНАНГ · ФУКУОК", title: "Дневная морская рыбалка", text: "Несколько часов в море с фокусом на рыбалку. Перед бронированием уточняем уровень гостей, время старта, снасти и подходящий район выхода.", bullets: ["Дананг или Фукуок", "Формат под уровень гостей", "Актуальная цена перед оплатой", "Улов не гарантируется"], image: "/ru/fishing/day-catch-sunset.webp", alt: "Дневная морская рыбалка во Вьетнаме" },
  { number: "03", tag: "ВЕЧЕР В МОРЕ", title: "Ночная ловля кальмара", text: "Вечерний выход в море с ловлей кальмара. Когда улов и программа позволяют, свежий кальмар можно приготовить на борту — именно так проходили наши реальные поездки.", bullets: ["Инструктаж по снасти", "Подходит парам и компаниям", "Зависит от сезона", "Программа подтверждается заранее"], image: "/ru/fishing/night-squid-two-guests.webp", alt: "Ночная ловля кальмара — гости GoVietStay" },
] as const;

const requestItems = ["Дананг или Фукуок", "Дата поездки", "Количество гостей", "Ваш опыт рыбалки", "Привычный способ ловли", "Желаемая длительность", "Нужны ли снасти", "Название отеля"] as const;

export default function Page() {
  return <main className="min-h-screen bg-[#061713] text-[#f7f4ea] pb-24 md:pb-0">
    <JsonLd data={graph} />

    <section className="relative isolate min-h-[760px] overflow-hidden lg:min-h-[780px]">
      <Image src={HERO} alt="Морская рыбалка GoVietStay в Дананге и на Фукуоке" fill priority sizes="100vw" className="object-cover object-center" />
      <div className="absolute inset-0 bg-gradient-to-b from-[#02110d]/35 via-[#02110d]/55 to-[#061713]" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#03140f]/90 via-[#03140f]/45 to-transparent" />
      <div className="relative z-10 mx-auto flex min-h-[760px] max-w-7xl flex-col px-4 py-5 sm:px-6 sm:py-7 lg:min-h-[780px] lg:px-10">
        <header className="flex items-center justify-between gap-3">
          <Link href="/ru" className="flex items-center gap-3" aria-label="GoVietStay на русском">
            <Image src="/govietstay-logo.jpg" alt="GoVietStay" width={52} height={52} className="h-11 w-11 rounded-2xl border border-white/20 object-cover shadow-lg sm:h-13 sm:w-13" />
            <div><p className="text-lg font-black leading-none sm:text-xl">GoVietStay</p><p className="mt-1 hidden text-[10px] font-bold uppercase tracking-[.18em] text-white/60 sm:block">Trusted Local Support</p></div>
          </Link>
          <span className="rounded-full border border-white/25 bg-black/25 px-3 py-2 text-[11px] font-bold backdrop-blur sm:text-xs">Дананг · Фукуок</span>
        </header>
        <div className="mt-auto max-w-4xl pb-10 pt-20 sm:pb-14 lg:pb-16">
          <div className="flex flex-wrap gap-2 text-[10px] font-black uppercase tracking-[.14em] sm:text-[11px]"><span className="rounded-full bg-amber-300 px-3 py-2 text-[#08251d]">Реальные фото гостей</span><span className="rounded-full border border-white/25 bg-black/25 px-3 py-2 backdrop-blur">Россия · Казахстан</span></div>
          <p className="mt-6 text-xs font-black uppercase tracking-[.22em] text-teal-200 sm:text-sm">SEA FISHING · VIETNAM</p>
          <h1 className="mt-3 max-w-4xl text-4xl font-black leading-[.98] tracking-tight sm:text-5xl lg:text-7xl">Морская рыбалка в Дананге и на Фукуоке</h1>
          <p className="mt-5 max-w-3xl text-base leading-relaxed text-white/85 sm:text-lg lg:text-xl">Профессиональные выходы для опытных рыболовов, дневная морская рыбалка и ночная ловля кальмара. Для профессионального формата навыки рыбалки обязательны. Цена и программа подтверждаются после уточнения деталей.</p>
          <div className="mt-7 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href={WHATSAPP} target="_blank" rel="noopener noreferrer" className="rounded-2xl bg-[#20a65a] px-6 py-4 text-center font-black text-white shadow-xl sm:rounded-full">Узнать программу и цену</a><a href="https://t.me/GoVietStay" target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-white/30 bg-black/20 px-6 py-4 text-center font-bold backdrop-blur sm:rounded-full">Telegram</a></div>
        </div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-10 lg:py-12"><div className="grid gap-3 sm:grid-cols-3">{[["Локации", "Только Дананг и Фукуок"], ["Профессиональный формат", "Опыт рыбалки обязателен"], ["Стоимость", "Точная цена после проверки деталей"]].map(([label, value]) => <div key={label} className="rounded-3xl border border-white/10 bg-white/[.055] p-5"><p className="text-[11px] font-black uppercase tracking-[.16em] text-teal-200">{label}</p><p className="mt-2 text-lg font-black sm:text-xl">{value}</p></div>)}</div></section>

    <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-10 lg:py-16">
      <div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300 sm:text-sm">Три разных формата</p><h2 className="mt-3 text-3xl font-black sm:text-4xl lg:text-5xl">Выберите, зачем вы хотите выйти в море</h2><p className="mt-4 leading-relaxed text-white/65">Мы не объединяем профессиональную рыбалку, обычный дневной выход и ловлю кальмара в один «универсальный тур». У них разные требования к опыту, судну, снастям, времени и морским условиям.</p></div>
      <div className="mt-8 grid gap-5 lg:grid-cols-3">{formats.map((item, index) => <article key={item.title} className={`overflow-hidden rounded-[2rem] border ${index === 0 ? "border-amber-300/45 bg-amber-300/[.055]" : "border-white/10 bg-white/[.045]"}`}><div className="relative aspect-[4/3] overflow-hidden"><Image src={item.image} alt={item.alt} fill sizes="(max-width: 1024px) 100vw, 33vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#061713] via-transparent to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-black/55 px-3 py-2 text-[10px] font-black tracking-[.16em] backdrop-blur">{item.number}</span></div><div className="p-6"><span className="rounded-full bg-amber-300/10 px-3 py-2 text-[10px] font-black uppercase tracking-[.14em] text-amber-200">{item.tag}</span><h3 className="mt-5 text-2xl font-black">{item.title}</h3><p className="mt-4 leading-relaxed text-white/65">{item.text}</p><ul className="mt-5 space-y-3 text-sm text-white/70">{item.bullets.map((bullet) => <li key={bullet} className="flex gap-3"><span className="text-teal-300">●</span><span>{bullet}</span></li>)}</ul></div></article>)}</div>
    </section>

    <section className="bg-[#f4eee0] text-[#0a2a21]"><div className="mx-auto grid max-w-7xl gap-7 px-4 py-12 sm:px-6 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:py-20">
      <figure className="relative min-h-[520px] overflow-hidden rounded-[2rem] bg-[#0a2a21] sm:min-h-[620px] lg:min-h-0"><Image src="/ru/fishing/pro-catch-big.webp" alt="Крупный улов во время морской рыбалки" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-6 pt-24 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-300">Профессиональный формат</p><p className="mt-2 text-sm text-white/75">Реальная фотография рыбалки. Результат каждого выхода зависит от условий моря.</p></div></figure>
      <div className="rounded-[2rem] bg-[#0a2a21] p-6 text-white sm:p-8 lg:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300 sm:text-sm">Не обычная экскурсия</p><h2 className="mt-3 text-3xl font-black sm:text-4xl lg:text-5xl">Профессиональная рыбалка — только для гостей с опытом</h2><p className="mt-5 leading-relaxed text-white/70">Если вы хотите полноценный рыболовный выход, свяжитесь с нами заранее. Нам важно понять ваш реальный уровень, привычный способ ловли и ожидания. Только после этого мы проверяем доступное судно, район выхода, снасти, продолжительность и актуальную цену.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{requestItems.map((item) => <div key={item} className="rounded-2xl border border-white/10 bg-white/[.065] p-4 text-sm font-semibold text-white/80">{item}</div>)}</div><a href={WHATSAPP} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex w-full justify-center rounded-2xl bg-amber-300 px-6 py-4 text-center font-black text-[#0a2a21] sm:w-auto sm:rounded-full">Отправить данные в WhatsApp</a></div>
    </div></section>

    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-10 lg:py-20"><div className="grid gap-5 md:grid-cols-2"><article className="rounded-[2rem] border border-teal-300/20 bg-teal-400/[.055] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-200">ДАНАНГ</p><h2 className="mt-3 text-3xl font-black">Рыбалка в Дананге</h2><p className="mt-4 leading-relaxed text-white/68">Дневные выходы, профессиональная рыбалка по предварительному запросу и ночная ловля кальмара. Доступность подтверждаем по фактическому состоянию моря.</p></article><article className="rounded-[2rem] border border-amber-300/20 bg-amber-300/[.05] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-amber-200">ФУКУОК</p><h2 className="mt-3 text-3xl font-black">Рыбалка на Фукуоке</h2><p className="mt-4 leading-relaxed text-white/68">Дневная рыбалка, профессиональный выход по предварительному запросу и вечерняя или ночная ловля кальмара. Район отеля важен для расчёта логистики до точки посадки.</p></article></div></section>

    <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-10 lg:pb-20"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300 sm:text-sm">Реальные фотографии</p><h2 className="mt-3 text-3xl font-black sm:text-4xl lg:text-5xl">Так выглядят наши морские выходы</h2></div><p className="max-w-xl text-sm leading-relaxed text-white/60">Мы используем фотографии реальных поездок, а не стоковые изображения. Большой улов на фото не означает гарантированный улов в каждой поездке.</p></div><div className="mt-8 grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-12"><figure className="relative col-span-2 aspect-[4/3] overflow-hidden rounded-[1.7rem] border border-white/10 lg:col-span-7 lg:row-span-2 lg:aspect-auto lg:min-h-[610px]"><Image src="/ru/fishing/guests-night-squid.webp" alt="Гости GoVietStay после ночной ловли кальмара" fill sizes="(max-width: 1024px) 100vw, 58vw" className="object-cover" /></figure><figure className="relative aspect-[3/4] overflow-hidden rounded-[1.7rem] border border-white/10 lg:col-span-5 lg:aspect-[4/3]"><Image src="/ru/fishing/night-squid-two-guests.webp" alt="Гости с кальмаром на ночной рыбалке" fill sizes="(max-width: 1024px) 50vw, 42vw" className="object-cover" /></figure><figure className="relative aspect-[3/4] overflow-hidden rounded-[1.7rem] border border-white/10 lg:col-span-5 lg:aspect-[4/3]"><Image src="/ru/fishing/pro-cuttlefish.webp" alt="Улов во время морской рыбалки" fill sizes="(max-width: 1024px) 50vw, 42vw" className="object-cover" /></figure></div></section>

    <section className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-10 lg:py-20"><p className="text-center text-xs font-black uppercase tracking-[.2em] text-amber-300 sm:text-sm">FAQ</p><h2 className="mt-3 text-center text-3xl font-black sm:text-4xl lg:text-5xl">Частые вопросы</h2><div className="mt-8 divide-y divide-white/10 rounded-[2rem] border border-white/10 bg-white/[.035] px-5 sm:px-8">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="cursor-pointer list-none pr-8 text-base font-black sm:text-lg">{question}<span className="float-right text-amber-300 transition group-open:rotate-45">＋</span></summary><p className="mt-4 leading-relaxed text-white/65">{answer}</p></details>)}</div></section>

    <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-10 lg:pb-24"><div className="overflow-hidden rounded-[2.2rem] border border-white/10 bg-gradient-to-br from-[#0d6b52] to-[#082b23]"><div className="grid lg:grid-cols-[1fr_.78fr]"><div className="p-7 sm:p-10 lg:p-12"><div className="flex items-center gap-3"><Image src="/govietstay-logo.jpg" alt="GoVietStay" width={48} height={48} className="h-12 w-12 rounded-2xl object-cover" /><p className="text-sm font-black uppercase tracking-[.16em] text-teal-100">GoVietStay · Trusted Local Support</p></div><h2 className="mt-6 text-3xl font-black sm:text-4xl lg:text-5xl">Хотите настоящую рыбалку, а не просто прогулку на лодке?</h2><p className="mt-5 max-w-2xl leading-relaxed text-white/75">Напишите локацию, дату, количество гостей и ваш опыт. Для профессиональной морской рыбалки навыки обязательны. Мы проверим подходящий формат и сообщим точную цену.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href={WHATSAPP} target="_blank" rel="noopener noreferrer" className="rounded-2xl bg-white px-6 py-4 text-center font-black text-[#0b503f] sm:rounded-full">WhatsApp · узнать цену</a><a href="https://t.me/GoVietStay" target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-white/30 px-6 py-4 text-center font-bold sm:rounded-full">Telegram</a></div></div><div className="relative min-h-[340px] lg:min-h-full"><Image src="/ru/fishing/pro-cuttlefish.webp" alt="Морская рыбалка GoVietStay" fill sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#082b23]/60 to-transparent lg:bg-gradient-to-r" /></div></div></div></section>

    <footer className="border-t border-white/10 px-4 py-8 text-center text-sm text-white/50 sm:px-6"><div className="flex flex-wrap justify-center gap-x-5 gap-y-3 font-semibold"><Link href="/ru">Главная</Link><Link href="/ru/danang">Дананг</Link><Link href="/ru/phu-quoc">Фукуок</Link><Link href="/ru/tours/phu-quoc">Туры на Фукуоке</Link></div></footer>
    <div className="fixed inset-x-0 bottom-0 z-50 border-t border-white/10 bg-[#061713]/95 p-3 backdrop-blur md:hidden"><div className="mx-auto flex max-w-lg gap-2"><a href={WHATSAPP} target="_blank" rel="noopener noreferrer" className="flex-1 rounded-2xl bg-[#20a65a] px-4 py-3 text-center text-sm font-black">WhatsApp · цена</a><a href="https://t.me/GoVietStay" target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-white/20 px-4 py-3 text-sm font-bold">Telegram</a></div></div>
  </main>;
}
