import type {Metadata} from "next";
import {israelSeoPages} from "../../lib/israelSeoPages";
import {israelMarketConfig as C} from "../../lib/israelMarketConfig";
import {getIsraelVisual,israelGuests} from "../../lib/israelVisuals";
import s from "./Israel.module.css";
export const metadata:Metadata={title:{absolute:"וייטנאם לישראלים 2026 | טיולים פרטיים | GoVietStay"},description:"טיולים פרטיים, דה נאנג, הוי אן, הואה ופו קווק עם WhatsApp ותמיכה מקומית.",alternates:{canonical:"https://www.govietstay.com/il",languages:{"he-IL":"https://www.govietstay.com/il"}}};
const picks=["bana-hills-golden-bridge","hoi-an-private-evening","cham-island-snorkeling","hue-day-trip","phu-quoc-3-islands","phu-quoc-4-islands-hon-thom"];
export default function Hub(){return <main className={s.page} dir="rtl">
<header><a href="/il"><img src="/govietstay-logo.jpg" alt="GoVietStay"/></a><nav><a href="#private">פרטי</a><a href="#price">מחירים</a><a href="/il/phu-quoc-guide-israelis">פו קווק</a><a className={s.wa} href={C.whatsapp}>WhatsApp</a></nav></header>
<section className={s.hero}><img src="/tour/coconut.jpg" alt="Hoi An"/><div><small>ישראל ← וייטנאם · FIT / PRIVATE</small><h1>את הטיסה והמלון תזמינו לבד. <em>בווייטנאם יהיה לכם צוות מקומי כשבאמת צריך.</em></h1><p>לזוגות, משפחות וקבוצות קטנות: פחות המתנה, יותר גמישות, מדריך בשפה המבוקשת ו-WhatsApp ישיר.</p><a href="#private">למה פרטי?</a><a href={C.whatsapp}>WhatsApp</a></div></section>
<section className={s.quick}><a href="/il/vietnam-evisa-israelis">e-Visa לישראלים</a><a href="/il/tel-aviv-hanoi-direct-flight">תל אביב–האנוי ישיר</a><a href="/il/hebrew-speaking-guide-vietnam">מדריך בעברית*</a><a href="/il/private-vietnam-trip-price">כמה עולה פרטי?</a></section>
<section id="private" className={s.private}><img src="/travelers/germany.jpg" alt="GoVietStay guests"/><div><small>WIIFM</small><h2>פרטי לא חייב להיות יוקרתי. לפעמים זה פשוט אומר שאף אחד אחר לא מנהל לכם את השעון.</h2><p>המחיר הרגיל נשאר זהה ל-English. משלמים תוספת רק אם רכב, מדריך, שעות או מסלול נותנים לכם יותר חופש.</p><div><b>הקבוצה שלכם</b><b>שעה גמישה</b><b>עברית/שפה אחרת*</b><b>בלי עצירות מיותרות</b></div><a href="/il/private-vietnam-trip">טיול פרטי ←</a></div></section>
<section id="price" className={s.section}><h2>מחיר רגיל = אותו מחיר English/public</h2><p>אין “מחיר ישראלי”. ₪ הוא רק אומדן להשוואה; VND הוא המחיר הרשמי.</p><div className={s.cards}>{picks.map(slug=>{const p:any=israelSeoPages.find(x=>x.slug===slug);const v=getIsraelVisual(p.slug,p.destination);const x=p.priceKey?C.standard[p.priceKey as keyof typeof C.standard]:null;return <a href={`/il/${slug}`} key={slug}><img src={v.hero} alt={p.h1}/><small>{p.destination}</small><h3>{p.h1}</h3><p>{p.wiifm}</p>{x?<strong dir="ltr">≈ ₪{x.ils} · {x.vnd.toLocaleString()} VND</strong>:<strong>הצעה לפי קבוצה</strong>}</a>})}</div></section>
<section className={s.dark}><h2>למה GoVietStay?</h2><div><article><b>01</b><h3>כשהתוכנית משתנה</h3><p>ים, מזג אוויר, טיסה או ילד עייף — כאן מקומי חוסך זמן.</p></article><article><b>02</b><h3>פרטי באמת</h3><p>לא מוסיפים זרים לחלק שאושר כפרטי.</p></article><article><b>03</b><h3>שפה לפי צורך</h3><p>{C.guide}</p></article><article><b>04</b><h3>מחיר שקוף</h3><p>רגיל במחיר English; פרטי לפי רכיבים אמיתיים.</p></article></div></section>
<section className={s.guests}><h2>תמונות אמיתיות מהאתר הראשי</h2><div>{israelGuests.map(x=><img key={x} src={x} alt="GoVietStay traveler"/>)}</div></section>
<section className={s.section}><h2>30 עמודים לפי שאלות אמיתיות</h2><div className={s.grid}>{israelSeoPages.map(p=><a href={`/il/${p.slug}`} key={p.slug}><small>{p.destination}</small><h3>{p.h1}</h3><p>{p.wiifm}</p><b>פתיחה ←</b></a>)}</div></section>
<footer><h2>כבר יש טיסה ומלון?</h2><p>שלחו תאריך, אנשים ומלון. מזה אפשר להתחיל.</p><a className={s.wa} href={C.whatsapp}>WhatsApp</a></footer>
</main>}