-- GoVietStay Yandex Intelligence V1
-- Stores Yandex Webmaster + Metrica snapshots for Owner/Admin dashboard.

create table if not exists public.yandex_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  date_from date not null,
  date_to date not null,
  webmaster_rows integer not null default 0,
  query_rows integer not null default 0,
  metrica_rows integer not null default 0,
  status text not null default 'running' check (status in ('running','success','failed')),
  error_message text,
  created_by uuid
);

create table if not exists public.yandex_webmaster_daily (
  date date not null,
  device text not null default 'ALL',
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  avg_show_position numeric(12,4) not null default 0,
  avg_click_position numeric(12,4) not null default 0,
  synced_at timestamptz not null default now(),
  primary key (date, device)
);

create table if not exists public.yandex_query_snapshots (
  date_from date not null,
  date_to date not null,
  query_id text not null,
  query_text text not null,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  avg_show_position numeric(12,4) not null default 0,
  avg_click_position numeric(12,4) not null default 0,
  synced_at timestamptz not null default now(),
  primary key (date_from, date_to, query_id)
);

create table if not exists public.yandex_metrica_snapshots (
  date_from date not null,
  date_to date not null,
  visits bigint not null default 0,
  users bigint not null default 0,
  pageviews bigint not null default 0,
  synced_at timestamptz not null default now(),
  primary key (date_from, date_to)
);

create table if not exists public.yandex_metrica_landing_snapshots (
  date_from date not null,
  date_to date not null,
  landing_page text not null,
  visits bigint not null default 0,
  users bigint not null default 0,
  pageviews bigint not null default 0,
  synced_at timestamptz not null default now(),
  primary key (date_from, date_to, landing_page)
);

create index if not exists yandex_sync_runs_started_idx on public.yandex_sync_runs (started_at desc);
create index if not exists yandex_query_snapshots_imp_idx on public.yandex_query_snapshots (date_from, date_to, impressions desc);
create index if not exists yandex_metrica_landing_visits_idx on public.yandex_metrica_landing_snapshots (date_from, date_to, visits desc);

alter table public.yandex_sync_runs enable row level security;
alter table public.yandex_webmaster_daily enable row level security;
alter table public.yandex_query_snapshots enable row level security;
alter table public.yandex_metrica_snapshots enable row level security;
alter table public.yandex_metrica_landing_snapshots enable row level security;

grant select, insert, update, delete on public.yandex_sync_runs to authenticated;
grant select, insert, update, delete on public.yandex_webmaster_daily to authenticated;
grant select, insert, update, delete on public.yandex_query_snapshots to authenticated;
grant select, insert, update, delete on public.yandex_metrica_snapshots to authenticated;
grant select, insert, update, delete on public.yandex_metrica_landing_snapshots to authenticated;
grant usage, select on sequence public.yandex_sync_runs_id_seq to authenticated;

-- Owner/Admin-only access, matching the existing GoVietStay Admin auth model.
drop policy if exists "yandex_admin_sync_runs" on public.yandex_sync_runs;
create policy "yandex_admin_sync_runs" on public.yandex_sync_runs for all to authenticated
using (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')))
with check (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')));

drop policy if exists "yandex_admin_webmaster_daily" on public.yandex_webmaster_daily;
create policy "yandex_admin_webmaster_daily" on public.yandex_webmaster_daily for all to authenticated
using (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')))
with check (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')));

drop policy if exists "yandex_admin_queries" on public.yandex_query_snapshots;
create policy "yandex_admin_queries" on public.yandex_query_snapshots for all to authenticated
using (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')))
with check (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')));

drop policy if exists "yandex_admin_metrica" on public.yandex_metrica_snapshots;
create policy "yandex_admin_metrica" on public.yandex_metrica_snapshots for all to authenticated
using (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')))
with check (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')));

drop policy if exists "yandex_admin_landings" on public.yandex_metrica_landing_snapshots;
create policy "yandex_admin_landings" on public.yandex_metrica_landing_snapshots for all to authenticated
using (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')))
with check (exists (select 1 from public.staff_profiles s where s.auth_user_id = auth.uid() and s.active = true and s.role in ('owner','admin')));

